[theme]
prefix = "slx-theme"
dark_mode = "class"

[theme.colors]
brand-primary = "#6366f1"
brand-accent = "#ec4899"

[theme.dark_colors]
brand-primary = "#818cf8"
brand-accent = "#f472b6"

[theme.breakpoints]
"3xl" = "1920px"
