[package]
name = "silex_net"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
silex_core.workspace = true
silex_persist = { workspace = true, optional = true }
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "AbortController",
    "AbortSignal",
    "CloseEvent",
    "ErrorEvent",
    "Event",
    "EventSource",
    "FormData",
    "Headers",
    "MessageEvent",
    "Request",
    "RequestCredentials",
    "RequestInit",
    "Response",
    "Storage",
    "WebSocket",
    "Window"
] }
js-sys.workspace = true
sha2.workspace = true
wasm-bindgen-futures.workspace = true
gloo-timers.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = []
json = ["dep:serde", "dep:serde_json", "silex_persist/json"]
persist = ["dep:silex_persist"]

[dev-dependencies]
trybuild = "1.0"
js-sys = { workspace = true, features = ["unsafe-eval"] }
silex_core = { workspace = true, features = ["test-support"] }
wasm-bindgen-test.workspace = true
