[package]
name = "silex_persist"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
silex_core = { workspace = true, features = ["error-persistence"] }
silex_view.workspace = true
silex_router.workspace = true
gloo-timers = { workspace = true, features = ["futures"] }
ref_str = "0.2"
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Storage",
    "StorageEvent",
    "Window"
] }
js-sys.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
gloo-timers.workspace = true
silex_view = { workspace = true, features = ["browser"] }
trybuild = "1.0"
wasm-bindgen-test.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
silex_dom.workspace = true

[features]
default = []
json = ["dep:serde", "dep:serde_json"]
