[package]
name = "silex_counter"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
silex = { workspace = true, features = ["bootstrap"] }
silex_view.workspace = true
gloo-timers.workspace = true
wasm-bindgen.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
