[package]
name = "silex_html"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
silex_dom.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlButtonElement",
    "HtmlOptionElement",
    "HtmlOptGroupElement",
    "HtmlAnchorElement",
    "HtmlCanvasElement",
    "HtmlFormElement",
    "HtmlImageElement",
    "HtmlAudioElement",
    "HtmlVideoElement",
    "HtmlDialogElement",
    "HtmlDetailsElement",
    "HtmlIFrameElement",
    "SvgElement",
    "SvgaElement",
] }

[dev-dependencies]
silex_core.workspace = true
trybuild = "1.0"
wasm-bindgen-test.workspace = true
web-sys = { workspace = true, features = [
    "Document",
    "Element",
    "HtmlAnchorElement",
    "Node",
    "SvgaElement",
    "Window",
] }
