[package]
name = "silex_html"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
silex_view = { workspace = true, features = ["browser"] }

[dev-dependencies]
silex_core.workspace = true
silex_dom.workspace = true
trybuild = "1.0"
wasm-bindgen-test.workspace = true
web-sys = { workspace = true, features = [
    "Document",
    "Element",
    "HtmlAnchorElement",
    "Node",
    "SvgaElement",
    "Window",
] }
