use crate::types::units::{Hex, hex};
use core::fmt::{self, Display, Formatter};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ColorName {
    Transparent,
    CurrentColor,
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenRod,
    DarkGray,
    DarkGreen,
    DarkGrey,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    DarkSlateGrey,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DimGrey,
    DodgerBlue,
    FireBrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    GoldenRod,
    Gray,
    Green,
    GreenYellow,
    Grey,
    HoneyDew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenRodYellow,
    LightGray,
    LightGreen,
    LightGrey,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    LightSlateGrey,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MediumAquaMarine,
    MediumBlue,
    MediumOrchid,
    MediumPurple,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenRod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    RebeccaPurple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    SlateGrey,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

pub type NamedColor = ColorName;

impl Default for ColorName {
    #[inline]
    fn default() -> Self {
        ColorName::Transparent
    }
}

impl ColorName {
    /// 获取对应的 CSS 颜色关键字名称字符串（例如 `"red"`, `"cornflowerblue"`, `"transparent"`）。
    #[inline]
    pub const fn as_str(&self) -> &'static str {
        match self {
            ColorName::Transparent => "transparent",
            ColorName::CurrentColor => "currentColor",
            ColorName::AliceBlue => "aliceblue",
            ColorName::AntiqueWhite => "antiquewhite",
            ColorName::Aqua => "aqua",
            ColorName::Aquamarine => "aquamarine",
            ColorName::Azure => "azure",
            ColorName::Beige => "beige",
            ColorName::Bisque => "bisque",
            ColorName::Black => "black",
            ColorName::BlanchedAlmond => "blanchedalmond",
            ColorName::Blue => "blue",
            ColorName::BlueViolet => "blueviolet",
            ColorName::Brown => "brown",
            ColorName::BurlyWood => "burlywood",
            ColorName::CadetBlue => "cadetblue",
            ColorName::Chartreuse => "chartreuse",
            ColorName::Chocolate => "chocolate",
            ColorName::Coral => "coral",
            ColorName::CornflowerBlue => "cornflowerblue",
            ColorName::Cornsilk => "cornsilk",
            ColorName::Crimson => "crimson",
            ColorName::Cyan => "cyan",
            ColorName::DarkBlue => "darkblue",
            ColorName::DarkCyan => "darkcyan",
            ColorName::DarkGoldenRod => "darkgoldenrod",
            ColorName::DarkGray => "darkgray",
            ColorName::DarkGreen => "darkgreen",
            ColorName::DarkGrey => "darkgrey",
            ColorName::DarkKhaki => "darkkhaki",
            ColorName::DarkMagenta => "darkmagenta",
            ColorName::DarkOliveGreen => "darkolivegreen",
            ColorName::DarkOrange => "darkorange",
            ColorName::DarkOrchid => "darkorchid",
            ColorName::DarkRed => "darkred",
            ColorName::DarkSalmon => "darksalmon",
            ColorName::DarkSeaGreen => "darkseagreen",
            ColorName::DarkSlateBlue => "darkslateblue",
            ColorName::DarkSlateGray => "darkslategray",
            ColorName::DarkSlateGrey => "darkslategrey",
            ColorName::DarkTurquoise => "darkturquoise",
            ColorName::DarkViolet => "darkviolet",
            ColorName::DeepPink => "deeppink",
            ColorName::DeepSkyBlue => "deepskyblue",
            ColorName::DimGray => "dimgray",
            ColorName::DimGrey => "dimgrey",
            ColorName::DodgerBlue => "dodgerblue",
            ColorName::FireBrick => "firebrick",
            ColorName::FloralWhite => "floralwhite",
            ColorName::ForestGreen => "forestgreen",
            ColorName::Fuchsia => "fuchsia",
            ColorName::Gainsboro => "gainsboro",
            ColorName::GhostWhite => "ghostwhite",
            ColorName::Gold => "gold",
            ColorName::GoldenRod => "goldenrod",
            ColorName::Gray => "gray",
            ColorName::Green => "green",
            ColorName::GreenYellow => "greenyellow",
            ColorName::Grey => "grey",
            ColorName::HoneyDew => "honeydew",
            ColorName::HotPink => "hotpink",
            ColorName::IndianRed => "indianred",
            ColorName::Indigo => "indigo",
            ColorName::Ivory => "ivory",
            ColorName::Khaki => "khaki",
            ColorName::Lavender => "lavender",
            ColorName::LavenderBlush => "lavenderblush",
            ColorName::LawnGreen => "lawngreen",
            ColorName::LemonChiffon => "lemonchiffon",
            ColorName::LightBlue => "lightblue",
            ColorName::LightCoral => "lightcoral",
            ColorName::LightCyan => "lightcyan",
            ColorName::LightGoldenRodYellow => "lightgoldenrodyellow",
            ColorName::LightGray => "lightgray",
            ColorName::LightGreen => "lightgreen",
            ColorName::LightGrey => "lightgrey",
            ColorName::LightPink => "lightpink",
            ColorName::LightSalmon => "lightsalmon",
            ColorName::LightSeaGreen => "lightseagreen",
            ColorName::LightSkyBlue => "lightskyblue",
            ColorName::LightSlateGray => "lightslategray",
            ColorName::LightSlateGrey => "lightslategrey",
            ColorName::LightSteelBlue => "lightsteelblue",
            ColorName::LightYellow => "lightyellow",
            ColorName::Lime => "lime",
            ColorName::LimeGreen => "limegreen",
            ColorName::Linen => "linen",
            ColorName::Magenta => "magenta",
            ColorName::Maroon => "maroon",
            ColorName::MediumAquaMarine => "mediumaquamarine",
            ColorName::MediumBlue => "mediumblue",
            ColorName::MediumOrchid => "mediumorchid",
            ColorName::MediumPurple => "mediumpurple",
            ColorName::MediumSeaGreen => "mediumseagreen",
            ColorName::MediumSlateBlue => "mediumslateblue",
            ColorName::MediumSpringGreen => "mediumspringgreen",
            ColorName::MediumTurquoise => "mediumturquoise",
            ColorName::MediumVioletRed => "mediumvioletred",
            ColorName::MidnightBlue => "midnightblue",
            ColorName::MintCream => "mintcream",
            ColorName::MistyRose => "mistyrose",
            ColorName::Moccasin => "moccasin",
            ColorName::NavajoWhite => "navajowhite",
            ColorName::Navy => "navy",
            ColorName::OldLace => "oldlace",
            ColorName::Olive => "olive",
            ColorName::OliveDrab => "olivedrab",
            ColorName::Orange => "orange",
            ColorName::OrangeRed => "orangered",
            ColorName::Orchid => "orchid",
            ColorName::PaleGoldenRod => "palegoldenrod",
            ColorName::PaleGreen => "palegreen",
            ColorName::PaleTurquoise => "paleturquoise",
            ColorName::PaleVioletRed => "palevioletred",
            ColorName::PapayaWhip => "papayawhip",
            ColorName::PeachPuff => "peachpuff",
            ColorName::Peru => "peru",
            ColorName::Pink => "pink",
            ColorName::Plum => "plum",
            ColorName::PowderBlue => "powderblue",
            ColorName::Purple => "purple",
            ColorName::RebeccaPurple => "rebeccapurple",
            ColorName::Red => "red",
            ColorName::RosyBrown => "rosybrown",
            ColorName::RoyalBlue => "royalblue",
            ColorName::SaddleBrown => "saddlebrown",
            ColorName::Salmon => "salmon",
            ColorName::SandyBrown => "sandybrown",
            ColorName::SeaGreen => "seagreen",
            ColorName::SeaShell => "seashell",
            ColorName::Sienna => "sienna",
            ColorName::Silver => "silver",
            ColorName::SkyBlue => "skyblue",
            ColorName::SlateBlue => "slateblue",
            ColorName::SlateGray => "slategray",
            ColorName::SlateGrey => "slategrey",
            ColorName::Snow => "snow",
            ColorName::SpringGreen => "springgreen",
            ColorName::SteelBlue => "steelblue",
            ColorName::Tan => "tan",
            ColorName::Teal => "teal",
            ColorName::Thistle => "thistle",
            ColorName::Tomato => "tomato",
            ColorName::Turquoise => "turquoise",
            ColorName::Violet => "violet",
            ColorName::Wheat => "wheat",
            ColorName::White => "white",
            ColorName::WhiteSmoke => "whitesmoke",
            ColorName::Yellow => "yellow",
            ColorName::YellowGreen => "yellowgreen",
        }
    }

    /// 尝试将预定义颜色转化为对应的十六进制 `Hex` 对象（如 `Red` -> `#ff0000`）。
    ///
    /// 对于 `Transparent` 和 `CurrentColor` 等关键字，返回 `None`。
    pub fn to_hex(&self) -> Option<Hex> {
        let hex_str = match self {
            ColorName::Transparent | ColorName::CurrentColor => return None,
            ColorName::AliceBlue => "#f0f8ff",
            ColorName::AntiqueWhite => "#faebd7",
            ColorName::Aqua | ColorName::Cyan => "#00ffff",
            ColorName::Aquamarine => "#7fffd4",
            ColorName::Azure => "#f0ffff",
            ColorName::Beige => "#f5f5dc",
            ColorName::Bisque => "#ffe4c4",
            ColorName::Black => "#000000",
            ColorName::BlanchedAlmond => "#ffebcd",
            ColorName::Blue => "#0000ff",
            ColorName::BlueViolet => "#8a2be2",
            ColorName::Brown => "#a52a2a",
            ColorName::BurlyWood => "#deb887",
            ColorName::CadetBlue => "#5f9ea0",
            ColorName::Chartreuse => "#7fff00",
            ColorName::Chocolate => "#d2691e",
            ColorName::Coral => "#ff7f50",
            ColorName::CornflowerBlue => "#6495ed",
            ColorName::Cornsilk => "#fff8dc",
            ColorName::Crimson => "#dc143c",
            ColorName::DarkBlue => "#00008b",
            ColorName::DarkCyan => "#008b8b",
            ColorName::DarkGoldenRod => "#b8860b",
            ColorName::DarkGray | ColorName::DarkGrey => "#a9a9a9",
            ColorName::DarkGreen => "#006400",
            ColorName::DarkKhaki => "#bdb76b",
            ColorName::DarkMagenta => "#8b008b",
            ColorName::DarkOliveGreen => "#556b2f",
            ColorName::DarkOrange => "#ff8c00",
            ColorName::DarkOrchid => "#9932cc",
            ColorName::DarkRed => "#8b0000",
            ColorName::DarkSalmon => "#e9967a",
            ColorName::DarkSeaGreen => "#8fbc8f",
            ColorName::DarkSlateBlue => "#483d8b",
            ColorName::DarkSlateGray | ColorName::DarkSlateGrey => "#2f4f4f",
            ColorName::DarkTurquoise => "#00ced1",
            ColorName::DarkViolet => "#9400d3",
            ColorName::DeepPink => "#ff1493",
            ColorName::DeepSkyBlue => "#00bfff",
            ColorName::DimGray | ColorName::DimGrey => "#696969",
            ColorName::DodgerBlue => "#1e90ff",
            ColorName::FireBrick => "#b22222",
            ColorName::FloralWhite => "#fffaf0",
            ColorName::ForestGreen => "#228b22",
            ColorName::Fuchsia | ColorName::Magenta => "#ff00ff",
            ColorName::Gainsboro => "#dcdcdc",
            ColorName::GhostWhite => "#f8f8ff",
            ColorName::Gold => "#ffd700",
            ColorName::GoldenRod => "#daa520",
            ColorName::Gray | ColorName::Grey => "#808080",
            ColorName::Green => "#008000",
            ColorName::GreenYellow => "#adff2f",
            ColorName::HoneyDew => "#f0fff0",
            ColorName::HotPink => "#ff69b4",
            ColorName::IndianRed => "#cd5c5c",
            ColorName::Indigo => "#4b0082",
            ColorName::Ivory => "#fffff0",
            ColorName::Khaki => "#f0e68c",
            ColorName::Lavender => "#e6e6fa",
            ColorName::LavenderBlush => "#fff0f5",
            ColorName::LawnGreen => "#7cfc00",
            ColorName::LemonChiffon => "#fffacd",
            ColorName::LightBlue => "#add8e6",
            ColorName::LightCoral => "#f08080",
            ColorName::LightCyan => "#e0ffff",
            ColorName::LightGoldenRodYellow => "#fafad2",
            ColorName::LightGray | ColorName::LightGrey => "#d3d3d3",
            ColorName::LightGreen => "#90ee90",
            ColorName::LightPink => "#ffb6c1",
            ColorName::LightSalmon => "#ffa07a",
            ColorName::LightSeaGreen => "#20b2aa",
            ColorName::LightSkyBlue => "#87cefa",
            ColorName::LightSlateGray | ColorName::LightSlateGrey => "#778899",
            ColorName::LightSteelBlue => "#b0c4de",
            ColorName::LightYellow => "#ffffe0",
            ColorName::Lime => "#00ff00",
            ColorName::LimeGreen => "#32cd32",
            ColorName::Linen => "#faf0e6",
            ColorName::Maroon => "#800000",
            ColorName::MediumAquaMarine => "#66cdaa",
            ColorName::MediumBlue => "#0000cd",
            ColorName::MediumOrchid => "#ba55d3",
            ColorName::MediumPurple => "#9370db",
            ColorName::MediumSeaGreen => "#3cb371",
            ColorName::MediumSlateBlue => "#7b68ee",
            ColorName::MediumSpringGreen => "#00fa9a",
            ColorName::MediumTurquoise => "#48d1cc",
            ColorName::MediumVioletRed => "#c71585",
            ColorName::MidnightBlue => "#191970",
            ColorName::MintCream => "#f5fffa",
            ColorName::MistyRose => "#ffe4e1",
            ColorName::Moccasin => "#ffe4b5",
            ColorName::NavajoWhite => "#ffdead",
            ColorName::Navy => "#000080",
            ColorName::OldLace => "#fdf5e6",
            ColorName::Olive => "#808000",
            ColorName::OliveDrab => "#6b8e23",
            ColorName::Orange => "#ffa500",
            ColorName::OrangeRed => "#ff4500",
            ColorName::Orchid => "#da70d6",
            ColorName::PaleGoldenRod => "#eee8aa",
            ColorName::PaleGreen => "#98fb98",
            ColorName::PaleTurquoise => "#afeeee",
            ColorName::PaleVioletRed => "#db7093",
            ColorName::PapayaWhip => "#ffefd5",
            ColorName::PeachPuff => "#ffdab9",
            ColorName::Peru => "#cd853f",
            ColorName::Pink => "#ffc0cb",
            ColorName::Plum => "#dda0dd",
            ColorName::PowderBlue => "#b0e0e6",
            ColorName::Purple => "#800080",
            ColorName::RebeccaPurple => "#663399",
            ColorName::Red => "#ff0000",
            ColorName::RosyBrown => "#bc8f8f",
            ColorName::RoyalBlue => "#4169e1",
            ColorName::SaddleBrown => "#8b4513",
            ColorName::Salmon => "#fa8072",
            ColorName::SandyBrown => "#f4a460",
            ColorName::SeaGreen => "#2e8b57",
            ColorName::SeaShell => "#fff5ee",
            ColorName::Sienna => "#a0522d",
            ColorName::Silver => "#c0c0c0",
            ColorName::SkyBlue => "#87ceeb",
            ColorName::SlateBlue => "#6a5acd",
            ColorName::SlateGray | ColorName::SlateGrey => "#708090",
            ColorName::Snow => "#fffafa",
            ColorName::SpringGreen => "#00ff7f",
            ColorName::SteelBlue => "#4682b4",
            ColorName::Tan => "#d2b48c",
            ColorName::Teal => "#008080",
            ColorName::Thistle => "#d8bfd8",
            ColorName::Tomato => "#ff6347",
            ColorName::Turquoise => "#40e0d0",
            ColorName::Violet => "#ee82ee",
            ColorName::Wheat => "#f5deb3",
            ColorName::White => "#ffffff",
            ColorName::WhiteSmoke => "#f5f5f5",
            ColorName::Yellow => "#ffff00",
            ColorName::YellowGreen => "#9acd32",
        };
        Some(hex(hex_str))
    }
}

impl Display for ColorName {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn color_name_displays_as_css_keyword() {
        assert_eq!(ColorName::Red.to_string(), "red");
        assert_eq!(ColorName::ForestGreen.to_string(), "forestgreen");
        assert_eq!(ColorName::Transparent.to_string(), "transparent");
        assert_eq!(ColorName::CurrentColor.to_string(), "currentColor");
    }

    #[test]
    fn color_name_converts_to_hex() {
        assert_eq!(ColorName::Red.to_hex(), Some(hex("#ff0000")));
        assert_eq!(ColorName::White.to_hex(), Some(hex("#ffffff")));
        assert_eq!(ColorName::Transparent.to_hex(), None);
    }
}
