/// 交互、滚动与可访问性规则解析
pub fn resolve_interactivity_rules(class_name: &str) -> Option<Vec<(&'static str, String)>> {
    let rules: Option<&'static [(&'static str, &'static str)]> = match class_name {
        // Accessibility
        "sr-only" => Some(&[
            ("position", "absolute"),
            ("width", "1px"),
            ("height", "1px"),
            ("padding", "0"),
            ("margin", "-1px"),
            ("overflow", "hidden"),
            ("clip", "rect(0, 0, 0, 0)"),
            ("white-space", "nowrap"),
            ("border-width", "0"),
        ]),
        "not-sr-only" => Some(&[
            ("position", "static"),
            ("width", "auto"),
            ("height", "auto"),
            ("padding", "0"),
            ("margin", "0"),
            ("overflow", "visible"),
            ("clip", "auto"),
            ("white-space", "normal"),
        ]),

        // Cursors
        "cursor-pointer" => Some(&[("cursor", "pointer")]),
        "cursor-default" => Some(&[("cursor", "default")]),
        "cursor-not-allowed" => Some(&[("cursor", "not-allowed")]),
        "cursor-wait" => Some(&[("cursor", "wait")]),
        "cursor-move" => Some(&[("cursor", "move")]),
        "cursor-text" => Some(&[("cursor", "text")]),
        "cursor-auto" => Some(&[("cursor", "auto")]),
        "cursor-none" => Some(&[("cursor", "none")]),
        "cursor-context-menu" => Some(&[("cursor", "context-menu")]),
        "cursor-help" => Some(&[("cursor", "help")]),
        "cursor-progress" => Some(&[("cursor", "progress")]),
        "cursor-cell" => Some(&[("cursor", "cell")]),
        "cursor-crosshair" => Some(&[("cursor", "crosshair")]),
        "cursor-vertical-text" => Some(&[("cursor", "vertical-text")]),
        "cursor-alias" => Some(&[("cursor", "alias")]),
        "cursor-copy" => Some(&[("cursor", "copy")]),
        "cursor-no-drop" => Some(&[("cursor", "no-drop")]),
        "cursor-grab" => Some(&[("cursor", "grab")]),
        "cursor-grabbing" => Some(&[("cursor", "grabbing")]),
        "cursor-all-scroll" => Some(&[("cursor", "all-scroll")]),
        "cursor-col-resize" => Some(&[("cursor", "col-resize")]),
        "cursor-row-resize" => Some(&[("cursor", "row-resize")]),
        "cursor-n-resize" => Some(&[("cursor", "n-resize")]),
        "cursor-e-resize" => Some(&[("cursor", "e-resize")]),
        "cursor-s-resize" => Some(&[("cursor", "s-resize")]),
        "cursor-w-resize" => Some(&[("cursor", "w-resize")]),
        "cursor-ne-resize" => Some(&[("cursor", "ne-resize")]),
        "cursor-nw-resize" => Some(&[("cursor", "nw-resize")]),
        "cursor-se-resize" => Some(&[("cursor", "se-resize")]),
        "cursor-sw-resize" => Some(&[("cursor", "sw-resize")]),
        "cursor-ew-resize" => Some(&[("cursor", "ew-resize")]),
        "cursor-ns-resize" => Some(&[("cursor", "ns-resize")]),
        "cursor-nesw-resize" => Some(&[("cursor", "nesw-resize")]),
        "cursor-nwse-resize" => Some(&[("cursor", "nwse-resize")]),
        "cursor-zoom-in" => Some(&[("cursor", "zoom-in")]),
        "cursor-zoom-out" => Some(&[("cursor", "zoom-out")]),

        // Pointer Events & User Select
        "pointer-events-none" => Some(&[("pointer-events", "none")]),
        "pointer-events-auto" => Some(&[("pointer-events", "auto")]),
        "select-none" => Some(&[("user-select", "none")]),
        "select-text" => Some(&[("user-select", "text")]),
        "select-all" => Some(&[("user-select", "all")]),
        "select-auto" => Some(&[("user-select", "auto")]),

        // Resize & Touch Action
        "resize-none" => Some(&[("resize", "none")]),
        "resize-y" => Some(&[("resize", "vertical")]),
        "resize-x" => Some(&[("resize", "horizontal")]),
        "resize" => Some(&[("resize", "both")]),
        "touch-auto" => Some(&[("touch-action", "auto")]),
        "touch-none" => Some(&[("touch-action", "none")]),
        "touch-pan-x" => Some(&[("touch-action", "pan-x")]),
        "touch-pan-left" => Some(&[("touch-action", "pan-left")]),
        "touch-pan-right" => Some(&[("touch-action", "pan-right")]),
        "touch-pan-y" => Some(&[("touch-action", "pan-y")]),
        "touch-pan-up" => Some(&[("touch-action", "pan-up")]),
        "touch-pan-down" => Some(&[("touch-action", "pan-down")]),
        "touch-pinch-zoom" => Some(&[("touch-action", "pinch-zoom")]),
        "touch-manipulation" => Some(&[("touch-action", "manipulation")]),

        // Scroll Behavior & Scrollbar & Color Scheme
        "scroll-smooth" => Some(&[("scroll-behavior", "smooth")]),
        "scroll-auto" => Some(&[("scroll-behavior", "auto")]),
        "scrollbar-auto" => Some(&[("scrollbar-width", "auto")]),
        "scrollbar-none" => Some(&[("scrollbar-width", "none")]),
        "scrollbar-thin" => Some(&[("scrollbar-width", "thin")]),
        "scrollbar-gutter-auto" => Some(&[("scrollbar-gutter", "auto")]),
        "scrollbar-gutter-stable" => Some(&[("scrollbar-gutter", "stable")]),
        "scrollbar-gutter-both" => Some(&[("scrollbar-gutter", "stable both-edges")]),
        "scheme-normal" => Some(&[("color-scheme", "normal")]),
        "scheme-light" => Some(&[("color-scheme", "light")]),
        "scheme-dark" => Some(&[("color-scheme", "dark")]),
        "scheme-light-dark" => Some(&[("color-scheme", "light dark")]),
        "scheme-only-light" => Some(&[("color-scheme", "only light")]),
        "scheme-only-dark" => Some(&[("color-scheme", "only dark")]),

        // Scroll Snap
        "snap-none" => Some(&[("scroll-snap-type", "none")]),
        "snap-x" => Some(&[("scroll-snap-type", "x var(--tw-scroll-snap-strictness)")]),
        "snap-y" => Some(&[("scroll-snap-type", "y var(--tw-scroll-snap-strictness)")]),
        "snap-both" => Some(&[("scroll-snap-type", "both var(--tw-scroll-snap-strictness)")]),
        "snap-mandatory" => Some(&[("--tw-scroll-snap-strictness", "mandatory")]),
        "snap-proximity" => Some(&[("--tw-scroll-snap-strictness", "proximity")]),
        "snap-start" => Some(&[("scroll-snap-align", "start")]),
        "snap-end" => Some(&[("scroll-snap-align", "end")]),
        "snap-center" => Some(&[("scroll-snap-align", "center")]),
        "snap-align-none" => Some(&[("scroll-snap-align", "none")]),
        "snap-normal" => Some(&[("scroll-snap-stop", "normal")]),
        "snap-always" => Some(&[("scroll-snap-stop", "always")]),

        // Vertical Align
        "align-baseline" => Some(&[("vertical-align", "baseline")]),
        "align-top" => Some(&[("vertical-align", "top")]),
        "align-middle" => Some(&[("vertical-align", "middle")]),
        "align-bottom" => Some(&[("vertical-align", "bottom")]),
        "align-text-top" => Some(&[("vertical-align", "text-top")]),
        "align-text-bottom" => Some(&[("vertical-align", "text-bottom")]),
        "align-sub" => Some(&[("vertical-align", "sub")]),
        "align-super" => Some(&[("vertical-align", "super")]),

        // Appearance
        "appearance-none" => Some(&[("appearance", "none")]),
        "appearance-auto" => Some(&[("appearance", "auto")]),

        // Will-Change & Forced Colors & Accent
        "will-change-auto" => Some(&[("will-change", "auto")]),
        "will-change-scroll" => Some(&[("will-change", "scroll-position")]),
        "will-change-contents" => Some(&[("will-change", "contents")]),
        "will-change-transform" => Some(&[("will-change", "transform")]),
        "forced-color-adjust-auto" => Some(&[("forced-color-adjust", "auto")]),
        "forced-color-adjust-none" => Some(&[("forced-color-adjust", "none")]),
        "accent-auto" => Some(&[("accent-color", "auto")]),

        _ => None,
    };

    rules.map(|r| r.iter().map(|&(k, v)| (k, v.to_string())).collect())
}
