// 自动生成的 Utility 前缀与单位元数据表（供 silex_macros 使用）
// 由 silex_codegen 自动生成，切勿手写修改！

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnitKind {
    RemScale,
    Pixel,
    Percentage,
    Degree,
    Milliseconds,
    Unitless,
    GridRepeat,
    GridSpan,
}

pub struct PrefixMeta {
    pub target_props: &'static [&'static str],
    pub unit_kind: UnitKind,
}

#[rustfmt::skip]
pub static PREFIX_METADATA: &[PrefixMeta] = &[
    PrefixMeta { target_props: &["grid-auto-columns"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["grid-auto-rows"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-bottom-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-block-end-style", "border-block-end-width", "inherits", "initial-value", "syntax"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-block-start-style", "border-block-start-width", "inherits", "initial-value", "syntax"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-inline-end-style", "border-inline-end-width", "inherits", "initial-value", "syntax"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-left-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-right-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-inline-start-style", "border-inline-start-width", "inherits", "initial-value", "syntax"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-top-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-left-width", "border-right-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["border-top-width", "border-bottom-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["grid-column-end"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["grid-column"], unit_kind: UnitKind::GridSpan },
    PrefixMeta { target_props: &["grid-column-start"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["column-count"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["transition-delay"], unit_kind: UnitKind::Milliseconds },
    PrefixMeta { target_props: &["transition-duration"], unit_kind: UnitKind::Milliseconds },
    PrefixMeta { target_props: &["--tw-enter-opacity"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["--tw-exit-opacity"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["gap"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["column-gap"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["row-gap"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["grid-template-columns"], unit_kind: UnitKind::GridRepeat },
    PrefixMeta { target_props: &["grid-template-rows"], unit_kind: UnitKind::GridRepeat },
    PrefixMeta { target_props: &["height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["top", "right", "bottom", "left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["left", "right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["top", "bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["--tw-leading", "inherits", "line-height", "syntax"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["-webkit-line-clamp"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["margin"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["max-height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["max-width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["min-height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["min-width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin-left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin-top"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin-left", "margin-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["margin-top", "margin-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["opacity"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["outline-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["padding"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding-left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding-top"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding-left", "padding-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["padding-top", "padding-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Degree },
    PrefixMeta { target_props: &["grid-row-end"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["grid-row"], unit_kind: UnitKind::GridSpan },
    PrefixMeta { target_props: &["grid-row-start"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["width", "height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Degree },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Degree },
    PrefixMeta { target_props: &["--tw-enter-translate-y"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["--tw-enter-translate-x"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["--tw-enter-translate-x"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["--tw-enter-translate-y"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["top"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["text-underline-offset"], unit_kind: UnitKind::Pixel },
    PrefixMeta { target_props: &["width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { target_props: &["z-index"], unit_kind: UnitKind::Unitless },
    PrefixMeta { target_props: &["--tw-enter-scale"], unit_kind: UnitKind::Percentage },
    PrefixMeta { target_props: &["--tw-exit-scale"], unit_kind: UnitKind::Percentage },
];

/// 根据 Utility 前缀静态匹配对应的元数据配置
pub fn lookup_prefix_meta(prefix: &str) -> Option<&'static PrefixMeta> {
    match prefix {
        "auto-cols" => Some(&PREFIX_METADATA[0]),
        "auto-rows" => Some(&PREFIX_METADATA[1]),
        "backdrop-blur" => Some(&PREFIX_METADATA[2]),
        "blur" => Some(&PREFIX_METADATA[3]),
        "border" => Some(&PREFIX_METADATA[4]),
        "border-b" => Some(&PREFIX_METADATA[5]),
        "border-be" => Some(&PREFIX_METADATA[6]),
        "border-bs" => Some(&PREFIX_METADATA[7]),
        "border-e" => Some(&PREFIX_METADATA[8]),
        "border-l" => Some(&PREFIX_METADATA[9]),
        "border-r" => Some(&PREFIX_METADATA[10]),
        "border-s" => Some(&PREFIX_METADATA[11]),
        "border-t" => Some(&PREFIX_METADATA[12]),
        "border-x" => Some(&PREFIX_METADATA[13]),
        "border-y" => Some(&PREFIX_METADATA[14]),
        "bottom" => Some(&PREFIX_METADATA[15]),
        "col-end" => Some(&PREFIX_METADATA[16]),
        "col-span" => Some(&PREFIX_METADATA[17]),
        "col-start" => Some(&PREFIX_METADATA[18]),
        "columns" => Some(&PREFIX_METADATA[19]),
        "delay" => Some(&PREFIX_METADATA[20]),
        "duration" => Some(&PREFIX_METADATA[21]),
        "fade-in" => Some(&PREFIX_METADATA[22]),
        "fade-out" => Some(&PREFIX_METADATA[23]),
        "gap" => Some(&PREFIX_METADATA[24]),
        "gap-x" => Some(&PREFIX_METADATA[25]),
        "gap-y" => Some(&PREFIX_METADATA[26]),
        "grid-cols" => Some(&PREFIX_METADATA[27]),
        "grid-rows" => Some(&PREFIX_METADATA[28]),
        "h" => Some(&PREFIX_METADATA[29]),
        "height" => Some(&PREFIX_METADATA[30]),
        "inset" => Some(&PREFIX_METADATA[31]),
        "inset-x" => Some(&PREFIX_METADATA[32]),
        "inset-y" => Some(&PREFIX_METADATA[33]),
        "leading" => Some(&PREFIX_METADATA[34]),
        "left" => Some(&PREFIX_METADATA[35]),
        "line-clamp" => Some(&PREFIX_METADATA[36]),
        "m" => Some(&PREFIX_METADATA[37]),
        "margin" => Some(&PREFIX_METADATA[38]),
        "max-h" => Some(&PREFIX_METADATA[39]),
        "max-w" => Some(&PREFIX_METADATA[40]),
        "mb" => Some(&PREFIX_METADATA[41]),
        "min-h" => Some(&PREFIX_METADATA[42]),
        "min-w" => Some(&PREFIX_METADATA[43]),
        "ml" => Some(&PREFIX_METADATA[44]),
        "mr" => Some(&PREFIX_METADATA[45]),
        "mt" => Some(&PREFIX_METADATA[46]),
        "mx" => Some(&PREFIX_METADATA[47]),
        "my" => Some(&PREFIX_METADATA[48]),
        "opacity" => Some(&PREFIX_METADATA[49]),
        "outline" => Some(&PREFIX_METADATA[50]),
        "p" => Some(&PREFIX_METADATA[51]),
        "padding" => Some(&PREFIX_METADATA[52]),
        "pb" => Some(&PREFIX_METADATA[53]),
        "pl" => Some(&PREFIX_METADATA[54]),
        "pr" => Some(&PREFIX_METADATA[55]),
        "pt" => Some(&PREFIX_METADATA[56]),
        "px" => Some(&PREFIX_METADATA[57]),
        "py" => Some(&PREFIX_METADATA[58]),
        "right" => Some(&PREFIX_METADATA[59]),
        "rotate" => Some(&PREFIX_METADATA[60]),
        "row-end" => Some(&PREFIX_METADATA[61]),
        "row-span" => Some(&PREFIX_METADATA[62]),
        "row-start" => Some(&PREFIX_METADATA[63]),
        "scale" => Some(&PREFIX_METADATA[64]),
        "scale-x" => Some(&PREFIX_METADATA[65]),
        "scale-y" => Some(&PREFIX_METADATA[66]),
        "size" => Some(&PREFIX_METADATA[67]),
        "skew-x" => Some(&PREFIX_METADATA[68]),
        "skew-y" => Some(&PREFIX_METADATA[69]),
        "slide-in-from-bottom" => Some(&PREFIX_METADATA[70]),
        "slide-in-from-left" => Some(&PREFIX_METADATA[71]),
        "slide-in-from-right" => Some(&PREFIX_METADATA[72]),
        "slide-in-from-top" => Some(&PREFIX_METADATA[73]),
        "top" => Some(&PREFIX_METADATA[74]),
        "translate-x" => Some(&PREFIX_METADATA[75]),
        "translate-y" => Some(&PREFIX_METADATA[76]),
        "underline-offset" => Some(&PREFIX_METADATA[77]),
        "w" => Some(&PREFIX_METADATA[78]),
        "width" => Some(&PREFIX_METADATA[79]),
        "z" => Some(&PREFIX_METADATA[80]),
        "zoom-in" => Some(&PREFIX_METADATA[81]),
        "zoom-out" => Some(&PREFIX_METADATA[82]),
        _ => None,
    }
}
