// 自动生成的 Utility 前缀与单位元数据表（供 silex_macros 使用）
// 由 silex_codegen 自动生成，切勿手写修改！

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnitKind {
    RemScale,
    Pixel,
    Percentage,
    Degree,
    Milliseconds,
    Unitless,
    GridRepeat,
    GridSpan,
}

pub struct PrefixMeta {
    pub target_props: &'static [&'static str],
    pub unit_kind: UnitKind,
    pub value_wrapper: Option<&'static str>,
    /// 命中该前缀时附带产出的固定声明（`outline-*` 的 `outline-style: solid`）
    pub companions: &'static [(&'static str, &'static str)],
}

#[rustfmt::skip]
pub static PREFIX_METADATA: &[PrefixMeta] = &[
    PrefixMeta { target_props: &["animation"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["aspect-ratio"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-auto-columns"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-auto-rows"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Pixel, value_wrapper: Some("blur({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("brightness({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("contrast({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("grayscale({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Degree, value_wrapper: Some("hue-rotate({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("invert({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("opacity({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("saturate({})"), companions: &[] },
    PrefixMeta { target_props: &["backdrop-filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("sepia({})"), companions: &[] },
    PrefixMeta { target_props: &["flex-basis"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Pixel, value_wrapper: Some("blur({})"), companions: &[] },
    PrefixMeta { target_props: &["border-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-bottom-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-block-end-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-block-start-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-inline-end-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-left-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-right-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-inline-start-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-top-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-left-width", "border-right-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["border-top-width", "border-bottom-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["bottom"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("brightness({})"), companions: &[] },
    PrefixMeta { target_props: &["grid-column"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-column-end"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-column"], unit_kind: UnitKind::GridSpan, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-column-start"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["columns"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["container-name"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["container-name"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["content"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("contrast({})"), companions: &[] },
    PrefixMeta { target_props: &["cursor"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["transition-delay"], unit_kind: UnitKind::Milliseconds, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Unitless, value_wrapper: Some("drop-shadow({})"), companions: &[] },
    PrefixMeta { target_props: &["transition-duration"], unit_kind: UnitKind::Milliseconds, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["transition-timing-function"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-opacity"], unit_kind: UnitKind::Percentage, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-opacity"], unit_kind: UnitKind::Percentage, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["gap"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["column-gap"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["row-gap"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("grayscale({})"), companions: &[] },
    PrefixMeta { target_props: &["grid-template-columns"], unit_kind: UnitKind::GridRepeat, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-template-rows"], unit_kind: UnitKind::GridRepeat, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["flex-grow"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["height"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["height"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Degree, value_wrapper: Some("hue-rotate({})"), companions: &[] },
    PrefixMeta { target_props: &["top", "right", "bottom", "left"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["left", "right"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["top", "bottom"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("invert({})"), companions: &[] },
    PrefixMeta { target_props: &["line-height"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["left"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["-webkit-line-clamp"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["max-height"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["max-width"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin-bottom"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["min-height"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["min-width"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin-left"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin-right"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin-top"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin-left", "margin-right"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["margin-top", "margin-bottom"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["object-fit"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["opacity"], unit_kind: UnitKind::Percentage, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["order"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["transform-origin"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["outline-width"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[("outline-style", "solid")] },
    PrefixMeta { target_props: &["padding"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding-bottom"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding-left"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding-right"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding-top"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding-left", "padding-right"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["padding-top", "padding-bottom"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["right"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Degree, value_wrapper: Some("rotate({})"), companions: &[] },
    PrefixMeta { target_props: &["border-radius"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-row"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-row-end"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-row"], unit_kind: UnitKind::GridSpan, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["grid-row-start"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("saturate({})"), companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Percentage, value_wrapper: Some("scale({})"), companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Percentage, value_wrapper: Some("scaleX({})"), companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Percentage, value_wrapper: Some("scaleY({})"), companions: &[] },
    PrefixMeta { target_props: &["filter"], unit_kind: UnitKind::Percentage, value_wrapper: Some("sepia({})"), companions: &[] },
    PrefixMeta { target_props: &["box-shadow"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["flex-shrink"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["width", "height"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Degree, value_wrapper: Some("skewX({})"), companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::Degree, value_wrapper: Some("skewY({})"), companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-translate-y"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-translate-x"], unit_kind: UnitKind::RemScale, value_wrapper: Some("-{}"), companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-translate-x"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-translate-y"], unit_kind: UnitKind::RemScale, value_wrapper: Some("-{}"), companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-translate-y"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-translate-x"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-translate-x"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-translate-y"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-rotate"], unit_kind: UnitKind::Degree, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-rotate"], unit_kind: UnitKind::Degree, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["top"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["letter-spacing"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::RemScale, value_wrapper: Some("translateX({})"), companions: &[] },
    PrefixMeta { target_props: &["transform"], unit_kind: UnitKind::RemScale, value_wrapper: Some("translateY({})"), companions: &[] },
    PrefixMeta { target_props: &["text-underline-offset"], unit_kind: UnitKind::Pixel, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["width"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["width"], unit_kind: UnitKind::RemScale, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["z-index"], unit_kind: UnitKind::Unitless, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-enter-scale"], unit_kind: UnitKind::Percentage, value_wrapper: None, companions: &[] },
    PrefixMeta { target_props: &["--tw-exit-scale"], unit_kind: UnitKind::Percentage, value_wrapper: None, companions: &[] },
];

/// 根据 Utility 前缀静态匹配对应的元数据配置
pub fn lookup_prefix_meta(prefix: &str) -> Option<&'static PrefixMeta> {
    match prefix {
        "animate" => Some(&PREFIX_METADATA[0]),
        "aspect" => Some(&PREFIX_METADATA[1]),
        "auto-cols" => Some(&PREFIX_METADATA[2]),
        "auto-rows" => Some(&PREFIX_METADATA[3]),
        "backdrop-blur" => Some(&PREFIX_METADATA[4]),
        "backdrop-brightness" => Some(&PREFIX_METADATA[5]),
        "backdrop-contrast" => Some(&PREFIX_METADATA[6]),
        "backdrop-grayscale" => Some(&PREFIX_METADATA[7]),
        "backdrop-hue-rotate" => Some(&PREFIX_METADATA[8]),
        "backdrop-invert" => Some(&PREFIX_METADATA[9]),
        "backdrop-opacity" => Some(&PREFIX_METADATA[10]),
        "backdrop-saturate" => Some(&PREFIX_METADATA[11]),
        "backdrop-sepia" => Some(&PREFIX_METADATA[12]),
        "basis" => Some(&PREFIX_METADATA[13]),
        "blur" => Some(&PREFIX_METADATA[14]),
        "border" => Some(&PREFIX_METADATA[15]),
        "border-b" => Some(&PREFIX_METADATA[16]),
        "border-be" => Some(&PREFIX_METADATA[17]),
        "border-bs" => Some(&PREFIX_METADATA[18]),
        "border-e" => Some(&PREFIX_METADATA[19]),
        "border-l" => Some(&PREFIX_METADATA[20]),
        "border-r" => Some(&PREFIX_METADATA[21]),
        "border-s" => Some(&PREFIX_METADATA[22]),
        "border-t" => Some(&PREFIX_METADATA[23]),
        "border-x" => Some(&PREFIX_METADATA[24]),
        "border-y" => Some(&PREFIX_METADATA[25]),
        "bottom" => Some(&PREFIX_METADATA[26]),
        "brightness" => Some(&PREFIX_METADATA[27]),
        "col" => Some(&PREFIX_METADATA[28]),
        "col-end" => Some(&PREFIX_METADATA[29]),
        "col-span" => Some(&PREFIX_METADATA[30]),
        "col-start" => Some(&PREFIX_METADATA[31]),
        "columns" => Some(&PREFIX_METADATA[32]),
        "container" => Some(&PREFIX_METADATA[33]),
        "container-name" => Some(&PREFIX_METADATA[34]),
        "content" => Some(&PREFIX_METADATA[35]),
        "contrast" => Some(&PREFIX_METADATA[36]),
        "cursor" => Some(&PREFIX_METADATA[37]),
        "delay" => Some(&PREFIX_METADATA[38]),
        "drop-shadow" => Some(&PREFIX_METADATA[39]),
        "duration" => Some(&PREFIX_METADATA[40]),
        "ease" => Some(&PREFIX_METADATA[41]),
        "fade-in" => Some(&PREFIX_METADATA[42]),
        "fade-out" => Some(&PREFIX_METADATA[43]),
        "gap" => Some(&PREFIX_METADATA[44]),
        "gap-x" => Some(&PREFIX_METADATA[45]),
        "gap-y" => Some(&PREFIX_METADATA[46]),
        "grayscale" => Some(&PREFIX_METADATA[47]),
        "grid-cols" => Some(&PREFIX_METADATA[48]),
        "grid-rows" => Some(&PREFIX_METADATA[49]),
        "grow" => Some(&PREFIX_METADATA[50]),
        "h" => Some(&PREFIX_METADATA[51]),
        "height" => Some(&PREFIX_METADATA[52]),
        "hue-rotate" => Some(&PREFIX_METADATA[53]),
        "inset" => Some(&PREFIX_METADATA[54]),
        "inset-x" => Some(&PREFIX_METADATA[55]),
        "inset-y" => Some(&PREFIX_METADATA[56]),
        "invert" => Some(&PREFIX_METADATA[57]),
        "leading" => Some(&PREFIX_METADATA[58]),
        "left" => Some(&PREFIX_METADATA[59]),
        "line-clamp" => Some(&PREFIX_METADATA[60]),
        "m" => Some(&PREFIX_METADATA[61]),
        "margin" => Some(&PREFIX_METADATA[62]),
        "max-h" => Some(&PREFIX_METADATA[63]),
        "max-w" => Some(&PREFIX_METADATA[64]),
        "mb" => Some(&PREFIX_METADATA[65]),
        "min-h" => Some(&PREFIX_METADATA[66]),
        "min-w" => Some(&PREFIX_METADATA[67]),
        "ml" => Some(&PREFIX_METADATA[68]),
        "mr" => Some(&PREFIX_METADATA[69]),
        "mt" => Some(&PREFIX_METADATA[70]),
        "mx" => Some(&PREFIX_METADATA[71]),
        "my" => Some(&PREFIX_METADATA[72]),
        "object" => Some(&PREFIX_METADATA[73]),
        "opacity" => Some(&PREFIX_METADATA[74]),
        "order" => Some(&PREFIX_METADATA[75]),
        "origin" => Some(&PREFIX_METADATA[76]),
        "outline" => Some(&PREFIX_METADATA[77]),
        "p" => Some(&PREFIX_METADATA[78]),
        "padding" => Some(&PREFIX_METADATA[79]),
        "pb" => Some(&PREFIX_METADATA[80]),
        "pl" => Some(&PREFIX_METADATA[81]),
        "pr" => Some(&PREFIX_METADATA[82]),
        "pt" => Some(&PREFIX_METADATA[83]),
        "px" => Some(&PREFIX_METADATA[84]),
        "py" => Some(&PREFIX_METADATA[85]),
        "right" => Some(&PREFIX_METADATA[86]),
        "rotate" => Some(&PREFIX_METADATA[87]),
        "rounded" => Some(&PREFIX_METADATA[88]),
        "row" => Some(&PREFIX_METADATA[89]),
        "row-end" => Some(&PREFIX_METADATA[90]),
        "row-span" => Some(&PREFIX_METADATA[91]),
        "row-start" => Some(&PREFIX_METADATA[92]),
        "saturate" => Some(&PREFIX_METADATA[93]),
        "scale" => Some(&PREFIX_METADATA[94]),
        "scale-x" => Some(&PREFIX_METADATA[95]),
        "scale-y" => Some(&PREFIX_METADATA[96]),
        "sepia" => Some(&PREFIX_METADATA[97]),
        "shadow" => Some(&PREFIX_METADATA[98]),
        "shrink" => Some(&PREFIX_METADATA[99]),
        "size" => Some(&PREFIX_METADATA[100]),
        "skew-x" => Some(&PREFIX_METADATA[101]),
        "skew-y" => Some(&PREFIX_METADATA[102]),
        "slide-in-from-bottom" => Some(&PREFIX_METADATA[103]),
        "slide-in-from-left" => Some(&PREFIX_METADATA[104]),
        "slide-in-from-right" => Some(&PREFIX_METADATA[105]),
        "slide-in-from-top" => Some(&PREFIX_METADATA[106]),
        "slide-out-to-bottom" => Some(&PREFIX_METADATA[107]),
        "slide-out-to-left" => Some(&PREFIX_METADATA[108]),
        "slide-out-to-right" => Some(&PREFIX_METADATA[109]),
        "slide-out-to-top" => Some(&PREFIX_METADATA[110]),
        "spin-in" => Some(&PREFIX_METADATA[111]),
        "spin-out" => Some(&PREFIX_METADATA[112]),
        "top" => Some(&PREFIX_METADATA[113]),
        "tracking" => Some(&PREFIX_METADATA[114]),
        "translate-x" => Some(&PREFIX_METADATA[115]),
        "translate-y" => Some(&PREFIX_METADATA[116]),
        "underline-offset" => Some(&PREFIX_METADATA[117]),
        "w" => Some(&PREFIX_METADATA[118]),
        "width" => Some(&PREFIX_METADATA[119]),
        "z" => Some(&PREFIX_METADATA[120]),
        "zoom-in" => Some(&PREFIX_METADATA[121]),
        "zoom-out" => Some(&PREFIX_METADATA[122]),
        _ => None,
    }
}
