// 自动生成的 CSS / Tailwind 简写属性到原子子属性的静态对照表（供 silex_macros 使用）
// 由 silex_codegen 自动提取，切勿手动修改！

#[rustfmt::skip]
pub static SHORTHAND_SUBPROPERTIES: &[(&str, &[&str])] = &[
    ("animation", &["animation-delay", "animation-direction", "animation-duration", "animation-fill-mode", "animation-iteration-count", "animation-name", "animation-play-state", "animation-timeline", "animation-timing-function"]),
    ("animation-range", &["animation-range-end", "animation-range-start"]),
    ("background", &["background-attachment", "background-clip", "background-color", "background-image", "background-origin", "background-position-x", "background-position-y", "background-repeat", "background-size"]),
    ("background-position", &["background-position-x", "background-position-y"]),
    ("border", &["border-bottom-color", "border-bottom-style", "border-bottom-width", "border-left-color", "border-left-style", "border-left-width", "border-right-color", "border-right-style", "border-right-width", "border-top-color", "border-top-style", "border-top-width"]),
    ("border-block", &["border-block-color", "border-block-style", "border-block-width"]),
    ("border-block-end", &["border-top-color", "border-top-style", "border-top-width"]),
    ("border-block-start", &["border-block-start-color", "border-bottom-style", "border-bottom-width", "border-left-style", "border-left-width", "border-right-style", "border-right-width", "border-top-style", "border-top-width"]),
    ("border-bottom", &["border-bottom-color", "border-bottom-style", "border-bottom-width"]),
    ("border-color", &["border-bottom-color", "border-left-color", "border-right-color", "border-top-color"]),
    ("border-image", &["border-image-outset", "border-image-repeat", "border-image-slice", "border-image-source", "border-image-width"]),
    ("border-inline", &["border-inline-color", "border-inline-style", "border-inline-width"]),
    ("border-inline-end", &["border-bottom-style", "border-bottom-width", "border-inline-end-color", "border-left-style", "border-left-width", "border-right-style", "border-right-width", "border-top-style", "border-top-width"]),
    ("border-inline-start", &["border-bottom-style", "border-bottom-width", "border-inline-start-color", "border-left-style", "border-left-width", "border-right-style", "border-right-width", "border-top-style", "border-top-width"]),
    ("border-left", &["border-left-color", "border-left-style", "border-left-width"]),
    ("border-radius", &["border-bottom-left-radius", "border-bottom-right-radius", "border-top-left-radius", "border-top-right-radius"]),
    ("border-right", &["border-right-color", "border-right-style", "border-right-width"]),
    ("border-style", &["border-bottom-style", "border-left-style", "border-right-style", "border-top-style"]),
    ("border-top", &["border-top-color", "border-top-style", "border-top-width"]),
    ("border-width", &["border-bottom-width", "border-left-width", "border-right-width", "border-top-width"]),
    ("border-x", &["border-left-width", "border-right-width"]),
    ("border-x-color", &["border-left-color", "border-right-color"]),
    ("border-x-style", &["border-left-style", "border-right-style"]),
    ("border-x-width", &["border-left-width", "border-right-width"]),
    ("border-y", &["border-bottom-width", "border-top-width"]),
    ("border-y-color", &["border-bottom-color", "border-top-color"]),
    ("border-y-style", &["border-bottom-style", "border-top-style"]),
    ("border-y-width", &["border-bottom-width", "border-top-width"]),
    ("caret", &["caret-animation", "caret-color", "caret-shape"]),
    ("column-rule", &["column-rule-color", "column-rule-style", "column-rule-width"]),
    ("columns", &["column-count", "column-height", "column-width"]),
    ("contain-intrinsic-size", &["contain-intrinsic-height", "contain-intrinsic-width"]),
    ("container", &["container-name", "container-type"]),
    ("corner-block-end-shape", &["corner-end-end-shape", "corner-end-start-shape"]),
    ("corner-block-start-shape", &["corner-start-end-shape", "corner-start-start-shape"]),
    ("corner-bottom-shape", &["corner-bottom-left-shape", "corner-bottom-right-shape"]),
    ("corner-inline-end-shape", &["corner-end-end-shape", "corner-start-end-shape"]),
    ("corner-inline-start-shape", &["corner-start-end-shape", "corner-start-start-shape"]),
    ("corner-left-shape", &["corner-bottom-left-shape", "corner-top-left-shape"]),
    ("corner-right-shape", &["corner-bottom-right-shape", "corner-top-right-shape"]),
    ("corner-shape", &["corner-bottom-left-shape", "corner-bottom-right-shape", "corner-top-left-shape", "corner-top-right-shape"]),
    ("corner-top-shape", &["corner-top-left-shape", "corner-top-right-shape"]),
    ("flex", &["flex-basis", "flex-grow", "flex-shrink"]),
    ("flex-flow", &["flex-direction", "flex-wrap"]),
    ("font", &["font-family", "font-size", "font-stretch", "font-style", "font-variant", "font-weight", "line-height"]),
    ("gap", &["column-gap", "row-gap"]),
    ("grid", &["column-gap", "grid-auto-columns", "grid-auto-flow", "grid-auto-rows", "grid-column-gap", "grid-row-gap", "grid-template-areas", "grid-template-columns", "grid-template-rows", "row-gap"]),
    ("grid-area", &["grid-column-end", "grid-column-start", "grid-row-end", "grid-row-start"]),
    ("grid-column", &["grid-column-end", "grid-column-start"]),
    ("grid-gap", &["grid-column-gap", "grid-row-gap"]),
    ("grid-row", &["grid-row-end", "grid-row-start"]),
    ("grid-template", &["grid-template-areas", "grid-template-columns", "grid-template-rows"]),
    ("inset", &["bottom", "left", "right", "top"]),
    ("inset-block", &["inset-block-end", "inset-block-start"]),
    ("inset-inline", &["inset-inline-end", "inset-inline-start"]),
    ("inset-x", &["left", "right"]),
    ("inset-y", &["bottom", "top"]),
    ("interest-delay", &["interest-delay-end", "interest-delay-start"]),
    ("list-style", &["list-style-image", "list-style-position", "list-style-type"]),
    ("margin", &["margin-bottom", "margin-left", "margin-right", "margin-top"]),
    ("margin-block", &["margin-bottom", "margin-top"]),
    ("margin-inline", &["margin-left", "margin-right"]),
    ("mask", &["mask-clip", "mask-composite", "mask-image", "mask-mode", "mask-origin", "mask-position", "mask-repeat", "mask-size"]),
    ("mask-border", &["mask-border-mode", "mask-border-outset", "mask-border-repeat", "mask-border-slice", "mask-border-source", "mask-border-width"]),
    ("offset", &["offset-anchor", "offset-distance", "offset-path", "offset-position", "offset-rotate"]),
    ("outline", &["outline-color", "outline-style", "outline-width"]),
    ("overflow", &["overflow-x", "overflow-y"]),
    ("overscroll-behavior", &["overscroll-behavior-x", "overscroll-behavior-y"]),
    ("padding", &["padding-bottom", "padding-left", "padding-right", "padding-top"]),
    ("padding-block", &["padding-bottom", "padding-top"]),
    ("padding-inline", &["padding-left", "padding-right"]),
    ("place-content", &["align-content", "justify-content"]),
    ("place-items", &["align-items", "justify-items"]),
    ("place-self", &["align-self", "justify-self"]),
    ("position-try", &["position-try-fallbacks", "position-try-order"]),
    ("scroll-margin", &["scroll-margin-bottom", "scroll-margin-left", "scroll-margin-right", "scroll-margin-top"]),
    ("scroll-margin-block", &["scroll-margin-bottom", "scroll-margin-top"]),
    ("scroll-margin-inline", &["scroll-margin-left", "scroll-margin-right"]),
    ("scroll-padding", &["scroll-padding-bottom", "scroll-padding-left", "scroll-padding-right", "scroll-padding-top"]),
    ("scroll-padding-block", &["scroll-padding-bottom", "scroll-padding-top"]),
    ("scroll-padding-inline", &["scroll-padding-left", "scroll-padding-right"]),
    ("scroll-timeline", &["scroll-timeline-axis", "scroll-timeline-name"]),
    ("text-decoration", &["text-decoration-color", "text-decoration-line", "text-decoration-style", "text-decoration-thickness"]),
    ("text-emphasis", &["text-emphasis-color", "text-emphasis-style"]),
    ("text-wrap", &["text-wrap-mode", "text-wrap-style"]),
    ("timeline-trigger", &["timeline-trigger-exit-range-end", "timeline-trigger-exit-range-start", "timeline-trigger-name", "timeline-trigger-range-end", "timeline-trigger-range-start", "timeline-trigger-source"]),
    ("timeline-trigger-exit-range", &["timeline-trigger-exit-range-end", "timeline-trigger-exit-range-start"]),
    ("timeline-trigger-range", &["timeline-trigger-range-end", "timeline-trigger-range-start"]),
    ("transition", &["transition-behavior", "transition-delay", "transition-duration", "transition-property", "transition-timing-function"]),
    ("view-timeline", &["view-timeline-axis", "view-timeline-name"]),
];

/// 获取指定 CSS / Tailwind 简写属性拆解后的原子子属性集合
pub fn get_atomic_subproperties(prop: &str) -> Option<&'static [&'static str]> {
    let idx = SHORTHAND_SUBPROPERTIES
        .binary_search_by_key(&prop, |&(k, _)| k)
        .ok()?;
    Some(SHORTHAND_SUBPROPERTIES[idx].1)
}
