[package]
name = "silex_core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lints]
workspace = true

[features]
default = []
test-support = ["silex_reactivity/test-support"]
error-persistence = []
error-i18n = []
error-i18n-persistence = ["error-i18n", "error-persistence"]
error-router = []
error-net = []
error-intl = []

[dependencies]
silex_reactivity.workspace = true
silex_rx.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
futures-util.workspace = true

[dev-dependencies]
gloo-timers.workspace = true
trybuild = "1.0"
wasm-bindgen-test.workspace = true
