[package]
name = "silex_dom"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[lints]
workspace = true

[features]
default = ["browser"]
browser = ["dep:js-sys", "dep:wasm-bindgen", "dep:web-sys"]
ssr = []

[dependencies]
silex_vtable.workspace = true
silex_core.workspace = true
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true, features = [
    "Node",
    "NodeList",
    "Document",
    "Text",
    "Window",
    "Element",
    "DomRect",
    "Comment",
    "DocumentFragment",
    "MouseEvent",
    "InputEvent",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "HtmlButtonElement",
    "HtmlOptionElement",
    "HtmlOptGroupElement",
    "HtmlAnchorElement",
    "HtmlCanvasElement",
    "HtmlFormElement",
    "HtmlImageElement",
    "HtmlAudioElement",
    "HtmlVideoElement",
    "HtmlDialogElement",
    "HtmlDetailsElement",
    "HtmlIFrameElement",
    "KeyboardEvent",
    "DomTokenList",
    "SvgElement",
    "CssStyleDeclaration",
    "SubmitEvent",
    "FocusEvent",
    "ErrorEvent",
    "PointerEvent",
    "DragEvent",
    "TouchEvent",
    "WheelEvent",
    "AnimationEvent",
    "TransitionEvent",
    "CompositionEvent",
    "Location",
    "PromiseRejectionEvent",
    "AddEventListenerOptions",
    "console"
] }
js-sys = { workspace = true, optional = true }

[dev-dependencies]
wasm-bindgen-futures.workspace = true
trybuild = "1.0"
wasm-bindgen-test.workspace = true
