/// 自动生成的 CSS 属性注册表
///
/// 每项的第四栏是该属性允许的值类型能力集合，由 MDN 值定义语法解析得出
/// （见 `silex_codegen::css::syntax`），而不是过去那 8 个粗粒度分组。
#[macro_export]
macro_rules! for_all_properties {
    ($callback:ident) => {
        $callback! {
            (webkit_line_clamp, "-webkit-line-clamp", WebkitLineClamp, [Int]),
            (webkit_text_fill_color, "-webkit-text-fill-color", WebkitTextFillColor, [Color]),
            (webkit_text_stroke, "-webkit-text-stroke", WebkitTextStroke, [Color LenCalc Length Str]),
            (webkit_text_stroke_color, "-webkit-text-stroke-color", WebkitTextStrokeColor, [Color]),
            (webkit_text_stroke_width, "-webkit-text-stroke-width", WebkitTextStrokeWidth, [LenCalc Length]),
            (accent_color, "accent-color", AccentColor, [Color]),
            (align_content, "align-content", AlignContent, [Str]),
            (align_items, "align-items", AlignItems, [Str]),
            (align_self, "align-self", AlignSelf, [Str]),
            (alignment_baseline, "alignment-baseline", AlignmentBaseline, []),
            (all, "all", All, []),
            (animation, "animation", Animation, [Num Str]),
            (animation_composition, "animation-composition", AnimationComposition, [Str]),
            (animation_delay, "animation-delay", AnimationDelay, [Str]),
            (animation_direction, "animation-direction", AnimationDirection, [Str]),
            (animation_duration, "animation-duration", AnimationDuration, [Str]),
            (animation_fill_mode, "animation-fill-mode", AnimationFillMode, [Str]),
            (animation_iteration_count, "animation-iteration-count", AnimationIterationCount, [Num Str]),
            (animation_name, "animation-name", AnimationName, [Str]),
            (animation_play_state, "animation-play-state", AnimationPlayState, [Str]),
            (animation_timing_function, "animation-timing-function", AnimationTimingFunction, [Str]),
            (animation_trigger, "animation-trigger", AnimationTrigger, [Str]),
            (appearance, "appearance", Appearance, []),
            (aspect_ratio, "aspect-ratio", AspectRatio, [Num Str]),
            (backdrop_filter, "backdrop-filter", BackdropFilter, [Str Url]),
            (backface_visibility, "backface-visibility", BackfaceVisibility, []),
            (background, "background", Background, [Color LenCalc Length Percent Str Url]),
            (background_attachment, "background-attachment", BackgroundAttachment, [Str]),
            (background_blend_mode, "background-blend-mode", BackgroundBlendMode, [Str]),
            (background_clip, "background-clip", BackgroundClip, [Str]),
            (background_color, "background-color", BackgroundColor, [Color]),
            (background_image, "background-image", BackgroundImage, [Str Url]),
            (background_origin, "background-origin", BackgroundOrigin, [Str]),
            (background_position, "background-position", BackgroundPosition, [LenCalc Length Percent Str]),
            (background_position_x, "background-position-x", BackgroundPositionX, [LenCalc Length Percent Str]),
            (background_position_y, "background-position-y", BackgroundPositionY, [LenCalc Length Percent Str]),
            (background_repeat, "background-repeat", BackgroundRepeat, [Str]),
            (background_size, "background-size", BackgroundSize, [LenCalc Length Percent Str]),
            (baseline_shift, "baseline-shift", BaselineShift, [LenCalc Length Percent]),
            (baseline_source, "baseline-source", BaselineSource, []),
            (block_size, "block-size", BlockSize, [LenCalc Length Percent]),
            (border, "border", Border, [Color LenCalc Length Str]),
            (border_block, "border-block", BorderBlock, [Color LenCalc Length Str]),
            (border_block_color, "border-block-color", BorderBlockColor, [Color Str]),
            (border_block_end, "border-block-end", BorderBlockEnd, [Color LenCalc Length Str]),
            (border_block_end_color, "border-block-end-color", BorderBlockEndColor, [Color]),
            (border_block_end_style, "border-block-end-style", BorderBlockEndStyle, []),
            (border_block_end_width, "border-block-end-width", BorderBlockEndWidth, [LenCalc Length]),
            (border_block_start, "border-block-start", BorderBlockStart, [Color LenCalc Length Str]),
            (border_block_start_color, "border-block-start-color", BorderBlockStartColor, [Color]),
            (border_block_start_style, "border-block-start-style", BorderBlockStartStyle, []),
            (border_block_start_width, "border-block-start-width", BorderBlockStartWidth, [LenCalc Length]),
            (border_block_style, "border-block-style", BorderBlockStyle, [Str]),
            (border_block_width, "border-block-width", BorderBlockWidth, [LenCalc Length Str]),
            (border_bottom, "border-bottom", BorderBottom, [Color LenCalc Length Str]),
            (border_bottom_color, "border-bottom-color", BorderBottomColor, [Color]),
            (border_bottom_left_radius, "border-bottom-left-radius", BorderBottomLeftRadius, [LenCalc Length Percent Str]),
            (border_bottom_right_radius, "border-bottom-right-radius", BorderBottomRightRadius, [LenCalc Length Percent Str]),
            (border_bottom_style, "border-bottom-style", BorderBottomStyle, []),
            (border_bottom_width, "border-bottom-width", BorderBottomWidth, [LenCalc Length]),
            (border_collapse, "border-collapse", BorderCollapse, []),
            (border_color, "border-color", BorderColor, [Color Str]),
            (border_end_end_radius, "border-end-end-radius", BorderEndEndRadius, [LenCalc Length Percent Str]),
            (border_end_start_radius, "border-end-start-radius", BorderEndStartRadius, [LenCalc Length Percent Str]),
            (border_image, "border-image", BorderImage, [LenCalc Num Percent Str Url]),
            (border_image_outset, "border-image-outset", BorderImageOutset, [LenCalc Length Num Str]),
            (border_image_repeat, "border-image-repeat", BorderImageRepeat, [Str]),
            (border_image_slice, "border-image-slice", BorderImageSlice, [LenCalc Num Percent Str]),
            (border_image_source, "border-image-source", BorderImageSource, [Url]),
            (border_image_width, "border-image-width", BorderImageWidth, [LenCalc Length Num Percent Str]),
            (border_inline, "border-inline", BorderInline, [Color LenCalc Length Str]),
            (border_inline_color, "border-inline-color", BorderInlineColor, [Color Str]),
            (border_inline_end, "border-inline-end", BorderInlineEnd, [Color LenCalc Length Str]),
            (border_inline_end_color, "border-inline-end-color", BorderInlineEndColor, [Color]),
            (border_inline_end_style, "border-inline-end-style", BorderInlineEndStyle, []),
            (border_inline_end_width, "border-inline-end-width", BorderInlineEndWidth, [LenCalc Length]),
            (border_inline_start, "border-inline-start", BorderInlineStart, [Color LenCalc Length Str]),
            (border_inline_start_color, "border-inline-start-color", BorderInlineStartColor, [Color]),
            (border_inline_start_style, "border-inline-start-style", BorderInlineStartStyle, []),
            (border_inline_start_width, "border-inline-start-width", BorderInlineStartWidth, [LenCalc Length]),
            (border_inline_style, "border-inline-style", BorderInlineStyle, [Str]),
            (border_inline_width, "border-inline-width", BorderInlineWidth, [LenCalc Length Str]),
            (border_left, "border-left", BorderLeft, [Color LenCalc Length Str]),
            (border_left_color, "border-left-color", BorderLeftColor, [Color]),
            (border_left_style, "border-left-style", BorderLeftStyle, []),
            (border_left_width, "border-left-width", BorderLeftWidth, [LenCalc Length]),
            (border_radius, "border-radius", BorderRadius, [LenCalc Length Percent Str]),
            (border_right, "border-right", BorderRight, [Color LenCalc Length Str]),
            (border_right_color, "border-right-color", BorderRightColor, [Color]),
            (border_right_style, "border-right-style", BorderRightStyle, []),
            (border_right_width, "border-right-width", BorderRightWidth, [LenCalc Length]),
            (border_spacing, "border-spacing", BorderSpacing, [LenCalc Length Str]),
            (border_start_end_radius, "border-start-end-radius", BorderStartEndRadius, [LenCalc Length Percent Str]),
            (border_start_start_radius, "border-start-start-radius", BorderStartStartRadius, [LenCalc Length Percent Str]),
            (border_style, "border-style", BorderStyle, [Str]),
            (border_top, "border-top", BorderTop, [Color LenCalc Length Str]),
            (border_top_color, "border-top-color", BorderTopColor, [Color]),
            (border_top_left_radius, "border-top-left-radius", BorderTopLeftRadius, [LenCalc Length Percent Str]),
            (border_top_right_radius, "border-top-right-radius", BorderTopRightRadius, [LenCalc Length Percent Str]),
            (border_top_style, "border-top-style", BorderTopStyle, []),
            (border_top_width, "border-top-width", BorderTopWidth, [LenCalc Length]),
            (border_width, "border-width", BorderWidth, [LenCalc Length Str]),
            (bottom, "bottom", Bottom, [LenCalc Length Percent]),
            (box_decoration_break, "box-decoration-break", BoxDecorationBreak, []),
            (box_shadow, "box-shadow", BoxShadow, [Str]),
            (box_sizing, "box-sizing", BoxSizing, []),
            (break_after, "break-after", BreakAfter, []),
            (break_before, "break-before", BreakBefore, []),
            (break_inside, "break-inside", BreakInside, []),
            (caption_side, "caption-side", CaptionSide, []),
            (caret, "caret", Caret, [Color Str]),
            (caret_animation, "caret-animation", CaretAnimation, []),
            (caret_color, "caret-color", CaretColor, [Color]),
            (caret_shape, "caret-shape", CaretShape, []),
            (clear, "clear", Clear, []),
            (clip_path, "clip-path", ClipPath, [Str Url]),
            (clip_rule, "clip-rule", ClipRule, []),
            (color, "color", Color, [Color]),
            (color_interpolation_filters, "color-interpolation-filters", ColorInterpolationFilters, []),
            (color_scheme, "color-scheme", ColorScheme, [Str]),
            (column_count, "column-count", ColumnCount, [Int]),
            (column_fill, "column-fill", ColumnFill, []),
            (column_gap, "column-gap", ColumnGap, [LenCalc Length Percent]),
            (column_height, "column-height", ColumnHeight, [LenCalc Length]),
            (column_rule, "column-rule", ColumnRule, [Color LenCalc Length Str]),
            (column_rule_color, "column-rule-color", ColumnRuleColor, [Color]),
            (column_rule_style, "column-rule-style", ColumnRuleStyle, [Str]),
            (column_rule_width, "column-rule-width", ColumnRuleWidth, [LenCalc Length Str]),
            (column_span, "column-span", ColumnSpan, []),
            (column_width, "column-width", ColumnWidth, [LenCalc Length]),
            (column_wrap, "column-wrap", ColumnWrap, []),
            (columns, "columns", Columns, [Int LenCalc Length Str]),
            (contain, "contain", Contain, [Str]),
            (contain_intrinsic_block_size, "contain-intrinsic-block-size", ContainIntrinsicBlockSize, [LenCalc Length Str]),
            (contain_intrinsic_height, "contain-intrinsic-height", ContainIntrinsicHeight, [LenCalc Length Str]),
            (contain_intrinsic_inline_size, "contain-intrinsic-inline-size", ContainIntrinsicInlineSize, [LenCalc Length Str]),
            (contain_intrinsic_size, "contain-intrinsic-size", ContainIntrinsicSize, [LenCalc Length Str]),
            (contain_intrinsic_width, "contain-intrinsic-width", ContainIntrinsicWidth, [LenCalc Length Str]),
            (container, "container", Container, [Str]),
            (container_name, "container-name", ContainerName, [Str]),
            (container_type, "container-type", ContainerType, [Str]),
            (content, "content", Content, [Str Url]),
            (content_visibility, "content-visibility", ContentVisibility, []),
            (corner_block_end_shape, "corner-block-end-shape", CornerBlockEndShape, [Str]),
            (corner_block_start_shape, "corner-block-start-shape", CornerBlockStartShape, [Str]),
            (corner_bottom_left_shape, "corner-bottom-left-shape", CornerBottomLeftShape, []),
            (corner_bottom_right_shape, "corner-bottom-right-shape", CornerBottomRightShape, []),
            (corner_bottom_shape, "corner-bottom-shape", CornerBottomShape, [Str]),
            (corner_end_end_shape, "corner-end-end-shape", CornerEndEndShape, []),
            (corner_end_start_shape, "corner-end-start-shape", CornerEndStartShape, []),
            (corner_inline_end_shape, "corner-inline-end-shape", CornerInlineEndShape, [Str]),
            (corner_inline_start_shape, "corner-inline-start-shape", CornerInlineStartShape, [Str]),
            (corner_left_shape, "corner-left-shape", CornerLeftShape, [Str]),
            (corner_right_shape, "corner-right-shape", CornerRightShape, [Str]),
            (corner_shape, "corner-shape", CornerShape, [Str]),
            (corner_start_end_shape, "corner-start-end-shape", CornerStartEndShape, []),
            (corner_start_start_shape, "corner-start-start-shape", CornerStartStartShape, []),
            (corner_top_left_shape, "corner-top-left-shape", CornerTopLeftShape, []),
            (corner_top_right_shape, "corner-top-right-shape", CornerTopRightShape, []),
            (corner_top_shape, "corner-top-shape", CornerTopShape, [Str]),
            (counter_increment, "counter-increment", CounterIncrement, [Str]),
            (counter_reset, "counter-reset", CounterReset, [Str]),
            (counter_set, "counter-set", CounterSet, [Str]),
            (cursor, "cursor", Cursor, [Str]),
            (cx, "cx", Cx, [LenCalc Length Percent]),
            (cy, "cy", Cy, [LenCalc Length Percent]),
            (d, "d", D, []),
            (direction, "direction", Direction, []),
            (display, "display", Display, [Str]),
            (dominant_baseline, "dominant-baseline", DominantBaseline, []),
            (dynamic_range_limit, "dynamic-range-limit", DynamicRangeLimit, []),
            (empty_cells, "empty-cells", EmptyCells, []),
            (fill, "fill", Fill, [Color Str Url]),
            (fill_opacity, "fill-opacity", FillOpacity, [LenCalc Num Percent]),
            (fill_rule, "fill-rule", FillRule, []),
            (filter, "filter", Filter, [Str Url]),
            (flex, "flex", Flex, [LenCalc Length Num Percent Str]),
            (flex_basis, "flex-basis", FlexBasis, [LenCalc Length Percent]),
            (flex_direction, "flex-direction", FlexDirection, []),
            (flex_flow, "flex-flow", FlexFlow, [Str]),
            (flex_grow, "flex-grow", FlexGrow, [Num]),
            (flex_shrink, "flex-shrink", FlexShrink, [Num]),
            (flex_wrap, "flex-wrap", FlexWrap, []),
            (float, "float", Float, []),
            (flood_color, "flood-color", FloodColor, [Color]),
            (flood_opacity, "flood-opacity", FloodOpacity, [LenCalc Num Percent]),
            (font, "font", Font, [Str]),
            (font_family, "font-family", FontFamily, [Str]),
            (font_feature_settings, "font-feature-settings", FontFeatureSettings, [Str]),
            (font_kerning, "font-kerning", FontKerning, []),
            (font_language_override, "font-language-override", FontLanguageOverride, [Str]),
            (font_optical_sizing, "font-optical-sizing", FontOpticalSizing, []),
            (font_palette, "font-palette", FontPalette, [Str]),
            (font_size, "font-size", FontSize, [LenCalc Length Percent]),
            (font_size_adjust, "font-size-adjust", FontSizeAdjust, [Num Str]),
            (font_style, "font-style", FontStyle, [Str]),
            (font_synthesis, "font-synthesis", FontSynthesis, [Str]),
            (font_synthesis_small_caps, "font-synthesis-small-caps", FontSynthesisSmallCaps, []),
            (font_synthesis_style, "font-synthesis-style", FontSynthesisStyle, []),
            (font_synthesis_weight, "font-synthesis-weight", FontSynthesisWeight, []),
            (font_variant, "font-variant", FontVariant, [Str]),
            (font_variant_alternates, "font-variant-alternates", FontVariantAlternates, [Str]),
            (font_variant_caps, "font-variant-caps", FontVariantCaps, []),
            (font_variant_east_asian, "font-variant-east-asian", FontVariantEastAsian, [Str]),
            (font_variant_emoji, "font-variant-emoji", FontVariantEmoji, []),
            (font_variant_ligatures, "font-variant-ligatures", FontVariantLigatures, [Str]),
            (font_variant_numeric, "font-variant-numeric", FontVariantNumeric, [Str]),
            (font_variant_position, "font-variant-position", FontVariantPosition, []),
            (font_variation_settings, "font-variation-settings", FontVariationSettings, [Str]),
            (font_weight, "font-weight", FontWeight, [Num]),
            (forced_color_adjust, "forced-color-adjust", ForcedColorAdjust, []),
            (gap, "gap", Gap, [LenCalc Length Percent Str]),
            (grid, "grid", Grid, [Str]),
            (grid_area, "grid-area", GridArea, [Int Str]),
            (grid_auto_columns, "grid-auto-columns", GridAutoColumns, [LenCalc Length Percent Str]),
            (grid_auto_flow, "grid-auto-flow", GridAutoFlow, [Str]),
            (grid_auto_rows, "grid-auto-rows", GridAutoRows, [LenCalc Length Percent Str]),
            (grid_column, "grid-column", GridColumn, [Int Str]),
            (grid_column_end, "grid-column-end", GridColumnEnd, [Int Str]),
            (grid_column_start, "grid-column-start", GridColumnStart, [Int Str]),
            (grid_row, "grid-row", GridRow, [Int Str]),
            (grid_row_end, "grid-row-end", GridRowEnd, [Int Str]),
            (grid_row_start, "grid-row-start", GridRowStart, [Int Str]),
            (grid_template, "grid-template", GridTemplate, [Str]),
            (grid_template_areas, "grid-template-areas", GridTemplateAreas, [Str]),
            (grid_template_columns, "grid-template-columns", GridTemplateColumns, [LenCalc Length Percent Str]),
            (grid_template_rows, "grid-template-rows", GridTemplateRows, [LenCalc Length Percent Str]),
            (hanging_punctuation, "hanging-punctuation", HangingPunctuation, [Str]),
            (height, "height", Height, [LenCalc Length Percent]),
            (hyphenate_character, "hyphenate-character", HyphenateCharacter, [Str]),
            (hyphenate_limit_chars, "hyphenate-limit-chars", HyphenateLimitChars, [Int Str]),
            (hyphens, "hyphens", Hyphens, []),
            (image_orientation, "image-orientation", ImageOrientation, [Angle Str]),
            (image_rendering, "image-rendering", ImageRendering, []),
            (initial_letter, "initial-letter", InitialLetter, [Num Str]),
            (inline_size, "inline-size", InlineSize, [LenCalc Length Percent]),
            (inset, "inset", Inset, [LenCalc Length Percent Str]),
            (inset_block, "inset-block", InsetBlock, [LenCalc Length Percent Str]),
            (inset_block_end, "inset-block-end", InsetBlockEnd, [LenCalc Length Percent]),
            (inset_block_start, "inset-block-start", InsetBlockStart, [LenCalc Length Percent]),
            (inset_inline, "inset-inline", InsetInline, [LenCalc Length Percent Str]),
            (inset_inline_end, "inset-inline-end", InsetInlineEnd, [LenCalc Length Percent]),
            (inset_inline_start, "inset-inline-start", InsetInlineStart, [LenCalc Length Percent]),
            (interactivity, "interactivity", Interactivity, []),
            (interest_delay, "interest-delay", InterestDelay, [Str]),
            (interest_delay_end, "interest-delay-end", InterestDelayEnd, [Str]),
            (interest_delay_start, "interest-delay-start", InterestDelayStart, [Str]),
            (isolation, "isolation", Isolation, []),
            (justify_content, "justify-content", JustifyContent, [Str]),
            (justify_items, "justify-items", JustifyItems, [Str]),
            (justify_self, "justify-self", JustifySelf, [Str]),
            (left, "left", Left, [LenCalc Length Percent]),
            (letter_spacing, "letter-spacing", LetterSpacing, [LenCalc Length]),
            (lighting_color, "lighting-color", LightingColor, [Color]),
            (line_break, "line-break", LineBreak, []),
            (line_clamp, "line-clamp", LineClamp, [Int]),
            (line_height, "line-height", LineHeight, [LenCalc Length Num Percent]),
            (list_style, "list-style", ListStyle, [Str Url]),
            (list_style_image, "list-style-image", ListStyleImage, [Url]),
            (list_style_position, "list-style-position", ListStylePosition, []),
            (list_style_type, "list-style-type", ListStyleType, [Str]),
            (margin, "margin", Margin, [LenCalc Length Percent Str]),
            (margin_block, "margin-block", MarginBlock, [LenCalc Length Percent Str]),
            (margin_block_end, "margin-block-end", MarginBlockEnd, [LenCalc Length Percent]),
            (margin_block_start, "margin-block-start", MarginBlockStart, [LenCalc Length Percent]),
            (margin_bottom, "margin-bottom", MarginBottom, [LenCalc Length Percent]),
            (margin_inline, "margin-inline", MarginInline, [LenCalc Length Percent Str]),
            (margin_inline_end, "margin-inline-end", MarginInlineEnd, [LenCalc Length Percent]),
            (margin_inline_start, "margin-inline-start", MarginInlineStart, [LenCalc Length Percent]),
            (margin_left, "margin-left", MarginLeft, [LenCalc Length Percent]),
            (margin_right, "margin-right", MarginRight, [LenCalc Length Percent]),
            (margin_top, "margin-top", MarginTop, [LenCalc Length Percent]),
            (marker, "marker", Marker, [Url]),
            (marker_end, "marker-end", MarkerEnd, [Url]),
            (marker_mid, "marker-mid", MarkerMid, [Url]),
            (marker_start, "marker-start", MarkerStart, [Url]),
            (mask, "mask", Mask, [LenCalc Length Percent Str Url]),
            (mask_border, "mask-border", MaskBorder, [LenCalc Num Percent Str Url]),
            (mask_border_mode, "mask-border-mode", MaskBorderMode, []),
            (mask_border_outset, "mask-border-outset", MaskBorderOutset, [LenCalc Length Num Str]),
            (mask_border_repeat, "mask-border-repeat", MaskBorderRepeat, [Str]),
            (mask_border_slice, "mask-border-slice", MaskBorderSlice, [LenCalc Num Percent Str]),
            (mask_border_source, "mask-border-source", MaskBorderSource, [Url]),
            (mask_border_width, "mask-border-width", MaskBorderWidth, [LenCalc Length Num Percent Str]),
            (mask_clip, "mask-clip", MaskClip, [Str]),
            (mask_composite, "mask-composite", MaskComposite, [Str]),
            (mask_image, "mask-image", MaskImage, [Str Url]),
            (mask_mode, "mask-mode", MaskMode, [Str]),
            (mask_origin, "mask-origin", MaskOrigin, [Str]),
            (mask_position, "mask-position", MaskPosition, [LenCalc Length Percent Str]),
            (mask_repeat, "mask-repeat", MaskRepeat, [Str]),
            (mask_size, "mask-size", MaskSize, [LenCalc Length Percent Str]),
            (mask_type, "mask-type", MaskType, []),
            (math_depth, "math-depth", MathDepth, [Int]),
            (math_style, "math-style", MathStyle, []),
            (max_block_size, "max-block-size", MaxBlockSize, [LenCalc Length Percent]),
            (max_height, "max-height", MaxHeight, [LenCalc Length Percent]),
            (max_inline_size, "max-inline-size", MaxInlineSize, [LenCalc Length Percent]),
            (max_width, "max-width", MaxWidth, [LenCalc Length Percent]),
            (min_block_size, "min-block-size", MinBlockSize, [LenCalc Length Percent]),
            (min_height, "min-height", MinHeight, [LenCalc Length Percent]),
            (min_inline_size, "min-inline-size", MinInlineSize, [LenCalc Length Percent]),
            (min_width, "min-width", MinWidth, [LenCalc Length Percent]),
            (mix_blend_mode, "mix-blend-mode", MixBlendMode, []),
            (object_fit, "object-fit", ObjectFit, []),
            (object_position, "object-position", ObjectPosition, [LenCalc Length Percent Str]),
            (offset, "offset", Offset, [LenCalc Length Percent Str Url]),
            (offset_anchor, "offset-anchor", OffsetAnchor, [LenCalc Length Percent Str]),
            (offset_distance, "offset-distance", OffsetDistance, [LenCalc Length Percent]),
            (offset_path, "offset-path", OffsetPath, [Str Url]),
            (offset_position, "offset-position", OffsetPosition, [LenCalc Length Percent Str]),
            (offset_rotate, "offset-rotate", OffsetRotate, [Angle Str]),
            (opacity, "opacity", Opacity, [LenCalc Num Percent]),
            (order, "order", Order, [Int]),
            (orphans, "orphans", Orphans, [Int]),
            (outline, "outline", Outline, [Color LenCalc Length Str]),
            (outline_color, "outline-color", OutlineColor, [Color]),
            (outline_offset, "outline-offset", OutlineOffset, [LenCalc Length]),
            (outline_style, "outline-style", OutlineStyle, []),
            (outline_width, "outline-width", OutlineWidth, [LenCalc Length]),
            (overflow, "overflow", Overflow, [Str]),
            (overflow_anchor, "overflow-anchor", OverflowAnchor, []),
            (overflow_block, "overflow-block", OverflowBlock, []),
            (overflow_clip_margin, "overflow-clip-margin", OverflowClipMargin, [LenCalc Length Str]),
            (overflow_inline, "overflow-inline", OverflowInline, []),
            (overflow_wrap, "overflow-wrap", OverflowWrap, []),
            (overflow_x, "overflow-x", OverflowX, []),
            (overflow_y, "overflow-y", OverflowY, []),
            (overscroll_behavior, "overscroll-behavior", OverscrollBehavior, [Str]),
            (overscroll_behavior_block, "overscroll-behavior-block", OverscrollBehaviorBlock, []),
            (overscroll_behavior_inline, "overscroll-behavior-inline", OverscrollBehaviorInline, []),
            (overscroll_behavior_x, "overscroll-behavior-x", OverscrollBehaviorX, []),
            (overscroll_behavior_y, "overscroll-behavior-y", OverscrollBehaviorY, []),
            (padding, "padding", Padding, [LenCalc Length Percent Str]),
            (padding_block, "padding-block", PaddingBlock, [LenCalc Length Percent Str]),
            (padding_block_end, "padding-block-end", PaddingBlockEnd, [LenCalc Length Percent]),
            (padding_block_start, "padding-block-start", PaddingBlockStart, [LenCalc Length Percent]),
            (padding_bottom, "padding-bottom", PaddingBottom, [LenCalc Length Percent]),
            (padding_inline, "padding-inline", PaddingInline, [LenCalc Length Percent Str]),
            (padding_inline_end, "padding-inline-end", PaddingInlineEnd, [LenCalc Length Percent]),
            (padding_inline_start, "padding-inline-start", PaddingInlineStart, [LenCalc Length Percent]),
            (padding_left, "padding-left", PaddingLeft, [LenCalc Length Percent]),
            (padding_right, "padding-right", PaddingRight, [LenCalc Length Percent]),
            (padding_top, "padding-top", PaddingTop, [LenCalc Length Percent]),
            (page, "page", Page, [Str]),
            (paint_order, "paint-order", PaintOrder, [Str]),
            (perspective, "perspective", Perspective, [LenCalc Length]),
            (perspective_origin, "perspective-origin", PerspectiveOrigin, [LenCalc Length Percent Str]),
            (place_content, "place-content", PlaceContent, [Str]),
            (place_items, "place-items", PlaceItems, [Str]),
            (place_self, "place-self", PlaceSelf, [Str]),
            (pointer_events, "pointer-events", PointerEvents, []),
            (position, "position", Position, []),
            (print_color_adjust, "print-color-adjust", PrintColorAdjust, []),
            (quotes, "quotes", Quotes, [Str]),
            (r, "r", R, [LenCalc Length Percent]),
            (reading_flow, "reading-flow", ReadingFlow, []),
            (reading_order, "reading-order", ReadingOrder, [Int]),
            (resize, "resize", Resize, []),
            (right, "right", Right, [LenCalc Length Percent]),
            (rotate, "rotate", Rotate, [Angle Str]),
            (row_gap, "row-gap", RowGap, [LenCalc Length Percent]),
            (ruby_align, "ruby-align", RubyAlign, []),
            (ruby_overhang, "ruby-overhang", RubyOverhang, []),
            (ruby_position, "ruby-position", RubyPosition, [Str]),
            (rx, "rx", Rx, [LenCalc Length Percent]),
            (ry, "ry", Ry, [LenCalc Length Percent]),
            (scale, "scale", Scale, [LenCalc Num Percent Str]),
            (scroll_behavior, "scroll-behavior", ScrollBehavior, []),
            (scroll_margin, "scroll-margin", ScrollMargin, [LenCalc Length Str]),
            (scroll_margin_block, "scroll-margin-block", ScrollMarginBlock, [LenCalc Length Str]),
            (scroll_margin_block_end, "scroll-margin-block-end", ScrollMarginBlockEnd, [LenCalc Length]),
            (scroll_margin_block_start, "scroll-margin-block-start", ScrollMarginBlockStart, [LenCalc Length]),
            (scroll_margin_bottom, "scroll-margin-bottom", ScrollMarginBottom, [LenCalc Length]),
            (scroll_margin_inline, "scroll-margin-inline", ScrollMarginInline, [LenCalc Length Str]),
            (scroll_margin_inline_end, "scroll-margin-inline-end", ScrollMarginInlineEnd, [LenCalc Length]),
            (scroll_margin_inline_start, "scroll-margin-inline-start", ScrollMarginInlineStart, [LenCalc Length]),
            (scroll_margin_left, "scroll-margin-left", ScrollMarginLeft, [LenCalc Length]),
            (scroll_margin_right, "scroll-margin-right", ScrollMarginRight, [LenCalc Length]),
            (scroll_margin_top, "scroll-margin-top", ScrollMarginTop, [LenCalc Length]),
            (scroll_marker_group, "scroll-marker-group", ScrollMarkerGroup, []),
            (scroll_padding, "scroll-padding", ScrollPadding, [LenCalc Length Percent Str]),
            (scroll_padding_block, "scroll-padding-block", ScrollPaddingBlock, [LenCalc Length Percent Str]),
            (scroll_padding_block_end, "scroll-padding-block-end", ScrollPaddingBlockEnd, [LenCalc Length Percent]),
            (scroll_padding_block_start, "scroll-padding-block-start", ScrollPaddingBlockStart, [LenCalc Length Percent]),
            (scroll_padding_bottom, "scroll-padding-bottom", ScrollPaddingBottom, [LenCalc Length Percent]),
            (scroll_padding_inline, "scroll-padding-inline", ScrollPaddingInline, [LenCalc Length Percent Str]),
            (scroll_padding_inline_end, "scroll-padding-inline-end", ScrollPaddingInlineEnd, [LenCalc Length Percent]),
            (scroll_padding_inline_start, "scroll-padding-inline-start", ScrollPaddingInlineStart, [LenCalc Length Percent]),
            (scroll_padding_left, "scroll-padding-left", ScrollPaddingLeft, [LenCalc Length Percent]),
            (scroll_padding_right, "scroll-padding-right", ScrollPaddingRight, [LenCalc Length Percent]),
            (scroll_padding_top, "scroll-padding-top", ScrollPaddingTop, [LenCalc Length Percent]),
            (scroll_snap_align, "scroll-snap-align", ScrollSnapAlign, [Str]),
            (scroll_snap_stop, "scroll-snap-stop", ScrollSnapStop, []),
            (scroll_snap_type, "scroll-snap-type", ScrollSnapType, [Str]),
            (scroll_target_group, "scroll-target-group", ScrollTargetGroup, []),
            (scrollbar_color, "scrollbar-color", ScrollbarColor, [Str]),
            (scrollbar_gutter, "scrollbar-gutter", ScrollbarGutter, [Str]),
            (scrollbar_width, "scrollbar-width", ScrollbarWidth, []),
            (shape_image_threshold, "shape-image-threshold", ShapeImageThreshold, [LenCalc Num Percent]),
            (shape_margin, "shape-margin", ShapeMargin, [LenCalc Length Percent]),
            (shape_outside, "shape-outside", ShapeOutside, [Str Url]),
            (shape_rendering, "shape-rendering", ShapeRendering, []),
            (stop_color, "stop-color", StopColor, [Color]),
            (stop_opacity, "stop-opacity", StopOpacity, [LenCalc Num Percent]),
            (stroke, "stroke", Stroke, [Color Str Url]),
            (stroke_dasharray, "stroke-dasharray", StrokeDasharray, [LenCalc Length Num Percent Str]),
            (stroke_dashoffset, "stroke-dashoffset", StrokeDashoffset, [LenCalc Length Num Percent]),
            (stroke_linecap, "stroke-linecap", StrokeLinecap, []),
            (stroke_linejoin, "stroke-linejoin", StrokeLinejoin, []),
            (stroke_miterlimit, "stroke-miterlimit", StrokeMiterlimit, [Num]),
            (stroke_opacity, "stroke-opacity", StrokeOpacity, [LenCalc Num Percent]),
            (stroke_width, "stroke-width", StrokeWidth, [LenCalc Length Num Percent]),
            (tab_size, "tab-size", TabSize, [Int LenCalc Length]),
            (table_layout, "table-layout", TableLayout, []),
            (text_align, "text-align", TextAlign, []),
            (text_align_last, "text-align-last", TextAlignLast, []),
            (text_anchor, "text-anchor", TextAnchor, []),
            (text_autospace, "text-autospace", TextAutospace, [Str]),
            (text_box, "text-box", TextBox, [Str]),
            (text_box_edge, "text-box-edge", TextBoxEdge, [Str]),
            (text_box_trim, "text-box-trim", TextBoxTrim, []),
            (text_combine_upright, "text-combine-upright", TextCombineUpright, [Str]),
            (text_decoration, "text-decoration", TextDecoration, [Color LenCalc Length Percent Str]),
            (text_decoration_color, "text-decoration-color", TextDecorationColor, [Color]),
            (text_decoration_inset, "text-decoration-inset", TextDecorationInset, [LenCalc Length Str]),
            (text_decoration_line, "text-decoration-line", TextDecorationLine, [Str]),
            (text_decoration_skip_ink, "text-decoration-skip-ink", TextDecorationSkipInk, []),
            (text_decoration_style, "text-decoration-style", TextDecorationStyle, []),
            (text_decoration_thickness, "text-decoration-thickness", TextDecorationThickness, [LenCalc Length Percent]),
            (text_emphasis, "text-emphasis", TextEmphasis, [Color Str]),
            (text_emphasis_color, "text-emphasis-color", TextEmphasisColor, [Color]),
            (text_emphasis_position, "text-emphasis-position", TextEmphasisPosition, [Str]),
            (text_emphasis_style, "text-emphasis-style", TextEmphasisStyle, [Str]),
            (text_indent, "text-indent", TextIndent, [LenCalc Length Percent Str]),
            (text_justify, "text-justify", TextJustify, []),
            (text_orientation, "text-orientation", TextOrientation, []),
            (text_overflow, "text-overflow", TextOverflow, [Str]),
            (text_rendering, "text-rendering", TextRendering, []),
            (text_shadow, "text-shadow", TextShadow, [Str]),
            (text_transform, "text-transform", TextTransform, [Str]),
            (text_underline_offset, "text-underline-offset", TextUnderlineOffset, [LenCalc Length Percent]),
            (text_underline_position, "text-underline-position", TextUnderlinePosition, [Str]),
            (text_wrap, "text-wrap", TextWrap, [Str]),
            (text_wrap_mode, "text-wrap-mode", TextWrapMode, []),
            (text_wrap_style, "text-wrap-style", TextWrapStyle, []),
            (timeline_trigger, "timeline-trigger", TimelineTrigger, [Str]),
            (timeline_trigger_exit_range, "timeline-trigger-exit-range", TimelineTriggerExitRange, [LenCalc Length Percent Str]),
            (timeline_trigger_exit_range_end, "timeline-trigger-exit-range-end", TimelineTriggerExitRangeEnd, [LenCalc Length Percent Str]),
            (timeline_trigger_exit_range_start, "timeline-trigger-exit-range-start", TimelineTriggerExitRangeStart, [LenCalc Length Percent Str]),
            (timeline_trigger_name, "timeline-trigger-name", TimelineTriggerName, [Str]),
            (timeline_trigger_range, "timeline-trigger-range", TimelineTriggerRange, [LenCalc Length Percent Str]),
            (timeline_trigger_range_end, "timeline-trigger-range-end", TimelineTriggerRangeEnd, [LenCalc Length Percent Str]),
            (timeline_trigger_range_start, "timeline-trigger-range-start", TimelineTriggerRangeStart, [LenCalc Length Percent Str]),
            (timeline_trigger_source, "timeline-trigger-source", TimelineTriggerSource, [Str]),
            (top, "top", Top, [LenCalc Length Percent]),
            (touch_action, "touch-action", TouchAction, [Str]),
            (transform, "transform", Transform, [Str]),
            (transform_box, "transform-box", TransformBox, []),
            (transform_origin, "transform-origin", TransformOrigin, [LenCalc Length Percent Str]),
            (transform_style, "transform-style", TransformStyle, []),
            (transition, "transition", Transition, [Str]),
            (transition_behavior, "transition-behavior", TransitionBehavior, [Str]),
            (transition_delay, "transition-delay", TransitionDelay, [Str]),
            (transition_duration, "transition-duration", TransitionDuration, [Str]),
            (transition_property, "transition-property", TransitionProperty, [Str]),
            (transition_timing_function, "transition-timing-function", TransitionTimingFunction, [Str]),
            (translate, "translate", Translate, [LenCalc Length Percent Str]),
            (trigger_scope, "trigger-scope", TriggerScope, [Str]),
            (unicode_bidi, "unicode-bidi", UnicodeBidi, []),
            (user_select, "user-select", UserSelect, []),
            (vector_effect, "vector-effect", VectorEffect, []),
            (vertical_align, "vertical-align", VerticalAlign, [LenCalc Length Percent]),
            (view_transition_class, "view-transition-class", ViewTransitionClass, [Str]),
            (view_transition_name, "view-transition-name", ViewTransitionName, [Str]),
            (visibility, "visibility", Visibility, []),
            (white_space, "white-space", WhiteSpace, [Str]),
            (white_space_collapse, "white-space-collapse", WhiteSpaceCollapse, []),
            (widows, "widows", Widows, [Int]),
            (width, "width", Width, [LenCalc Length Percent]),
            (will_change, "will-change", WillChange, [Str]),
            (word_break, "word-break", WordBreak, []),
            (word_spacing, "word-spacing", WordSpacing, [LenCalc Length]),
            (word_wrap, "word-wrap", WordWrap, []),
            (writing_mode, "writing-mode", WritingMode, []),
            (x, "x", X, [LenCalc Length Percent]),
            (y, "y", Y, [LenCalc Length Percent]),
            (z_index, "z-index", ZIndex, [Int]),
            (zoom, "zoom", Zoom, [LenCalc Num Percent Str])
        }
    };
}
