[package]
name = "silex_router_example"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
silex = { workspace = true, features = ["bootstrap", "persistence"] }
wasm-bindgen.workspace = true
web-sys.workspace = true

[dev-dependencies]
gloo-timers.workspace = true
wasm-bindgen-test.workspace = true
