/// 精准静态匹配表
pub fn resolve_exact_match(class_name: &str) -> Option<Vec<(&'static str, String)>> {
    let rules: Option<&'static [(&'static str, &'static str)]> = match class_name {
        // Layout & Display
        "block" => Some(&[("display", "block")]),
        "inline-block" => Some(&[("display", "inline-block")]),
        "inline" => Some(&[("display", "inline")]),
        "flex" => Some(&[("display", "flex")]),
        "inline-flex" => Some(&[("display", "inline-flex")]),
        "grid" => Some(&[("display", "grid")]),
        "inline-grid" => Some(&[("display", "inline-grid")]),
        "hidden" => Some(&[("display", "none")]),
        "contents" => Some(&[("display", "contents")]),
        "table" => Some(&[("display", "table")]),
        "table-row" => Some(&[("display", "table-row")]),
        "table-cell" => Some(&[("display", "table-cell")]),
        "flow-root" => Some(&[("display", "flow-root")]),

        // Position
        "static" => Some(&[("position", "static")]),
        "fixed" => Some(&[("position", "fixed")]),
        "absolute" => Some(&[("position", "absolute")]),
        "relative" => Some(&[("position", "relative")]),
        "sticky" => Some(&[("position", "sticky")]),

        // Visibility
        "visible" => Some(&[("visibility", "visible")]),
        "invisible" => Some(&[("visibility", "hidden")]),
        "collapse" => Some(&[("visibility", "collapse")]),

        // Flex & Grid Direction / Wrap / Alignment
        "flex-row" => Some(&[("flex-direction", "row")]),
        "flex-row-reverse" => Some(&[("flex-direction", "row-reverse")]),
        "flex-col" => Some(&[("flex-direction", "column")]),
        "flex-col-reverse" => Some(&[("flex-direction", "column-reverse")]),
        "flex-wrap" => Some(&[("flex-wrap", "wrap")]),
        "flex-wrap-reverse" => Some(&[("flex-wrap", "wrap-reverse")]),
        "flex-nowrap" => Some(&[("flex-wrap", "nowrap")]),
        "flex-1" => Some(&[("flex", "1 1 0%")]),
        "flex-auto" => Some(&[("flex", "1 1 auto")]),
        "flex-initial" => Some(&[("flex", "0 1 auto")]),
        "flex-none" => Some(&[("flex", "none")]),
        "grow" => Some(&[("flex-grow", "1")]),
        "grow-0" => Some(&[("flex-grow", "0")]),
        "shrink" => Some(&[("flex-shrink", "1")]),
        "shrink-0" => Some(&[("flex-shrink", "0")]),
        "justify-start" => Some(&[("justify-content", "flex-start")]),
        "justify-end" => Some(&[("justify-content", "flex-end")]),
        "justify-center" => Some(&[("justify-content", "center")]),
        "justify-between" => Some(&[("justify-content", "space-between")]),
        "justify-around" => Some(&[("justify-content", "space-around")]),
        "justify-evenly" => Some(&[("justify-content", "space-evenly")]),
        "justify-stretch" => Some(&[("justify-content", "stretch")]),
        "items-start" => Some(&[("align-items", "flex-start")]),
        "items-end" => Some(&[("align-items", "flex-end")]),
        "items-center" => Some(&[("align-items", "center")]),
        "items-baseline" => Some(&[("align-items", "baseline")]),
        "items-stretch" => Some(&[("align-items", "stretch")]),
        "self-auto" => Some(&[("align-self", "auto")]),
        "self-start" => Some(&[("align-self", "flex-start")]),
        "self-end" => Some(&[("align-self", "flex-end")]),
        "self-center" => Some(&[("align-self", "center")]),
        "self-stretch" => Some(&[("align-self", "stretch")]),

        // Object fit & position
        "object-contain" => Some(&[("object-fit", "contain")]),
        "object-cover" => Some(&[("object-fit", "cover")]),
        "object-fill" => Some(&[("object-fit", "fill")]),
        "object-none" => Some(&[("object-fit", "none")]),
        "object-scale-down" => Some(&[("object-fit", "scale-down")]),

        // Typography
        "text-left" => Some(&[("text-align", "left")]),
        "text-center" => Some(&[("text-align", "center")]),
        "text-right" => Some(&[("text-align", "right")]),
        "text-justify" => Some(&[("text-align", "justify")]),
        "italic" => Some(&[("font-style", "italic")]),
        "not-italic" => Some(&[("font-style", "normal")]),
        "underline" => Some(&[("text-decoration-line", "underline")]),
        "overline" => Some(&[("text-decoration-line", "overline")]),
        "line-through" => Some(&[("text-decoration-line", "line-through")]),
        "no-underline" => Some(&[("text-decoration-line", "none")]),
        "uppercase" => Some(&[("text-transform", "uppercase")]),
        "lowercase" => Some(&[("text-transform", "lowercase")]),
        "capitalize" => Some(&[("text-transform", "capitalize")]),
        "normal-case" => Some(&[("text-transform", "none")]),
        "truncate" => Some(&[
            ("overflow", "hidden"),
            ("text-overflow", "ellipsis"),
            ("white-space", "nowrap"),
        ]),

        // Accessibility
        "sr-only" => Some(&[
            ("position", "absolute"),
            ("width", "1px"),
            ("height", "1px"),
            ("padding", "0"),
            ("margin", "-1px"),
            ("overflow", "hidden"),
            ("clip", "rect(0, 0, 0, 0)"),
            ("white-space", "nowrap"),
            ("border-width", "0"),
        ]),
        "not-sr-only" => Some(&[
            ("position", "static"),
            ("width", "auto"),
            ("height", "auto"),
            ("padding", "0"),
            ("margin", "0"),
            ("overflow", "visible"),
            ("clip", "auto"),
            ("white-space", "normal"),
        ]),

        // Interactivity
        "cursor-pointer" => Some(&[("cursor", "pointer")]),
        "cursor-default" => Some(&[("cursor", "default")]),
        "cursor-not-allowed" => Some(&[("cursor", "not-allowed")]),
        "cursor-wait" => Some(&[("cursor", "wait")]),
        "cursor-move" => Some(&[("cursor", "move")]),
        "cursor-text" => Some(&[("cursor", "text")]),
        "pointer-events-none" => Some(&[("pointer-events", "none")]),
        "pointer-events-auto" => Some(&[("pointer-events", "auto")]),
        "select-none" => Some(&[("user-select", "none")]),
        "select-text" => Some(&[("user-select", "text")]),
        "select-all" => Some(&[("user-select", "all")]),
        "select-auto" => Some(&[("user-select", "auto")]),

        // Overflow
        "overflow-auto" => Some(&[("overflow", "auto")]),
        "overflow-hidden" => Some(&[("overflow", "hidden")]),
        "overflow-visible" => Some(&[("overflow", "visible")]),
        "overflow-scroll" => Some(&[("overflow", "scroll")]),
        "overflow-x-auto" => Some(&[("overflow-x", "auto")]),
        "overflow-x-hidden" => Some(&[("overflow-x", "hidden")]),
        "overflow-y-auto" => Some(&[("overflow-y", "auto")]),
        "overflow-y-hidden" => Some(&[("overflow-y", "hidden")]),

        // Aspect ratio
        "aspect-auto" => Some(&[("aspect-ratio", "auto")]),
        "aspect-square" => Some(&[("aspect-ratio", "1 / 1")]),
        "aspect-video" => Some(&[("aspect-ratio", "16 / 9")]),

        // Vertical Align
        "align-baseline" => Some(&[("vertical-align", "baseline")]),
        "align-top" => Some(&[("vertical-align", "top")]),
        "align-middle" => Some(&[("vertical-align", "middle")]),
        "align-bottom" => Some(&[("vertical-align", "bottom")]),
        "align-text-top" => Some(&[("vertical-align", "text-top")]),
        "align-text-bottom" => Some(&[("vertical-align", "text-bottom")]),
        "align-sub" => Some(&[("vertical-align", "sub")]),
        "align-super" => Some(&[("vertical-align", "super")]),

        // Appearance
        "appearance-none" => Some(&[("appearance", "none")]),
        "appearance-auto" => Some(&[("appearance", "auto")]),

        // Backface
        "backface-visible" => Some(&[("backface-visibility", "visible")]),
        "backface-hidden" => Some(&[("backface-visibility", "hidden")]),

        // Background Attachment / Clip / Origin / Repeat / Size / Position
        "bg-fixed" => Some(&[("background-attachment", "fixed")]),
        "bg-local" => Some(&[("background-attachment", "local")]),
        "bg-scroll" => Some(&[("background-attachment", "scroll")]),
        "bg-clip-border" => Some(&[("background-clip", "border-box")]),
        "bg-clip-padding" => Some(&[("background-clip", "padding-box")]),
        "bg-clip-content" => Some(&[("background-clip", "content-box")]),
        "bg-clip-text" => Some(&[("background-clip", "text")]),
        "bg-origin-border" => Some(&[("background-origin", "border-box")]),
        "bg-origin-padding" => Some(&[("background-origin", "padding-box")]),
        "bg-origin-content" => Some(&[("background-origin", "content-box")]),
        "bg-repeat" => Some(&[("background-repeat", "repeat")]),
        "bg-no-repeat" => Some(&[("background-repeat", "no-repeat")]),
        "bg-repeat-x" => Some(&[("background-repeat", "repeat-x")]),
        "bg-repeat-y" => Some(&[("background-repeat", "repeat-y")]),
        "bg-repeat-round" => Some(&[("background-repeat", "round")]),
        "bg-repeat-space" => Some(&[("background-repeat", "space")]),
        "bg-auto" => Some(&[("background-size", "auto")]),
        "bg-cover" => Some(&[("background-size", "cover")]),
        "bg-contain" => Some(&[("background-size", "contain")]),
        "bg-bottom" => Some(&[("background-position", "bottom")]),
        "bg-center" => Some(&[("background-position", "center")]),
        "bg-left" => Some(&[("background-position", "left")]),
        "bg-right" => Some(&[("background-position", "right")]),
        "bg-top" => Some(&[("background-position", "top")]),
        "bg-top-left" => Some(&[("background-position", "top left")]),
        "bg-top-right" => Some(&[("background-position", "top right")]),
        "bg-bottom-left" => Some(&[("background-position", "bottom left")]),
        "bg-bottom-right" => Some(&[("background-position", "bottom right")]),

        // Box Sizing & Decoration
        "box-border" => Some(&[("box-sizing", "border-box")]),
        "box-content" => Some(&[("box-sizing", "content-box")]),
        "box-decoration-clone" => Some(&[("box-decoration-break", "clone")]),
        "box-decoration-slice" => Some(&[("box-decoration-break", "slice")]),

        // Clear & Float
        "clear-left" => Some(&[("clear", "left")]),
        "clear-right" => Some(&[("clear", "right")]),
        "clear-both" => Some(&[("clear", "both")]),
        "clear-none" => Some(&[("clear", "none")]),
        "clear-start" => Some(&[("clear", "inline-start")]),
        "clear-end" => Some(&[("clear", "inline-end")]),
        "float-left" => Some(&[("float", "left")]),
        "float-right" => Some(&[("float", "right")]),
        "float-none" => Some(&[("float", "none")]),
        "float-start" => Some(&[("float", "inline-start")]),
        "float-end" => Some(&[("float", "inline-end")]),

        // Isolation
        "isolate" => Some(&[("isolation", "isolate")]),
        "isolation-auto" => Some(&[("isolation", "auto")]),

        // Object Position
        "object-bottom" => Some(&[("object-position", "bottom")]),
        "object-center" => Some(&[("object-position", "center")]),
        "object-left" => Some(&[("object-position", "left")]),
        "object-right" => Some(&[("object-position", "right")]),
        "object-top" => Some(&[("object-position", "top")]),
        "object-top-left" => Some(&[("object-position", "top left")]),
        "object-top-right" => Some(&[("object-position", "top right")]),
        "object-bottom-left" => Some(&[("object-position", "bottom left")]),
        "object-bottom-right" => Some(&[("object-position", "bottom right")]),

        // Overscroll
        "overscroll-auto" => Some(&[("overscroll-behavior", "auto")]),
        "overscroll-contain" => Some(&[("overscroll-behavior", "contain")]),
        "overscroll-none" => Some(&[("overscroll-behavior", "none")]),
        "overscroll-x-auto" => Some(&[("overscroll-behavior-x", "auto")]),
        "overscroll-x-contain" => Some(&[("overscroll-behavior-x", "contain")]),
        "overscroll-x-none" => Some(&[("overscroll-behavior-x", "none")]),
        "overscroll-y-auto" => Some(&[("overscroll-behavior-y", "auto")]),
        "overscroll-y-contain" => Some(&[("overscroll-behavior-y", "contain")]),
        "overscroll-y-none" => Some(&[("overscroll-behavior-y", "none")]),

        // Breaks & Word Break & Whitespace & Hyphens
        "break-after-auto" => Some(&[("break-after", "auto")]),
        "break-after-avoid" => Some(&[("break-after", "avoid")]),
        "break-after-all" => Some(&[("break-after", "all")]),
        "break-after-avoid-page" => Some(&[("break-after", "avoid-page")]),
        "break-after-page" => Some(&[("break-after", "page")]),
        "break-after-left" => Some(&[("break-after", "left")]),
        "break-after-right" => Some(&[("break-after", "right")]),
        "break-after-column" => Some(&[("break-after", "column")]),
        "break-before-auto" => Some(&[("break-before", "auto")]),
        "break-before-avoid" => Some(&[("break-before", "avoid")]),
        "break-before-all" => Some(&[("break-before", "all")]),
        "break-before-avoid-page" => Some(&[("break-before", "avoid-page")]),
        "break-before-page" => Some(&[("break-before", "page")]),
        "break-before-left" => Some(&[("break-before", "left")]),
        "break-before-right" => Some(&[("break-before", "right")]),
        "break-before-column" => Some(&[("break-before", "column")]),
        "break-inside-auto" => Some(&[("break-inside", "auto")]),
        "break-inside-avoid" => Some(&[("break-inside", "avoid")]),
        "break-inside-avoid-page" => Some(&[("break-inside", "avoid-page")]),
        "break-inside-avoid-column" => Some(&[("break-inside", "avoid-column")]),
        "break-inside-avoid-flex" => Some(&[("break-inside", "avoid-flex")]),
        "break-all" => Some(&[("word-break", "break-all")]),
        "break-keep" => Some(&[("word-break", "keep-all")]),
        "break-normal" => Some(&[("overflow-wrap", "normal"), ("word-break", "normal")]),
        "whitespace-normal" => Some(&[("white-space", "normal")]),
        "whitespace-nowrap" => Some(&[("white-space", "nowrap")]),
        "whitespace-pre" => Some(&[("white-space", "pre")]),
        "whitespace-pre-line" => Some(&[("white-space", "pre-line")]),
        "whitespace-pre-wrap" => Some(&[("white-space", "pre-wrap")]),
        "whitespace-break-spaces" => Some(&[("white-space", "break-spaces")]),
        "hyphens-none" => Some(&[("hyphens", "none")]),
        "hyphens-manual" => Some(&[("hyphens", "manual")]),
        "hyphens-auto" => Some(&[("hyphens", "auto")]),

        // Font stretch & variant numeric
        "font-stretch-normal" => Some(&[("font-stretch", "normal")]),
        "font-stretch-condensed" => Some(&[("font-stretch", "condensed")]),
        "font-stretch-expanded" => Some(&[("font-stretch", "expanded")]),
        "font-stretch-ultra-condensed" => Some(&[("font-stretch", "ultra-condensed")]),
        "font-stretch-extra-condensed" => Some(&[("font-stretch", "extra-condensed")]),
        "font-stretch-semi-condensed" => Some(&[("font-stretch", "semi-condensed")]),
        "font-stretch-semi-expanded" => Some(&[("font-stretch", "semi-expanded")]),
        "font-stretch-extra-expanded" => Some(&[("font-stretch", "extra-expanded")]),
        "font-stretch-ultra-expanded" => Some(&[("font-stretch", "ultra-expanded")]),
        "ordinal" => Some(&[("font-variant-numeric", "ordinal")]),
        "slashed-zero" => Some(&[("font-variant-numeric", "slashed-zero")]),
        "lining-nums" => Some(&[("font-variant-numeric", "lining-nums")]),
        "oldstyle-nums" => Some(&[("font-variant-numeric", "oldstyle-nums")]),
        "proportional-nums" => Some(&[("font-variant-numeric", "proportional-nums")]),
        "tabular-nums" => Some(&[("font-variant-numeric", "tabular-nums")]),
        "diagonal-fractions" => Some(&[("font-variant-numeric", "diagonal-fractions")]),
        "stacked-fractions" => Some(&[("font-variant-numeric", "stacked-fractions")]),
        "normal-nums" => Some(&[("font-variant-numeric", "normal")]),

        // Text decoration style & thickness
        "decoration-solid" => Some(&[("text-decoration-style", "solid")]),
        "decoration-double" => Some(&[("text-decoration-style", "double")]),
        "decoration-dotted" => Some(&[("text-decoration-style", "dotted")]),
        "decoration-dashed" => Some(&[("text-decoration-style", "dashed")]),
        "decoration-wavy" => Some(&[("text-decoration-style", "wavy")]),
        "decoration-auto" => Some(&[("text-decoration-thickness", "auto")]),
        "decoration-from-font" => Some(&[("text-decoration-thickness", "from-font")]),
        "underline-offset-auto" => Some(&[("text-underline-offset", "auto")]),

        // Blend Modes
        "mix-blend-normal" => Some(&[("mix-blend-mode", "normal")]),
        "mix-blend-multiply" => Some(&[("mix-blend-mode", "multiply")]),
        "mix-blend-screen" => Some(&[("mix-blend-mode", "screen")]),
        "mix-blend-overlay" => Some(&[("mix-blend-mode", "overlay")]),
        "mix-blend-darken" => Some(&[("mix-blend-mode", "darken")]),
        "mix-blend-lighten" => Some(&[("mix-blend-mode", "lighten")]),
        "mix-blend-color-dodge" => Some(&[("mix-blend-mode", "color-dodge")]),
        "mix-blend-color-burn" => Some(&[("mix-blend-mode", "color-burn")]),
        "mix-blend-hard-light" => Some(&[("mix-blend-mode", "hard-light")]),
        "mix-blend-soft-light" => Some(&[("mix-blend-mode", "soft-light")]),
        "mix-blend-difference" => Some(&[("mix-blend-mode", "difference")]),
        "mix-blend-exclusion" => Some(&[("mix-blend-mode", "exclusion")]),
        "mix-blend-hue" => Some(&[("mix-blend-mode", "hue")]),
        "mix-blend-saturation" => Some(&[("mix-blend-mode", "saturation")]),
        "mix-blend-color" => Some(&[("mix-blend-mode", "color")]),
        "mix-blend-luminosity" => Some(&[("mix-blend-mode", "luminosity")]),
        "mix-blend-plus-lighter" => Some(&[("mix-blend-mode", "plus-lighter")]),
        "bg-blend-normal" => Some(&[("background-blend-mode", "normal")]),
        "bg-blend-multiply" => Some(&[("background-blend-mode", "multiply")]),
        "bg-blend-screen" => Some(&[("background-blend-mode", "screen")]),
        "bg-blend-overlay" => Some(&[("background-blend-mode", "overlay")]),
        "bg-blend-darken" => Some(&[("background-blend-mode", "darken")]),
        "bg-blend-lighten" => Some(&[("background-blend-mode", "lighten")]),
        "bg-blend-color-dodge" => Some(&[("background-blend-mode", "color-dodge")]),
        "bg-blend-color-burn" => Some(&[("background-blend-mode", "color-burn")]),
        "bg-blend-hard-light" => Some(&[("background-blend-mode", "hard-light")]),
        "bg-blend-soft-light" => Some(&[("background-blend-mode", "soft-light")]),
        "bg-blend-difference" => Some(&[("background-blend-mode", "difference")]),
        "bg-blend-exclusion" => Some(&[("background-blend-mode", "exclusion")]),
        "bg-blend-hue" => Some(&[("background-blend-mode", "hue")]),
        "bg-blend-saturation" => Some(&[("background-blend-mode", "saturation")]),
        "bg-blend-color" => Some(&[("background-blend-mode", "color")]),
        "bg-blend-luminosity" => Some(&[("background-blend-mode", "luminosity")]),

        // More Cursors
        "cursor-auto" => Some(&[("cursor", "auto")]),
        "cursor-none" => Some(&[("cursor", "none")]),
        "cursor-context-menu" => Some(&[("cursor", "context-menu")]),
        "cursor-help" => Some(&[("cursor", "help")]),
        "cursor-progress" => Some(&[("cursor", "progress")]),
        "cursor-cell" => Some(&[("cursor", "cell")]),
        "cursor-crosshair" => Some(&[("cursor", "crosshair")]),
        "cursor-vertical-text" => Some(&[("cursor", "vertical-text")]),
        "cursor-alias" => Some(&[("cursor", "alias")]),
        "cursor-copy" => Some(&[("cursor", "copy")]),
        "cursor-no-drop" => Some(&[("cursor", "no-drop")]),
        "cursor-grab" => Some(&[("cursor", "grab")]),
        "cursor-grabbing" => Some(&[("cursor", "grabbing")]),
        "cursor-all-scroll" => Some(&[("cursor", "all-scroll")]),
        "cursor-col-resize" => Some(&[("cursor", "col-resize")]),
        "cursor-row-resize" => Some(&[("cursor", "row-resize")]),
        "cursor-n-resize" => Some(&[("cursor", "n-resize")]),
        "cursor-e-resize" => Some(&[("cursor", "e-resize")]),
        "cursor-s-resize" => Some(&[("cursor", "s-resize")]),
        "cursor-w-resize" => Some(&[("cursor", "w-resize")]),
        "cursor-ne-resize" => Some(&[("cursor", "ne-resize")]),
        "cursor-nw-resize" => Some(&[("cursor", "nw-resize")]),
        "cursor-se-resize" => Some(&[("cursor", "se-resize")]),
        "cursor-sw-resize" => Some(&[("cursor", "sw-resize")]),
        "cursor-ew-resize" => Some(&[("cursor", "ew-resize")]),
        "cursor-ns-resize" => Some(&[("cursor", "ns-resize")]),
        "cursor-nesw-resize" => Some(&[("cursor", "nesw-resize")]),
        "cursor-nwse-resize" => Some(&[("cursor", "nwse-resize")]),
        "cursor-zoom-in" => Some(&[("cursor", "zoom-in")]),
        "cursor-zoom-out" => Some(&[("cursor", "zoom-out")]),

        // Resize & Touch & Will-Change & Forced Colors
        "resize-none" => Some(&[("resize", "none")]),
        "resize-y" => Some(&[("resize", "vertical")]),
        "resize-x" => Some(&[("resize", "horizontal")]),
        "resize" => Some(&[("resize", "both")]),
        "touch-auto" => Some(&[("touch-action", "auto")]),
        "touch-none" => Some(&[("touch-action", "none")]),
        "touch-pan-x" => Some(&[("touch-action", "pan-x")]),
        "touch-pan-left" => Some(&[("touch-action", "pan-left")]),
        "touch-pan-right" => Some(&[("touch-action", "pan-right")]),
        "touch-pan-y" => Some(&[("touch-action", "pan-y")]),
        "touch-pan-up" => Some(&[("touch-action", "pan-up")]),
        "touch-pan-down" => Some(&[("touch-action", "pan-down")]),
        "touch-pinch-zoom" => Some(&[("touch-action", "pinch-zoom")]),
        "touch-manipulation" => Some(&[("touch-action", "manipulation")]),
        "will-change-auto" => Some(&[("will-change", "auto")]),
        "will-change-scroll" => Some(&[("will-change", "scroll-position")]),
        "will-change-contents" => Some(&[("will-change", "contents")]),
        "will-change-transform" => Some(&[("will-change", "transform")]),
        "forced-color-adjust-auto" => Some(&[("forced-color-adjust", "auto")]),
        "forced-color-adjust-none" => Some(&[("forced-color-adjust", "none")]),

        // Align Content
        "content-normal" => Some(&[("align-content", "normal")]),
        "content-center" => Some(&[("align-content", "center")]),
        "content-start" => Some(&[("align-content", "flex-start")]),
        "content-end" => Some(&[("align-content", "flex-end")]),
        "content-between" => Some(&[("align-content", "space-between")]),
        "content-around" => Some(&[("align-content", "space-around")]),
        "content-evenly" => Some(&[("align-content", "space-evenly")]),
        "content-baseline" => Some(&[("align-content", "baseline")]),
        "content-stretch" => Some(&[("align-content", "stretch")]),

        // Justify & Items Align Extensions
        "justify-normal" => Some(&[("justify-content", "normal")]),
        "justify-items-start" => Some(&[("justify-items", "start")]),
        "justify-items-end" => Some(&[("justify-items", "end")]),
        "justify-items-center" => Some(&[("justify-items", "center")]),
        "justify-items-stretch" => Some(&[("justify-items", "stretch")]),
        "justify-items-normal" => Some(&[("justify-items", "normal")]),
        "justify-self-auto" => Some(&[("justify-self", "auto")]),
        "justify-self-start" => Some(&[("justify-self", "start")]),
        "justify-self-end" => Some(&[("justify-self", "end")]),
        "justify-self-center" => Some(&[("justify-self", "center")]),
        "justify-self-stretch" => Some(&[("justify-self", "stretch")]),
        "items-baseline-last" => Some(&[("align-items", "last baseline")]),
        "items-center-safe" => Some(&[("align-items", "safe center")]),
        "items-end-safe" => Some(&[("align-items", "safe end")]),
        "self-baseline" => Some(&[("align-self", "baseline")]),
        "self-baseline-last" => Some(&[("align-self", "last baseline")]),

        // SVG
        "fill-none" => Some(&[("fill", "none")]),
        "stroke-none" => Some(&[("stroke", "none")]),
        "stroke-0" => Some(&[("stroke-width", "0")]),
        "stroke-1" => Some(&[("stroke-width", "1px")]),
        "stroke-2" => Some(&[("stroke-width", "2px")]),
        "stroke-3" => Some(&[("stroke-width", "3px")]),

        // List & Table
        "list-inside" => Some(&[("list-style-position", "inside")]),
        "list-outside" => Some(&[("list-style-position", "outside")]),
        "list-disc" => Some(&[("list-style-type", "disc")]),
        "list-decimal" => Some(&[("list-style-type", "decimal")]),
        "list-none" => Some(&[("list-style-type", "none")]),
        "list-item" => Some(&[("display", "list-item")]),
        "list-image-none" => Some(&[("list-style-image", "none")]),
        "table-auto" => Some(&[("table-layout", "auto")]),
        "table-fixed" => Some(&[("table-layout", "fixed")]),
        "border-collapse" => Some(&[("border-collapse", "collapse")]),
        "border-separate" => Some(&[("border-collapse", "separate")]),
        "caption-top" => Some(&[("caption-side", "top")]),
        "caption-bottom" => Some(&[("caption-side", "bottom")]),
        "table-caption" => Some(&[("display", "table-caption")]),
        "table-column" => Some(&[("display", "table-column")]),
        "table-column-group" => Some(&[("display", "table-column-group")]),
        "table-footer-group" => Some(&[("display", "table-footer-group")]),
        "table-header-group" => Some(&[("display", "table-header-group")]),
        "table-row-group" => Some(&[("display", "table-row-group")]),

        // Background Gradient Directions & Antialiased
        "bg" => Some(&[("background-color", "transparent")]),
        "bg-none" => Some(&[("background-image", "none")]),
        "bg-linear-to-t" => Some(&[(
            "background-image",
            "linear-gradient(to top, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-tr" => Some(&[(
            "background-image",
            "linear-gradient(to top right, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-r" => Some(&[(
            "background-image",
            "linear-gradient(to right, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-br" => Some(&[(
            "background-image",
            "linear-gradient(to bottom right, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-b" => Some(&[(
            "background-image",
            "linear-gradient(to bottom, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-bl" => Some(&[(
            "background-image",
            "linear-gradient(to bottom left, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-l" => Some(&[(
            "background-image",
            "linear-gradient(to left, var(--tw-gradient-stops))",
        )]),
        "bg-linear-to-tl" => Some(&[(
            "background-image",
            "linear-gradient(to top left, var(--tw-gradient-stops))",
        )]),
        "antialiased" => Some(&[("-webkit-font-smoothing", "antialiased")]),
        "subpixel-antialiased" => Some(&[("-webkit-font-smoothing", "auto")]),

        // Accent & Animate
        "accent-auto" => Some(&[("accent-color", "auto")]),
        "animate-none" => Some(&[("animation", "none")]),
        "animate-in" => Some(&[("animation-name", "enter"), ("animation-duration", "150ms")]),
        "animate-out" => Some(&[("animation-name", "exit"), ("animation-duration", "150ms")]),

        // Contain & Container & Content
        "contain-none" => Some(&[("contain", "none")]),
        "contain-strict" => Some(&[("contain", "strict")]),
        "contain-content" => Some(&[("contain", "content")]),
        "contain-size" => Some(&[("contain", "size")]),
        "contain-inline-size" => Some(&[("contain", "inline-size")]),
        "contain-layout" => Some(&[("contain", "layout")]),
        "contain-paint" => Some(&[("contain", "paint")]),
        "contain-style" => Some(&[("contain", "style")]),
        "container" | "@container" => Some(&[("container-type", "inline-size")]),
        "@container-normal" => Some(&[("container-type", "normal")]),
        "content-none" => Some(&[("content", "none")]),
        "content-center-safe" => Some(&[("align-content", "safe center")]),
        "content-end-safe" => Some(&[("align-content", "safe end")]),

        // Field-Sizing & Flow-Root & Inline-Table
        "field-sizing-content" => Some(&[("field-sizing", "content")]),
        "field-sizing-fixed" => Some(&[("field-sizing", "fixed")]),
        "inline-table" => Some(&[("display", "inline-table")]),

        // Safe Alignments
        "justify-baseline" => Some(&[("justify-content", "baseline")]),
        "justify-center-safe" => Some(&[("justify-content", "safe center")]),
        "justify-end-safe" => Some(&[("justify-content", "safe end")]),
        "justify-items-center-safe" => Some(&[("justify-items", "safe center")]),
        "justify-items-end-safe" => Some(&[("justify-items", "safe end")]),
        "justify-self-center-safe" => Some(&[("justify-self", "safe center")]),
        "justify-self-end-safe" => Some(&[("justify-self", "safe end")]),
        "place-content-center-safe" => Some(&[("place-content", "safe center")]),
        "place-content-end-safe" => Some(&[("place-content", "safe end")]),
        "place-items-center-safe" => Some(&[("place-items", "safe center")]),
        "place-items-end-safe" => Some(&[("place-items", "safe end")]),
        "place-self-center-safe" => Some(&[("place-self", "safe center")]),
        "place-self-end-safe" => Some(&[("place-self", "safe end")]),
        "self-center-safe" => Some(&[("align-self", "safe center")]),
        "self-end-safe" => Some(&[("align-self", "safe end")]),

        // Overflow Clip & Scroll
        "overflow-clip" => Some(&[("overflow", "clip")]),
        "overflow-x-clip" => Some(&[("overflow-x", "clip")]),
        "overflow-y-clip" => Some(&[("overflow-y", "clip")]),
        "overflow-x-scroll" => Some(&[("overflow-x", "scroll")]),
        "overflow-y-scroll" => Some(&[("overflow-y", "scroll")]),
        "overflow-x-visible" => Some(&[("overflow-x", "visible")]),
        "overflow-y-visible" => Some(&[("overflow-y", "visible")]),

        // Scroll Behavior & Scrollbar & Scheme
        "scroll-smooth" => Some(&[("scroll-behavior", "smooth")]),
        "scroll-auto" => Some(&[("scroll-behavior", "auto")]),
        "scrollbar-auto" => Some(&[("scrollbar-width", "auto")]),
        "scrollbar-none" => Some(&[("scrollbar-width", "none")]),
        "scrollbar-thin" => Some(&[("scrollbar-width", "thin")]),
        "scrollbar-gutter-auto" => Some(&[("scrollbar-gutter", "auto")]),
        "scrollbar-gutter-stable" => Some(&[("scrollbar-gutter", "stable")]),
        "scrollbar-gutter-both" => Some(&[("scrollbar-gutter", "stable both-edges")]),
        "scheme-normal" => Some(&[("color-scheme", "normal")]),
        "scheme-light" => Some(&[("color-scheme", "light")]),
        "scheme-dark" => Some(&[("color-scheme", "dark")]),
        "scheme-light-dark" => Some(&[("color-scheme", "light dark")]),
        "scheme-only-light" => Some(&[("color-scheme", "only light")]),
        "scheme-only-dark" => Some(&[("color-scheme", "only dark")]),

        // Scroll Snap
        "snap-none" => Some(&[("scroll-snap-type", "none")]),
        "snap-x" => Some(&[("scroll-snap-type", "x var(--tw-scroll-snap-strictness)")]),
        "snap-y" => Some(&[("scroll-snap-type", "y var(--tw-scroll-snap-strictness)")]),
        "snap-both" => Some(&[("scroll-snap-type", "both var(--tw-scroll-snap-strictness)")]),
        "snap-mandatory" => Some(&[("--tw-scroll-snap-strictness", "mandatory")]),
        "snap-proximity" => Some(&[("--tw-scroll-snap-strictness", "proximity")]),
        "snap-start" => Some(&[("scroll-snap-align", "start")]),
        "snap-end" => Some(&[("scroll-snap-align", "end")]),
        "snap-center" => Some(&[("scroll-snap-align", "center")]),
        "snap-align-none" => Some(&[("scroll-snap-align", "none")]),
        "snap-normal" => Some(&[("scroll-snap-stop", "normal")]),
        "snap-always" => Some(&[("scroll-snap-stop", "always")]),

        // Text Overflow & Align
        "text-start" => Some(&[("text-align", "start")]),
        "text-end" => Some(&[("text-align", "end")]),
        "text-clip" => Some(&[("text-overflow", "clip")]),
        "text-ellipsis" => Some(&[("text-overflow", "ellipsis")]),

        // Transitions & Animations
        "transition-none" => Some(&[("transition-property", "none")]),
        "transition-all" => Some(&[("transition-property", "all")]),
        "transition" => Some(&[(
            "transition-property",
            "color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, translate, scale, rotate, filter, backdrop-filter",
        )]),
        "transition-colors" => Some(&[(
            "transition-property",
            "color, background-color, border-color, text-decoration-color, fill, stroke",
        )]),
        "transition-opacity" => Some(&[("transition-property", "opacity")]),
        "transition-shadow" => Some(&[("transition-property", "box-shadow")]),
        "transition-transform" => {
            Some(&[("transition-property", "transform, translate, scale, rotate")])
        }
        "transition-discrete" => Some(&[("transition-behavior", "allow-discrete")]),
        "duration-initial" => Some(&[("transition-duration", "initial")]),
        "ease-initial" => Some(&[("transition-timing-function", "initial")]),

        // Transform Utilities
        "transform" => Some(&[(
            "transform",
            "var(--tw-rotate-x) var(--tw-rotate-y) var(--tw-rotate-z) var(--tw-skew-x) var(--tw-skew-y)",
        )]),
        "transform-none" => Some(&[("transform", "none")]),
        "transform-gpu" => Some(&[(
            "transform",
            "translate3d(var(--tw-translate-x), var(--tw-translate-y), 0) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))",
        )]),
        "transform-cpu" => Some(&[(
            "transform",
            "translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))",
        )]),
        "transform-flat" => Some(&[("transform-style", "flat")]),
        "transform-3d" => Some(&[("transform-style", "preserve-3d")]),
        "transform-border" => Some(&[("transform-box", "border-box")]),
        "transform-content" => Some(&[("transform-box", "content-box")]),
        "transform-fill" => Some(&[("transform-box", "fill-box")]),
        "transform-stroke" => Some(&[("transform-box", "stroke-box")]),
        "transform-view" => Some(&[("transform-box", "view-box")]),

        // Background Radial / Conic Base & Gradient Via None
        "bg-radial" => Some(&[(
            "background-image",
            "radial-gradient(var(--tw-gradient-stops))",
        )]),
        "bg-conic" => Some(&[(
            "background-image",
            "conic-gradient(var(--tw-gradient-stops))",
        )]),
        "via-none" => Some(&[("--tw-gradient-via-stops", "none")]),

        // Border & Filter
        "border" => Some(&[("border-style", "solid"), ("border-width", "1px")]),
        "border-hidden" => Some(&[("border-style", "hidden")]),
        "grayscale" => Some(&[("filter", "grayscale(100%)")]),
        "invert" => Some(&[("filter", "invert(100%)")]),

        // Blend & Shadow & Transition Initial
        "mix-blend-plus-darker" => Some(&[("mix-blend-mode", "plus-darker")]),
        "shadow-initial" => Some(&[("box-shadow", "initial")]),
        "text-shadow-initial" => Some(&[("text-shadow", "initial")]),
        "text-shadow-none" => Some(&[("text-shadow", "none")]),
        "transition-normal" => Some(&[("transition-timing-function", "normal")]),

        // Mask Base & Position & Mode
        "mask-none" => Some(&[("mask-image", "none")]),
        "mask-alpha" => Some(&[("mask-type", "alpha")]),
        "mask-type-alpha" => Some(&[("mask-type", "alpha")]),
        "mask-type-luminance" => Some(&[("mask-type", "luminance")]),
        "mask-luminance" => Some(&[("mask-type", "luminance")]),
        "mask-match" => Some(&[("mask-mode", "match-source")]),
        "mask-circle" => Some(&[(
            "mask-image",
            "radial-gradient(circle, var(--tw-mask-stops))",
        )]),
        "mask-ellipse" => Some(&[(
            "mask-image",
            "radial-gradient(ellipse, var(--tw-mask-stops))",
        )]),
        "mask-contain" => Some(&[("mask-size", "contain")]),
        "mask-cover" => Some(&[("mask-size", "cover")]),
        "mask-auto" => Some(&[("mask-size", "auto")]),
        "mask-clip-border" => Some(&[("mask-clip", "border-box")]),
        "mask-clip-content" => Some(&[("mask-clip", "content-box")]),
        "mask-clip-padding" => Some(&[("mask-clip", "padding-box")]),
        "mask-clip-fill" => Some(&[("mask-clip", "fill-box")]),
        "mask-clip-stroke" => Some(&[("mask-clip", "stroke-box")]),
        "mask-clip-view" => Some(&[("mask-clip", "view-box")]),
        "mask-no-clip" => Some(&[("mask-clip", "no-clip")]),
        "mask-origin-border" => Some(&[("mask-origin", "border-box")]),
        "mask-origin-content" => Some(&[("mask-origin", "content-box")]),
        "mask-origin-padding" => Some(&[("mask-origin", "padding-box")]),
        "mask-origin-fill" => Some(&[("mask-origin", "fill-box")]),
        "mask-origin-stroke" => Some(&[("mask-origin", "stroke-box")]),
        "mask-origin-view" => Some(&[("mask-origin", "view-box")]),
        "mask-repeat" => Some(&[("mask-repeat", "repeat")]),
        "mask-no-repeat" => Some(&[("mask-repeat", "no-repeat")]),
        "mask-repeat-round" => Some(&[("mask-repeat", "round")]),
        "mask-repeat-space" => Some(&[("mask-repeat", "space")]),
        "mask-repeat-x" => Some(&[("mask-repeat", "repeat-x")]),
        "mask-repeat-y" => Some(&[("mask-repeat", "repeat-y")]),
        "mask-top" => Some(&[("mask-position", "top")]),
        "mask-bottom" => Some(&[("mask-position", "bottom")]),
        "mask-left" => Some(&[("mask-position", "left")]),
        "mask-right" => Some(&[("mask-position", "right")]),
        "mask-center" => Some(&[("mask-position", "center")]),
        "mask-top-left" => Some(&[("mask-position", "top left")]),
        "mask-top-right" => Some(&[("mask-position", "top right")]),
        "mask-bottom-left" => Some(&[("mask-position", "bottom left")]),
        "mask-bottom-right" => Some(&[("mask-position", "bottom right")]),
        "mask-add" => Some(&[("mask-composite", "add")]),
        "mask-subtract" => Some(&[("mask-composite", "subtract")]),
        "mask-intersect" => Some(&[("mask-composite", "intersect")]),
        "mask-exclude" => Some(&[("mask-composite", "exclude")]),
        "mask-radial-at-bottom" => Some(&[(
            "mask-image",
            "radial-gradient(at bottom, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-bottom-left" => Some(&[(
            "mask-image",
            "radial-gradient(at bottom left, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-bottom-right" => Some(&[(
            "mask-image",
            "radial-gradient(at bottom right, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-center" => Some(&[(
            "mask-image",
            "radial-gradient(at center, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-left" => Some(&[(
            "mask-image",
            "radial-gradient(at left, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-right" => Some(&[(
            "mask-image",
            "radial-gradient(at right, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-top" => Some(&[(
            "mask-image",
            "radial-gradient(at top, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-top-left" => Some(&[(
            "mask-image",
            "radial-gradient(at top left, var(--tw-mask-stops))",
        )]),
        "mask-radial-at-top-right" => Some(&[(
            "mask-image",
            "radial-gradient(at top right, var(--tw-mask-stops))",
        )]),
        "mask-radial-closest-corner" => Some(&[(
            "mask-image",
            "radial-gradient(closest-corner, var(--tw-mask-stops))",
        )]),
        "mask-radial-closest-side" => Some(&[(
            "mask-image",
            "radial-gradient(closest-side, var(--tw-mask-stops))",
        )]),
        "mask-radial-farthest-corner" => Some(&[(
            "mask-image",
            "radial-gradient(farthest-corner, var(--tw-mask-stops))",
        )]),
        "mask-radial-farthest-side" => Some(&[(
            "mask-image",
            "radial-gradient(farthest-side, var(--tw-mask-stops))",
        )]),

        _ => None,
    };

    rules.map(|r| r.iter().map(|&(k, v)| (k, v.to_string())).collect())
}
