[settings]
minimum_release_age = "1h"

[tools]
node = { version = "latest" }
pnpm = {
    version = "latest",
    depends = ["node"],
}
yarn = {
    version = "latest",
    depends = ["node"],
}

python = "latest"
rust = [
    {
        version = "stable",
        components = ["rust-src"],
        targets = ["wasm32-unknown-unknown"],
    },
    {
        version = "nightly",
        components = ["rust-src"],
        targets = ["wasm32-unknown-unknown"],
    },
]

# AI 工具
"npm:@openai/codex" = {
    version = "latest",
    depends = ["node"],
}
"aqua:anomalyco/opencode" = {
    version = "latest",
}
"aqua:google-antigravity/antigravity-cli" = {
    version = "latest",
}
"aqua:anthropics/claude-code" = {
    version = "latest",
}

# WebAssembly 工具
"cargo:wasmi_cli" = {
    version = "latest",
    depends = ["rust"],
}
"cargo:wasm-pack" = {
    version = "latest",
    depends = ["rust"],
}
"cargo:wasm-bindgen-cli" = {
    version = "latest",
    depends = ["rust"],
}

# 实用工具
jq = "latest"
ripgrep = "latest"
gh = "latest"
