pub mod callback;
pub mod context;
pub mod error;
pub mod logic;
pub mod node_ref;
mod owner;
pub mod reactivity;
pub mod scoped_slot;
pub mod store;
mod task;
pub mod traits;

pub use callback::Callback;
pub use context::{SilexContext, SilexContextProvider};
pub use error::{
    AppHostError, BootstrapError, CleanupOrigin, DisposeError, DomError, DomResult, ErrorHandler,
    ErrorHandlerAnchor, ErrorHandlerInput, ErrorHandlerToken, ErrorReporter, ErrorSeverity,
    HandlerLease, HostState, MountAvailability, MountError, RollbackError, SilexError,
    SilexErrorKind, SilexResult, UnmountOutcome, ViewError,
};

pub use error::{CleanupFailure as DomCleanupFailure, CleanupReport as DomCleanupReport};

#[cfg(feature = "error-persistence")]
pub use error::{PersistenceError, PersistenceErrorKind};

#[cfg(feature = "error-i18n")]
pub use error::{I18nError, I18nErrorKind};

#[cfg(feature = "error-router")]
pub use error::{
    PathError, PathErrorKind, PathParamError, PathParamErrorKind, RoutePatternError,
    RoutePatternErrorKind,
};

#[cfg(feature = "error-net")]
pub use error::{NetConnectionState, NetError, NetErrorKind};

#[cfg(feature = "error-intl")]
pub use error::{IntlError, IntlErrorKind};

pub use node_ref::NodeRef;
pub use owner::{OwnerAccess, OwnerChild, OwnerCleanupRegistrationError, OwnerHandle, Runtime};
pub use reactivity::{
    BorrowedReadGuard, Computed, Constant, EffectHandle, EffectPhase, MappedOptionReadGuard,
    MappedReadGuard, Mutation, PromotionPlan, ReactiveSource, ReadGuard, ReadSignal, Resource,
    ResourceBuilder, ResourceFetchBuilder, ResourceSource, ResourceSourceBuilder, Rx, RxReadGuard,
    Signal, StoredValue, SuspenseContext, Transaction, WatchOptions, WriteGuard, WriteSignal,
};
pub use scoped_slot::ScopedSlot;
#[cfg(feature = "test-support")]
pub use silex_reactivity::RuntimeSnapshot;
pub use silex_reactivity::{CallbackInvokeError, CompletionSubmitError};
pub type CompletionOnce<T> = silex_reactivity::CompletionOnce<T, SilexError>;
pub type CompletionSender<T> = silex_reactivity::CompletionSender<T, SilexError>;
pub use silex_reactivity::unwind_safe;
pub use store::StoreField;
pub use task::TaskHandle;
pub use traits::{
    ReactiveInput, RuntimeScoped, RxBase, RxData, RxDefault, RxFrom, RxGet, RxOptionGuard, RxRead,
    RxReadLease, RxReadOption, RxReadOptionSource, RxReadRef, RxReadRefSource, RxReadTuple1,
    RxReadTuple2, RxReadTuple3, RxReadTuple4, RxReadTuple5, RxReadTuple6, RxReadTupleSource1,
    RxReadTupleSource2, RxReadTupleSource3, RxReadTupleSource4, RxReadTupleSource5,
    RxReadTupleSource6, RxRefGuard, RxTupleGuard1, RxTupleGuard2, RxTupleGuard3, RxTupleGuard4,
    RxTupleGuard5, RxTupleGuard6, RxValue, RxWrite,
};

pub use silex_reactivity::ReactiveError;
pub use silex_reactivity::{
    CleanupDiagnostic, CleanupPayloadKind, CloseError, CloseFailure, ClosePhase, CloseSource,
    CloseTransaction,
};

pub use silex_rx::rx as __internal_rx;

/// Create a reactive value from an explicit component ctx.
///
/// The expansion returns a `SilexResult` and uses `?` internally to propagate
/// scope, promotion, and initial computation errors. The ctx supplies both
/// the scope and the [`ErrorHandler`] used for deferred errors.
///
/// `$source` is read through its existing tracked value access semantics. Use
/// `$(source.field)` when the field itself is the reactive source, such as a
/// field generated by `#[store]`.
#[macro_export]
macro_rules! rx {
    ($ctx:expr; $($body:tt)*) => {
        $crate::__internal_rx!($crate; @ctx $ctx; $($body)*)
    };
}

/// Read several values through nested closure-based accesses.
///
/// Each source is read through a tracked access, so this macro also preserves
/// dependencies when used inside a computation owned by a different lexical
/// scope. Use [`batch_read_untracked!`] when no dependency should be recorded.
#[macro_export]
macro_rules! batch_read {
    ($($source:expr),+ => |$($param:ident : $ty:ty),+| $body:expr) => {
        $crate::batch_read_recurse!([$($source),+] => [$($param : $ty),+] => $body)
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! batch_read_recurse {
    ([$source:expr] => [$param:ident : $ty:ty] => $body:expr) => {{
        use $crate::traits::RxReadRef;
        let __silex_batch_source = $source;
        __silex_batch_source.with(|$param: &$ty| $body)
    }};
    ([$source:expr, $($rest:expr),+] => [$param:ident : $ty:ty, $($params:ident : $tys:ty),+] => $body:expr) => {{
        use $crate::traits::RxReadRef;
        let __silex_batch_source = $source;
        __silex_batch_source.with(|$param: &$ty| {
            $crate::batch_read_recurse!([$($rest),+] => [$($params : $tys),+] => $body)
        })
    }};
}

#[macro_export]
macro_rules! batch_read_untracked {
    ($($source:expr),+ => |$($param:ident : $ty:ty),+| $body:expr) => {
        $crate::batch_read_untracked_recurse!([$($source),+] => [$($param : $ty),+] => $body)
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! batch_read_untracked_recurse {
    ([$source:expr] => [$param:ident : $ty:ty] => $body:expr) => {{
        use $crate::traits::RxReadRef;
        ($source).with_untracked(|$param: &$ty| $body)
    }};
    ([$source:expr, $($rest:expr),+] => [$param:ident : $ty:ty, $($params:ident : $tys:ty),+] => $body:expr) => {{
        use $crate::traits::RxReadRef;
        ($source).with_untracked(|$param: &$ty| {
            $crate::batch_read_untracked_recurse!([$($rest),+] => [$($params : $tys),+] => $body)
        })
    }};
}

pub mod prelude {
    pub use crate::{
        Callback, CompletionOnce, CompletionSender, ErrorHandler, ErrorHandlerInput,
        ErrorHandlerToken, ErrorReporter, NodeRef, OwnerAccess, OwnerHandle, ReactiveError,
        Runtime, Rx, ScopedSlot, SilexContext, SilexContextProvider, SilexError, SilexErrorKind,
        SilexResult, StoreField, Transaction, batch_read, batch_read_untracked, logic::*,
        reactivity::*, rx, traits::*, unwind_safe,
    };
}
