//! 自动生成：每个属性的取值能力与取值形态。
//!
//! 由 `silex_codegen` 从 MDN 值定义语法生成，与 `silex_css` 的
//! `for_all_properties!` 第四栏同源。

/// 位定义。
///
/// 前 11 位与 `silex_codegen::css::types::ValueCap` 一一对应，后两位是
/// 取值形态，`ValueCap` 里没有对应项。
pub mod cap {
    /// `Px` / `Rem` / `Em` / `Vw` / `Vh`
    pub const LENGTH: u16 = 1 << 0;
    /// `Percent`
    pub const PERCENT: u16 = 1 << 1;
    /// `CalcValue<LengthMark>`
    pub const LEN_CALC: u16 = 1 << 2;
    /// 全部数值类型（含整数）
    pub const NUM: u16 = 1 << 3;
    /// 仅整数类型
    pub const INT: u16 = 1 << 4;
    /// `Deg` / `Rad` / `Turn`
    pub const ANGLE: u16 = 1 << 5;
    /// `Sec` / `Ms`
    pub const TIME: u16 = 1 << 6;
    /// `Fr`——网格轨道的 `<flex>`
    pub const FLEX: u16 = 1 << 7;
    /// `Rgba` / `Hex` / `Hsl` / `ColorKeyword`
    pub const COLOR: u16 = 1 << 8;
    /// `Url`——含 `<image>`
    pub const URL: u16 = 1 << 9;
    /// 裸字符串兜底
    pub const STR: u16 = 1 << 10;
    /// 取值可以由多个**顶层分量**拼成（`<length>{1,4}`、`a && b`、`<x>#`）。
    ///
    /// 没有这一位的属性写成 `color: 1px solid red` 是确定的错误。
    pub const MULTI: u16 = 1 << 11;
    /// 语法里有 `<custom-ident>` / `<string>` / 解析不出来的引用——
    /// 能取什么在编译期无法穷举，所有取值校验一律放行。
    ///
    /// `animation-name: fadeIn`、`font-family: Inter`、`grid-area: header`
    /// 都靠这一位过关。
    pub const OPEN: u16 = 1 << 12;

    /// 数值类能力的并集。
    ///
    /// `calc()` 一族的量纲取决于操作数，宏侧不做求值；只在属性**完全
    /// 不接受任何数值类能力**时才判错。
    pub const ANY_NUMERIC: u16 = LENGTH | PERCENT | LEN_CALC | NUM | INT | ANGLE | TIME | FLEX;
}

/// (属性名, 位掩码)，按属性名升序，可二分查找。
///
/// 查不到的属性（自定义变量、注册表外的厂商前缀属性）没有语法数据，
/// 宏侧一律跳过取值校验。
pub static PROPERTY_CAPS: &[(&str, u16)] = &[
    ("-moz-appearance", 0),
    ("-moz-context-properties", cap::STR | cap::MULTI),
    ("-moz-orient", 0),
    ("-webkit-appearance", 0),
    (
        "-webkit-box-reflect",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::URL | cap::MULTI,
    ),
    ("-webkit-line-clamp", cap::INT),
    (
        "-webkit-mask",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::URL | cap::MULTI,
    ),
    ("-webkit-mask-clip", cap::STR | cap::MULTI),
    ("-webkit-mask-composite", cap::STR | cap::MULTI),
    ("-webkit-mask-image", cap::STR | cap::URL | cap::MULTI),
    ("-webkit-mask-origin", cap::STR | cap::MULTI),
    (
        "-webkit-mask-position",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("-webkit-mask-repeat", cap::STR | cap::MULTI),
    (
        "-webkit-mask-size",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("-webkit-overflow-scrolling", 0),
    ("-webkit-tap-highlight-color", cap::COLOR),
    ("-webkit-text-fill-color", cap::COLOR),
    (
        "-webkit-text-stroke",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("-webkit-text-stroke-color", cap::COLOR),
    ("-webkit-text-stroke-width", cap::LEN_CALC | cap::LENGTH),
    ("-webkit-touch-callout", 0),
    ("-webkit-user-modify", 0),
    ("-webkit-user-select", 0),
    ("accent-color", cap::COLOR),
    ("align-content", cap::STR | cap::MULTI),
    ("align-items", cap::STR | cap::MULTI),
    ("align-self", cap::STR | cap::MULTI),
    ("alignment-baseline", 0),
    ("all", 0),
    (
        "animation",
        cap::NUM | cap::STR | cap::TIME | cap::MULTI | cap::OPEN,
    ),
    ("animation-composition", cap::STR | cap::MULTI),
    ("animation-delay", cap::STR | cap::TIME | cap::MULTI),
    ("animation-direction", cap::STR | cap::MULTI),
    ("animation-duration", cap::STR | cap::TIME | cap::MULTI),
    ("animation-fill-mode", cap::STR | cap::MULTI),
    (
        "animation-iteration-count",
        cap::NUM | cap::STR | cap::MULTI,
    ),
    ("animation-name", cap::STR | cap::MULTI | cap::OPEN),
    ("animation-play-state", cap::STR | cap::MULTI),
    ("animation-timing-function", cap::STR | cap::MULTI),
    ("animation-trigger", cap::STR | cap::MULTI),
    ("appearance", 0),
    ("aspect-ratio", cap::NUM | cap::STR | cap::MULTI),
    ("backdrop-filter", cap::STR | cap::URL | cap::MULTI),
    ("backface-visibility", 0),
    (
        "background",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::URL | cap::MULTI,
    ),
    ("background-attachment", cap::STR | cap::MULTI),
    ("background-blend-mode", cap::STR | cap::MULTI),
    ("background-clip", cap::STR | cap::MULTI),
    ("background-color", cap::COLOR),
    ("background-image", cap::STR | cap::URL | cap::MULTI),
    ("background-origin", cap::STR | cap::MULTI),
    (
        "background-position",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "background-position-x",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "background-position-y",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("background-repeat", cap::STR | cap::MULTI),
    (
        "background-size",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("baseline-shift", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("baseline-source", 0),
    ("block-size", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "border",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "border-block",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-block-color", cap::COLOR | cap::STR | cap::MULTI),
    (
        "border-block-end",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-block-end-color", cap::COLOR),
    ("border-block-end-style", 0),
    ("border-block-end-width", cap::LEN_CALC | cap::LENGTH),
    (
        "border-block-start",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-block-start-color", cap::COLOR),
    ("border-block-start-style", 0),
    ("border-block-start-width", cap::LEN_CALC | cap::LENGTH),
    ("border-block-style", cap::STR | cap::MULTI),
    (
        "border-block-width",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "border-bottom",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-bottom-color", cap::COLOR),
    (
        "border-bottom-left-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-bottom-right-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("border-bottom-style", 0),
    ("border-bottom-width", cap::LEN_CALC | cap::LENGTH),
    ("border-collapse", 0),
    ("border-color", cap::COLOR | cap::STR | cap::MULTI),
    (
        "border-end-end-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-end-start-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-image",
        cap::LEN_CALC | cap::NUM | cap::PERCENT | cap::STR | cap::URL | cap::MULTI,
    ),
    (
        "border-image-outset",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::STR | cap::MULTI,
    ),
    ("border-image-repeat", cap::STR | cap::MULTI),
    (
        "border-image-slice",
        cap::LEN_CALC | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("border-image-source", cap::URL),
    (
        "border-image-width",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-inline",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-inline-color", cap::COLOR | cap::STR | cap::MULTI),
    (
        "border-inline-end",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-inline-end-color", cap::COLOR),
    ("border-inline-end-style", 0),
    ("border-inline-end-width", cap::LEN_CALC | cap::LENGTH),
    (
        "border-inline-start",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-inline-start-color", cap::COLOR),
    ("border-inline-start-style", 0),
    ("border-inline-start-width", cap::LEN_CALC | cap::LENGTH),
    ("border-inline-style", cap::STR | cap::MULTI),
    (
        "border-inline-width",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "border-left",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-left-color", cap::COLOR),
    ("border-left-style", 0),
    ("border-left-width", cap::LEN_CALC | cap::LENGTH),
    (
        "border-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-right",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-right-color", cap::COLOR),
    ("border-right-style", 0),
    ("border-right-width", cap::LEN_CALC | cap::LENGTH),
    (
        "border-spacing",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "border-start-end-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-start-start-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("border-style", cap::STR | cap::MULTI),
    (
        "border-top",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("border-top-color", cap::COLOR),
    (
        "border-top-left-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "border-top-right-radius",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("border-top-style", 0),
    ("border-top-width", cap::LEN_CALC | cap::LENGTH),
    (
        "border-width",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("bottom", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("box-decoration-break", 0),
    ("box-shadow", cap::STR | cap::MULTI),
    ("box-sizing", 0),
    ("break-after", 0),
    ("break-before", 0),
    ("break-inside", 0),
    ("caption-side", 0),
    ("caret", cap::COLOR | cap::STR | cap::MULTI),
    ("caret-animation", 0),
    ("caret-color", cap::COLOR),
    ("caret-shape", 0),
    ("clear", 0),
    ("clip-path", cap::STR | cap::URL | cap::MULTI),
    ("clip-rule", 0),
    ("color", cap::COLOR),
    ("color-interpolation-filters", 0),
    ("color-scheme", cap::STR | cap::MULTI | cap::OPEN),
    ("column-count", cap::INT),
    ("column-fill", 0),
    ("column-gap", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("column-height", cap::LEN_CALC | cap::LENGTH),
    (
        "column-rule",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("column-rule-color", cap::COLOR),
    ("column-rule-style", cap::STR | cap::MULTI),
    (
        "column-rule-width",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("column-span", 0),
    ("column-width", cap::LEN_CALC | cap::LENGTH),
    ("column-wrap", 0),
    (
        "columns",
        cap::INT | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("contain", cap::STR | cap::MULTI),
    (
        "contain-intrinsic-block-size",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "contain-intrinsic-height",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "contain-intrinsic-inline-size",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "contain-intrinsic-size",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "contain-intrinsic-width",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("container", cap::STR | cap::MULTI | cap::OPEN),
    ("container-name", cap::STR | cap::MULTI | cap::OPEN),
    ("container-type", cap::STR | cap::MULTI),
    ("content", cap::STR | cap::URL | cap::MULTI | cap::OPEN),
    ("content-visibility", 0),
    ("corner-block-end-shape", cap::STR | cap::MULTI),
    ("corner-block-start-shape", cap::STR | cap::MULTI),
    ("corner-bottom-left-shape", 0),
    ("corner-bottom-right-shape", 0),
    ("corner-bottom-shape", cap::STR | cap::MULTI),
    ("corner-end-end-shape", 0),
    ("corner-end-start-shape", 0),
    ("corner-inline-end-shape", cap::STR | cap::MULTI),
    ("corner-inline-start-shape", cap::STR | cap::MULTI),
    ("corner-left-shape", cap::STR | cap::MULTI),
    ("corner-right-shape", cap::STR | cap::MULTI),
    ("corner-shape", cap::STR | cap::MULTI),
    ("corner-start-end-shape", 0),
    ("corner-start-start-shape", 0),
    ("corner-top-left-shape", 0),
    ("corner-top-right-shape", 0),
    ("corner-top-shape", cap::STR | cap::MULTI),
    ("counter-increment", cap::STR | cap::MULTI | cap::OPEN),
    ("counter-reset", cap::STR | cap::MULTI | cap::OPEN),
    ("counter-set", cap::STR | cap::MULTI | cap::OPEN),
    ("cursor", cap::STR | cap::MULTI),
    ("cx", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("cy", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("d", 0),
    ("direction", 0),
    ("display", cap::STR | cap::MULTI),
    ("dominant-baseline", 0),
    ("dynamic-range-limit", 0),
    ("empty-cells", 0),
    ("fill", cap::COLOR | cap::STR | cap::URL | cap::MULTI),
    ("fill-opacity", cap::LEN_CALC | cap::NUM | cap::PERCENT),
    ("fill-rule", 0),
    ("filter", cap::STR | cap::URL | cap::MULTI),
    (
        "flex",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("flex-basis", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("flex-direction", 0),
    ("flex-flow", cap::STR | cap::MULTI),
    ("flex-grow", cap::NUM),
    ("flex-shrink", cap::NUM),
    ("flex-wrap", 0),
    ("float", 0),
    ("flood-color", cap::COLOR),
    ("flood-opacity", cap::LEN_CALC | cap::NUM | cap::PERCENT),
    ("font", cap::STR | cap::MULTI),
    ("font-family", cap::STR | cap::MULTI | cap::OPEN),
    ("font-feature-settings", cap::STR | cap::MULTI | cap::OPEN),
    ("font-kerning", 0),
    ("font-language-override", cap::STR | cap::OPEN),
    ("font-optical-sizing", 0),
    ("font-palette", cap::STR | cap::OPEN),
    ("font-size", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("font-size-adjust", cap::NUM | cap::STR | cap::MULTI),
    ("font-style", cap::STR | cap::MULTI),
    ("font-synthesis", cap::STR | cap::MULTI),
    ("font-synthesis-small-caps", 0),
    ("font-synthesis-style", 0),
    ("font-synthesis-weight", 0),
    ("font-variant", cap::STR | cap::MULTI),
    ("font-variant-alternates", cap::STR | cap::MULTI),
    ("font-variant-caps", 0),
    ("font-variant-east-asian", cap::STR | cap::MULTI),
    ("font-variant-emoji", 0),
    ("font-variant-ligatures", cap::STR | cap::MULTI),
    ("font-variant-numeric", cap::STR | cap::MULTI),
    ("font-variant-position", 0),
    ("font-variation-settings", cap::STR | cap::MULTI),
    ("font-weight", cap::NUM),
    ("forced-color-adjust", 0),
    (
        "gap",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("grid", cap::STR | cap::MULTI | cap::OPEN),
    ("grid-area", cap::INT | cap::STR | cap::MULTI | cap::OPEN),
    (
        "grid-auto-columns",
        cap::FLEX | cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("grid-auto-flow", cap::STR | cap::MULTI),
    (
        "grid-auto-rows",
        cap::FLEX | cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("grid-column", cap::INT | cap::STR | cap::MULTI | cap::OPEN),
    (
        "grid-column-end",
        cap::INT | cap::STR | cap::MULTI | cap::OPEN,
    ),
    (
        "grid-column-start",
        cap::INT | cap::STR | cap::MULTI | cap::OPEN,
    ),
    ("grid-row", cap::INT | cap::STR | cap::MULTI | cap::OPEN),
    ("grid-row-end", cap::INT | cap::STR | cap::MULTI | cap::OPEN),
    (
        "grid-row-start",
        cap::INT | cap::STR | cap::MULTI | cap::OPEN,
    ),
    ("grid-template", cap::STR | cap::MULTI | cap::OPEN),
    ("grid-template-areas", cap::STR | cap::MULTI | cap::OPEN),
    (
        "grid-template-columns",
        cap::FLEX | cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "grid-template-rows",
        cap::FLEX | cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("hanging-punctuation", cap::STR | cap::MULTI),
    ("height", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("hyphenate-character", cap::STR | cap::OPEN),
    ("hyphenate-limit-chars", cap::INT | cap::STR | cap::MULTI),
    ("hyphens", 0),
    ("image-orientation", cap::ANGLE | cap::STR | cap::MULTI),
    ("image-rendering", 0),
    ("initial-letter", cap::NUM | cap::STR | cap::MULTI),
    ("inline-size", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "inset",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "inset-block",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "inset-block-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "inset-block-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "inset-inline",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "inset-inline-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "inset-inline-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("interactivity", 0),
    ("interest-delay", cap::STR | cap::TIME | cap::MULTI),
    ("interest-delay-end", cap::TIME),
    ("interest-delay-start", cap::TIME),
    ("isolation", 0),
    ("justify-content", cap::STR | cap::MULTI),
    ("justify-items", cap::STR | cap::MULTI),
    ("justify-self", cap::STR | cap::MULTI),
    ("left", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("letter-spacing", cap::LEN_CALC | cap::LENGTH),
    ("lighting-color", cap::COLOR),
    ("line-break", 0),
    ("line-clamp", cap::INT),
    (
        "line-height",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT,
    ),
    ("list-style", cap::STR | cap::URL | cap::MULTI | cap::OPEN),
    ("list-style-image", cap::URL),
    ("list-style-position", 0),
    ("list-style-type", cap::STR | cap::OPEN),
    (
        "margin",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "margin-block",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "margin-block-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "margin-block-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("margin-bottom", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "margin-inline",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "margin-inline-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "margin-inline-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("margin-left", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("margin-right", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("margin-top", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("marker", cap::URL),
    ("marker-end", cap::URL),
    ("marker-mid", cap::URL),
    ("marker-start", cap::URL),
    (
        "mask",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::URL | cap::MULTI,
    ),
    (
        "mask-border",
        cap::LEN_CALC | cap::NUM | cap::PERCENT | cap::STR | cap::URL | cap::MULTI,
    ),
    ("mask-border-mode", 0),
    (
        "mask-border-outset",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::STR | cap::MULTI,
    ),
    ("mask-border-repeat", cap::STR | cap::MULTI),
    (
        "mask-border-slice",
        cap::LEN_CALC | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("mask-border-source", cap::URL),
    (
        "mask-border-width",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("mask-clip", cap::STR | cap::MULTI),
    ("mask-composite", cap::STR | cap::MULTI),
    ("mask-image", cap::STR | cap::URL | cap::MULTI),
    ("mask-mode", cap::STR | cap::MULTI),
    ("mask-origin", cap::STR | cap::MULTI),
    (
        "mask-position",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("mask-repeat", cap::STR | cap::MULTI),
    (
        "mask-size",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("mask-type", 0),
    ("math-depth", cap::INT),
    ("math-style", 0),
    ("max-block-size", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("max-height", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "max-inline-size",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("max-width", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("min-block-size", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("min-height", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "min-inline-size",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("min-width", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("mix-blend-mode", 0),
    ("object-fit", 0),
    (
        "object-position",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "offset",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::URL | cap::MULTI,
    ),
    (
        "offset-anchor",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "offset-distance",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("offset-path", cap::STR | cap::URL | cap::MULTI),
    (
        "offset-position",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("offset-rotate", cap::ANGLE | cap::STR | cap::MULTI),
    ("opacity", cap::LEN_CALC | cap::NUM | cap::PERCENT),
    ("order", cap::INT),
    ("orphans", cap::INT),
    (
        "outline",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("outline-color", cap::COLOR),
    ("outline-offset", cap::LEN_CALC | cap::LENGTH),
    ("outline-style", 0),
    ("outline-width", cap::LEN_CALC | cap::LENGTH),
    ("overflow", cap::STR | cap::MULTI),
    ("overflow-anchor", 0),
    ("overflow-block", 0),
    (
        "overflow-clip-margin",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("overflow-inline", 0),
    ("overflow-wrap", 0),
    ("overflow-x", 0),
    ("overflow-y", 0),
    ("overscroll-behavior", cap::STR | cap::MULTI),
    ("overscroll-behavior-block", 0),
    ("overscroll-behavior-inline", 0),
    ("overscroll-behavior-x", 0),
    ("overscroll-behavior-y", 0),
    (
        "padding",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "padding-block",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "padding-block-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "padding-block-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("padding-bottom", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "padding-inline",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "padding-inline-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "padding-inline-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("padding-left", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("padding-right", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("padding-top", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("page", cap::STR | cap::OPEN),
    ("paint-order", cap::STR | cap::MULTI),
    ("perspective", cap::LEN_CALC | cap::LENGTH),
    (
        "perspective-origin",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("place-content", cap::STR | cap::MULTI),
    ("place-items", cap::STR | cap::MULTI),
    ("place-self", cap::STR | cap::MULTI),
    ("pointer-events", 0),
    ("position", 0),
    ("print-color-adjust", 0),
    ("quotes", cap::STR | cap::MULTI),
    ("r", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("reading-flow", 0),
    ("reading-order", cap::INT),
    ("resize", 0),
    ("right", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("rotate", cap::ANGLE | cap::STR | cap::MULTI),
    ("row-gap", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("ruby-align", 0),
    ("ruby-overhang", 0),
    ("ruby-position", cap::STR | cap::MULTI),
    ("rx", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("ry", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    (
        "scale",
        cap::LEN_CALC | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("scroll-behavior", 0),
    (
        "scroll-margin",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    (
        "scroll-margin-block",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("scroll-margin-block-end", cap::LEN_CALC | cap::LENGTH),
    ("scroll-margin-block-start", cap::LEN_CALC | cap::LENGTH),
    ("scroll-margin-bottom", cap::LEN_CALC | cap::LENGTH),
    (
        "scroll-margin-inline",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("scroll-margin-inline-end", cap::LEN_CALC | cap::LENGTH),
    ("scroll-margin-inline-start", cap::LEN_CALC | cap::LENGTH),
    ("scroll-margin-left", cap::LEN_CALC | cap::LENGTH),
    ("scroll-margin-right", cap::LEN_CALC | cap::LENGTH),
    ("scroll-margin-top", cap::LEN_CALC | cap::LENGTH),
    ("scroll-marker-group", 0),
    (
        "scroll-padding",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "scroll-padding-block",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "scroll-padding-block-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-block-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-bottom",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-inline",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "scroll-padding-inline-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-inline-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-left",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-right",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "scroll-padding-top",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("scroll-snap-align", cap::STR | cap::MULTI),
    ("scroll-snap-stop", 0),
    ("scroll-snap-type", cap::STR | cap::MULTI),
    ("scroll-target-group", 0),
    ("scrollbar-color", cap::STR | cap::MULTI),
    ("scrollbar-gutter", cap::STR | cap::MULTI),
    ("scrollbar-width", 0),
    (
        "shape-image-threshold",
        cap::LEN_CALC | cap::NUM | cap::PERCENT,
    ),
    ("shape-margin", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("shape-outside", cap::STR | cap::URL | cap::MULTI),
    ("shape-rendering", 0),
    ("stop-color", cap::COLOR),
    ("stop-opacity", cap::LEN_CALC | cap::NUM | cap::PERCENT),
    ("stroke", cap::COLOR | cap::STR | cap::URL | cap::MULTI),
    (
        "stroke-dasharray",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "stroke-dashoffset",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT,
    ),
    ("stroke-linecap", 0),
    ("stroke-linejoin", 0),
    ("stroke-miterlimit", cap::NUM),
    ("stroke-opacity", cap::LEN_CALC | cap::NUM | cap::PERCENT),
    (
        "stroke-width",
        cap::LEN_CALC | cap::LENGTH | cap::NUM | cap::PERCENT,
    ),
    ("tab-size", cap::INT | cap::LEN_CALC | cap::LENGTH),
    ("table-layout", 0),
    ("text-align", 0),
    ("text-align-last", 0),
    ("text-anchor", 0),
    ("text-autospace", cap::STR | cap::OPEN),
    ("text-box", cap::STR | cap::MULTI),
    ("text-box-edge", cap::STR | cap::MULTI),
    ("text-box-trim", 0),
    ("text-combine-upright", cap::STR | cap::MULTI),
    (
        "text-decoration",
        cap::COLOR | cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("text-decoration-color", cap::COLOR),
    (
        "text-decoration-inset",
        cap::LEN_CALC | cap::LENGTH | cap::STR | cap::MULTI,
    ),
    ("text-decoration-line", cap::STR | cap::MULTI),
    ("text-decoration-skip-ink", 0),
    ("text-decoration-style", 0),
    (
        "text-decoration-thickness",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    (
        "text-emphasis",
        cap::COLOR | cap::STR | cap::MULTI | cap::OPEN,
    ),
    ("text-emphasis-color", cap::COLOR),
    ("text-emphasis-position", cap::STR | cap::MULTI),
    ("text-emphasis-style", cap::STR | cap::MULTI | cap::OPEN),
    (
        "text-indent",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("text-justify", 0),
    ("text-orientation", 0),
    ("text-overflow", cap::STR | cap::MULTI | cap::OPEN),
    ("text-rendering", 0),
    ("text-shadow", cap::STR | cap::MULTI),
    ("text-transform", cap::STR | cap::MULTI),
    (
        "text-underline-offset",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT,
    ),
    ("text-underline-position", cap::STR | cap::MULTI),
    ("text-wrap", cap::STR | cap::MULTI),
    ("text-wrap-mode", 0),
    ("text-wrap-style", 0),
    ("timeline-trigger", cap::STR | cap::MULTI),
    (
        "timeline-trigger-exit-range",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "timeline-trigger-exit-range-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "timeline-trigger-exit-range-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("timeline-trigger-name", cap::STR | cap::MULTI | cap::OPEN),
    (
        "timeline-trigger-range",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "timeline-trigger-range-end",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    (
        "timeline-trigger-range-start",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("timeline-trigger-source", cap::STR | cap::MULTI | cap::OPEN),
    ("top", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("touch-action", cap::STR | cap::MULTI),
    ("transform", cap::STR | cap::MULTI),
    ("transform-box", 0),
    (
        "transform-origin",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("transform-style", 0),
    ("transition", cap::STR | cap::TIME | cap::MULTI | cap::OPEN),
    ("transition-behavior", cap::STR | cap::MULTI),
    ("transition-delay", cap::STR | cap::TIME | cap::MULTI),
    ("transition-duration", cap::STR | cap::TIME | cap::MULTI),
    ("transition-property", cap::STR | cap::MULTI | cap::OPEN),
    ("transition-timing-function", cap::STR | cap::MULTI),
    (
        "translate",
        cap::LEN_CALC | cap::LENGTH | cap::PERCENT | cap::STR | cap::MULTI,
    ),
    ("trigger-scope", cap::STR | cap::MULTI | cap::OPEN),
    ("unicode-bidi", 0),
    ("user-select", 0),
    ("vector-effect", 0),
    ("vertical-align", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("view-transition-class", cap::STR | cap::MULTI | cap::OPEN),
    ("view-transition-name", cap::STR | cap::OPEN),
    ("visibility", 0),
    ("white-space", cap::STR | cap::MULTI),
    ("white-space-collapse", 0),
    ("widows", cap::INT),
    ("width", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("will-change", cap::STR | cap::MULTI | cap::OPEN),
    ("word-break", 0),
    ("word-spacing", cap::LEN_CALC | cap::LENGTH),
    ("word-wrap", 0),
    ("writing-mode", 0),
    ("x", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("y", cap::LEN_CALC | cap::LENGTH | cap::PERCENT),
    ("z-index", cap::INT),
    (
        "zoom",
        cap::LEN_CALC | cap::NUM | cap::PERCENT | cap::STR | cap::MULTI,
    ),
];
