//! 自动生成：每个属性可以单独取的字面关键字。
//!
//! 由 `silex_codegen` 从 MDN 值定义语法生成，与 `silex_css` 的
//! `keywords_gen.rs` 同源——都来自 `Analysis::keywords`。
//!
//! 「可以**单独**取」是关键：`align-items` 的 `safe` 不在表里，因为
//! `<overflow-position>` 必须跟着一个 `<self-position>`，`safe` 单独出现
//! 并不是合法取值。多分量取值由 `property_caps` 的 `MULTI` 位负责。

/// (属性名, 该属性的关键字表)。属性名升序，关键字表内部也升序，
/// 两层都可二分查找。
///
/// 关键字表为空的属性**不收录**：查不到就是没有判据，一律放行。
///
/// 全部小写：CSS 的关键字是 ASCII 大小写无关的，查表前把取值一并
/// 转小写就够了，不必两边各留一份大小写。
pub static PROPERTY_KEYWORDS: &[(&str, &[&str])] = &[
    (
        "-moz-appearance",
        &[
            "button",
            "button-arrow-down",
            "button-arrow-next",
            "button-arrow-previous",
            "button-arrow-up",
            "button-bevel",
            "button-focus",
            "caret",
            "checkbox",
            "checkbox-container",
            "checkbox-label",
            "checkmenuitem",
            "dualbutton",
            "groupbox",
            "listbox",
            "listitem",
            "menuarrow",
            "menubar",
            "menucheckbox",
            "menuimage",
            "menuitem",
            "menuitemtext",
            "menulist",
            "menulist-button",
            "menulist-text",
            "menulist-textfield",
            "menupopup",
            "menuradio",
            "menuseparator",
            "meterbar",
            "meterchunk",
            "none",
            "progressbar",
            "progressbar-vertical",
            "progresschunk",
            "progresschunk-vertical",
            "radio",
            "radio-container",
            "radio-label",
            "radiomenuitem",
            "range",
            "range-thumb",
            "resizer",
            "resizerpanel",
            "scale-horizontal",
            "scale-vertical",
            "scalethumb-horizontal",
            "scalethumb-vertical",
            "scalethumbend",
            "scalethumbstart",
            "scalethumbtick",
            "scrollbarbutton-down",
            "scrollbarbutton-left",
            "scrollbarbutton-right",
            "scrollbarbutton-up",
            "scrollbarthumb-horizontal",
            "scrollbarthumb-vertical",
            "scrollbartrack-horizontal",
            "scrollbartrack-vertical",
            "searchfield",
            "separator",
            "sheet",
            "spinner",
            "spinner-downbutton",
            "spinner-textfield",
            "spinner-upbutton",
            "splitter",
            "statusbar",
            "statusbarpanel",
            "tab",
            "tab-scroll-arrow-back",
            "tab-scroll-arrow-forward",
            "tabpanel",
            "tabpanels",
            "textfield",
            "textfield-multiline",
            "toolbar",
            "toolbarbutton",
            "toolbarbutton-dropdown",
            "toolbargripper",
            "toolbox",
            "tooltip",
            "treeheader",
            "treeheadercell",
            "treeheadersortarrow",
            "treeitem",
            "treeline",
            "treetwisty",
            "treetwistyopen",
            "treeview",
        ],
    ),
    (
        "-moz-context-properties",
        &["fill", "fill-opacity", "none", "stroke", "stroke-opacity"],
    ),
    (
        "-moz-orient",
        &["block", "horizontal", "inline", "vertical"],
    ),
    (
        "-webkit-appearance",
        &[
            "button",
            "button-bevel",
            "caret",
            "checkbox",
            "default-button",
            "inner-spin-button",
            "listbox",
            "listitem",
            "media-controls-background",
            "media-controls-fullscreen-background",
            "media-current-time-display",
            "media-enter-fullscreen-button",
            "media-exit-fullscreen-button",
            "media-fullscreen-button",
            "media-mute-button",
            "media-overlay-play-button",
            "media-play-button",
            "media-seek-back-button",
            "media-seek-forward-button",
            "media-slider",
            "media-sliderthumb",
            "media-time-remaining-display",
            "media-toggle-closed-captions-button",
            "media-volume-slider",
            "media-volume-slider-container",
            "media-volume-sliderthumb",
            "menulist",
            "menulist-button",
            "menulist-text",
            "menulist-textfield",
            "meter",
            "none",
            "progress-bar",
            "progress-bar-value",
            "push-button",
            "radio",
            "searchfield",
            "searchfield-cancel-button",
            "searchfield-decoration",
            "searchfield-results-button",
            "searchfield-results-decoration",
            "slider-horizontal",
            "slider-vertical",
            "sliderthumb-horizontal",
            "sliderthumb-vertical",
            "square-button",
            "textarea",
            "textfield",
        ],
    ),
    ("-webkit-box-reflect", &["above", "below", "left", "right"]),
    ("-webkit-line-clamp", &["none"]),
    (
        "-webkit-mask",
        &[
            "border",
            "border-box",
            "bottom",
            "center",
            "content",
            "content-box",
            "left",
            "no-repeat",
            "none",
            "padding",
            "padding-box",
            "repeat",
            "repeat-x",
            "repeat-y",
            "right",
            "round",
            "space",
            "text",
            "top",
        ],
    ),
    (
        "-webkit-mask-clip",
        &[
            "border",
            "border-box",
            "content",
            "content-box",
            "fill-box",
            "no-clip",
            "padding",
            "padding-box",
            "stroke-box",
            "text",
            "view-box",
        ],
    ),
    (
        "-webkit-mask-composite",
        &[
            "clear",
            "copy",
            "destination-atop",
            "destination-in",
            "destination-out",
            "destination-over",
            "source-atop",
            "source-in",
            "source-out",
            "source-over",
            "xor",
        ],
    ),
    ("-webkit-mask-image", &["none"]),
    (
        "-webkit-mask-origin",
        &[
            "border",
            "border-box",
            "content",
            "content-box",
            "fill-box",
            "padding",
            "padding-box",
            "stroke-box",
            "view-box",
        ],
    ),
    (
        "-webkit-mask-position",
        &["bottom", "center", "left", "right", "top"],
    ),
    (
        "-webkit-mask-repeat",
        &[
            "no-repeat",
            "repeat",
            "repeat-x",
            "repeat-y",
            "round",
            "space",
        ],
    ),
    ("-webkit-mask-size", &["auto", "contain", "cover"]),
    ("-webkit-overflow-scrolling", &["auto", "touch"]),
    ("-webkit-touch-callout", &["default", "none"]),
    (
        "-webkit-user-modify",
        &["read-only", "read-write", "read-write-plaintext-only"],
    ),
    ("-webkit-user-select", &["all", "auto", "none", "text"]),
    ("accent-color", &["auto"]),
    (
        "align-content",
        &[
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "normal",
            "space-around",
            "space-between",
            "space-evenly",
            "start",
            "stretch",
        ],
    ),
    (
        "align-items",
        &[
            "anchor-center",
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "normal",
            "self-end",
            "self-start",
            "start",
            "stretch",
        ],
    ),
    (
        "align-self",
        &[
            "anchor-center",
            "auto",
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "normal",
            "self-end",
            "self-start",
            "start",
            "stretch",
        ],
    ),
    (
        "alignment-baseline",
        &[
            "alphabetic",
            "baseline",
            "central",
            "ideographic",
            "mathematical",
            "middle",
            "text-after-edge",
            "text-before-edge",
        ],
    ),
    (
        "all",
        &["inherit", "initial", "revert", "revert-layer", "unset"],
    ),
    (
        "animation",
        &[
            "alternate",
            "alternate-reverse",
            "auto",
            "backwards",
            "both",
            "ease",
            "ease-in",
            "ease-in-out",
            "ease-out",
            "forwards",
            "infinite",
            "linear",
            "none",
            "normal",
            "paused",
            "reverse",
            "running",
            "step-end",
            "step-start",
        ],
    ),
    ("animation-composition", &["accumulate", "add", "replace"]),
    (
        "animation-direction",
        &["alternate", "alternate-reverse", "normal", "reverse"],
    ),
    ("animation-duration", &["auto"]),
    (
        "animation-fill-mode",
        &["backwards", "both", "forwards", "none"],
    ),
    ("animation-iteration-count", &["infinite"]),
    ("animation-name", &["none"]),
    ("animation-play-state", &["paused", "running"]),
    (
        "animation-timing-function",
        &[
            "ease",
            "ease-in",
            "ease-in-out",
            "ease-out",
            "linear",
            "step-end",
            "step-start",
        ],
    ),
    ("animation-trigger", &["none"]),
    (
        "appearance",
        &[
            "auto",
            "button",
            "checkbox",
            "listbox",
            "menulist",
            "menulist-button",
            "meter",
            "none",
            "progress-bar",
            "radio",
            "searchfield",
            "textarea",
            "textfield",
        ],
    ),
    ("aspect-ratio", &["auto"]),
    ("backdrop-filter", &["none"]),
    ("backface-visibility", &["hidden", "visible"]),
    (
        "background",
        &[
            "border-box",
            "bottom",
            "center",
            "content-box",
            "fixed",
            "left",
            "local",
            "no-repeat",
            "none",
            "padding-box",
            "repeat",
            "repeat-x",
            "repeat-y",
            "right",
            "round",
            "scroll",
            "space",
            "top",
        ],
    ),
    ("background-attachment", &["fixed", "local", "scroll"]),
    (
        "background-blend-mode",
        &[
            "color",
            "color-burn",
            "color-dodge",
            "darken",
            "difference",
            "exclusion",
            "hard-light",
            "hue",
            "lighten",
            "luminosity",
            "multiply",
            "normal",
            "overlay",
            "saturation",
            "screen",
            "soft-light",
        ],
    ),
    (
        "background-clip",
        &[
            "border-area",
            "border-box",
            "content-box",
            "padding-box",
            "text",
        ],
    ),
    ("background-image", &["none"]),
    (
        "background-origin",
        &["border-box", "content-box", "padding-box"],
    ),
    (
        "background-position",
        &["bottom", "center", "left", "right", "top"],
    ),
    (
        "background-position-x",
        &["center", "left", "right", "x-end", "x-start"],
    ),
    (
        "background-position-y",
        &["bottom", "center", "top", "y-end", "y-start"],
    ),
    (
        "background-repeat",
        &[
            "no-repeat",
            "repeat",
            "repeat-x",
            "repeat-y",
            "round",
            "space",
        ],
    ),
    ("background-size", &["auto", "contain", "cover"]),
    ("baseline-shift", &["baseline", "sub", "super"]),
    ("baseline-source", &["auto", "first", "last"]),
    (
        "block-size",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    (
        "border",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-block",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-block-end",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-block-end-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-block-end-width", &["medium", "thick", "thin"]),
    (
        "border-block-start",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-block-start-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-block-start-width", &["medium", "thick", "thin"]),
    (
        "border-block-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-block-width", &["medium", "thick", "thin"]),
    (
        "border-bottom",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-bottom-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-bottom-width", &["medium", "thick", "thin"]),
    ("border-collapse", &["collapse", "separate"]),
    (
        "border-image",
        &["none", "repeat", "round", "space", "stretch"],
    ),
    (
        "border-image-repeat",
        &["repeat", "round", "space", "stretch"],
    ),
    ("border-image-source", &["none"]),
    ("border-image-width", &["auto"]),
    (
        "border-inline",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-inline-end",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-inline-end-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-inline-end-width", &["medium", "thick", "thin"]),
    (
        "border-inline-start",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-inline-start-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-inline-start-width", &["medium", "thick", "thin"]),
    (
        "border-inline-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-inline-width", &["medium", "thick", "thin"]),
    (
        "border-left",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-left-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-left-width", &["medium", "thick", "thin"]),
    (
        "border-right",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-right-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-right-width", &["medium", "thick", "thin"]),
    (
        "border-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    (
        "border-top",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "border-top-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("border-top-width", &["medium", "thick", "thin"]),
    ("border-width", &["medium", "thick", "thin"]),
    ("bottom", &["auto"]),
    ("box-decoration-break", &["clone", "slice"]),
    ("box-shadow", &["none"]),
    ("box-sizing", &["border-box", "content-box"]),
    (
        "break-after",
        &[
            "all",
            "always",
            "auto",
            "avoid",
            "avoid-column",
            "avoid-page",
            "avoid-region",
            "column",
            "left",
            "page",
            "recto",
            "region",
            "right",
            "verso",
        ],
    ),
    (
        "break-before",
        &[
            "all",
            "always",
            "auto",
            "avoid",
            "avoid-column",
            "avoid-page",
            "avoid-region",
            "column",
            "left",
            "page",
            "recto",
            "region",
            "right",
            "verso",
        ],
    ),
    (
        "break-inside",
        &[
            "auto",
            "avoid",
            "avoid-column",
            "avoid-page",
            "avoid-region",
        ],
    ),
    ("caption-side", &["bottom", "top"]),
    ("caret", &["auto", "bar", "block", "manual", "underscore"]),
    ("caret-animation", &["auto", "manual"]),
    ("caret-color", &["auto"]),
    ("caret-shape", &["auto", "bar", "block", "underscore"]),
    (
        "clear",
        &[
            "both",
            "inline-end",
            "inline-start",
            "left",
            "none",
            "right",
        ],
    ),
    (
        "clip-path",
        &[
            "border-box",
            "content-box",
            "fill-box",
            "margin-box",
            "none",
            "padding-box",
            "stroke-box",
            "view-box",
        ],
    ),
    ("clip-rule", &["evenodd", "nonzero"]),
    (
        "color-interpolation-filters",
        &["auto", "linearrgb", "srgb"],
    ),
    ("color-scheme", &["dark", "light", "normal"]),
    ("column-count", &["auto"]),
    ("column-fill", &["auto", "balance"]),
    ("column-gap", &["normal"]),
    ("column-height", &["auto"]),
    (
        "column-rule",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    (
        "column-rule-style",
        &[
            "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("column-rule-width", &["medium", "thick", "thin"]),
    ("column-span", &["all", "none"]),
    ("column-width", &["auto"]),
    ("column-wrap", &["auto", "nowrap", "wrap"]),
    ("columns", &["auto"]),
    (
        "contain",
        &[
            "content",
            "inline-size",
            "layout",
            "none",
            "paint",
            "size",
            "strict",
            "style",
        ],
    ),
    ("contain-intrinsic-block-size", &["none"]),
    ("contain-intrinsic-height", &["none"]),
    ("contain-intrinsic-inline-size", &["none"]),
    ("contain-intrinsic-size", &["none"]),
    ("contain-intrinsic-width", &["none"]),
    ("container", &["none"]),
    ("container-name", &["none"]),
    (
        "container-type",
        &["inline-size", "normal", "scroll-state", "size"],
    ),
    (
        "content",
        &[
            "close-quote",
            "no-close-quote",
            "no-open-quote",
            "none",
            "normal",
            "open-quote",
        ],
    ),
    ("content-visibility", &["auto", "hidden", "visible"]),
    (
        "corner-block-end-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-block-start-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-bottom-left-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-bottom-right-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-bottom-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-end-end-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-end-start-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-inline-end-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-inline-start-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-left-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-right-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-start-end-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-start-start-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-top-left-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-top-right-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    (
        "corner-top-shape",
        &["bevel", "notch", "round", "scoop", "square", "squircle"],
    ),
    ("counter-increment", &["none"]),
    ("counter-reset", &["none"]),
    ("counter-set", &["none"]),
    (
        "cursor",
        &[
            "alias",
            "all-scroll",
            "auto",
            "cell",
            "col-resize",
            "context-menu",
            "copy",
            "crosshair",
            "default",
            "e-resize",
            "ew-resize",
            "grab",
            "grabbing",
            "help",
            "move",
            "n-resize",
            "ne-resize",
            "nesw-resize",
            "no-drop",
            "none",
            "not-allowed",
            "ns-resize",
            "nw-resize",
            "nwse-resize",
            "pointer",
            "progress",
            "row-resize",
            "s-resize",
            "se-resize",
            "sw-resize",
            "text",
            "vertical-text",
            "w-resize",
            "wait",
            "zoom-in",
            "zoom-out",
        ],
    ),
    ("d", &["none"]),
    ("direction", &["ltr", "rtl"]),
    (
        "display",
        &[
            "block",
            "contents",
            "flex",
            "flow",
            "flow-root",
            "grid",
            "inline",
            "inline-block",
            "inline-flex",
            "inline-grid",
            "inline-list-item",
            "inline-table",
            "list-item",
            "none",
            "ruby",
            "ruby-base",
            "ruby-base-container",
            "ruby-text",
            "ruby-text-container",
            "run-in",
            "table",
            "table-caption",
            "table-cell",
            "table-column",
            "table-column-group",
            "table-footer-group",
            "table-header-group",
            "table-row",
            "table-row-group",
        ],
    ),
    (
        "dominant-baseline",
        &[
            "alphabetic",
            "auto",
            "central",
            "hanging",
            "ideographic",
            "mathematical",
            "middle",
            "text-bottom",
            "text-top",
        ],
    ),
    (
        "dynamic-range-limit",
        &["constrained", "no-limit", "standard"],
    ),
    ("empty-cells", &["hide", "show"]),
    ("fill", &["context-fill", "context-stroke", "none"]),
    ("fill-rule", &["evenodd", "nonzero"]),
    ("filter", &["none"]),
    (
        "flex",
        &[
            "auto",
            "content",
            "fit-content",
            "max-content",
            "min-content",
            "none",
        ],
    ),
    (
        "flex-basis",
        &[
            "auto",
            "content",
            "fit-content",
            "max-content",
            "min-content",
        ],
    ),
    (
        "flex-direction",
        &["column", "column-reverse", "row", "row-reverse"],
    ),
    (
        "flex-flow",
        &[
            "column",
            "column-reverse",
            "nowrap",
            "row",
            "row-reverse",
            "wrap",
            "wrap-reverse",
        ],
    ),
    ("flex-wrap", &["nowrap", "wrap", "wrap-reverse"]),
    (
        "float",
        &["inline-end", "inline-start", "left", "none", "right"],
    ),
    (
        "font",
        &[
            "caption",
            "icon",
            "menu",
            "message-box",
            "small-caption",
            "status-bar",
        ],
    ),
    (
        "font-family",
        &[
            "cursive",
            "emoji",
            "fangsong",
            "fantasy",
            "math",
            "monospace",
            "sans-serif",
            "serif",
            "system-ui",
            "ui-monospace",
            "ui-rounded",
            "ui-sans-serif",
            "ui-serif",
        ],
    ),
    ("font-feature-settings", &["normal"]),
    ("font-kerning", &["auto", "none", "normal"]),
    ("font-language-override", &["normal"]),
    ("font-optical-sizing", &["auto", "none"]),
    ("font-palette", &["dark", "light", "normal"]),
    (
        "font-size",
        &[
            "large",
            "larger",
            "math",
            "medium",
            "small",
            "smaller",
            "x-large",
            "x-small",
            "xx-large",
            "xx-small",
            "xxx-large",
        ],
    ),
    ("font-size-adjust", &["from-font", "none"]),
    ("font-style", &["italic", "normal", "oblique"]),
    (
        "font-synthesis",
        &["none", "position", "small-caps", "style", "weight"],
    ),
    ("font-synthesis-small-caps", &["auto", "none"]),
    ("font-synthesis-style", &["auto", "none"]),
    ("font-synthesis-weight", &["auto", "none"]),
    (
        "font-variant",
        &[
            "all-petite-caps",
            "all-small-caps",
            "common-ligatures",
            "contextual",
            "diagonal-fractions",
            "discretionary-ligatures",
            "full-width",
            "historical-forms",
            "historical-ligatures",
            "jis04",
            "jis78",
            "jis83",
            "jis90",
            "lining-nums",
            "no-common-ligatures",
            "no-contextual",
            "no-discretionary-ligatures",
            "no-historical-ligatures",
            "none",
            "normal",
            "oldstyle-nums",
            "ordinal",
            "petite-caps",
            "proportional-nums",
            "proportional-width",
            "ruby",
            "simplified",
            "slashed-zero",
            "small-caps",
            "stacked-fractions",
            "tabular-nums",
            "titling-caps",
            "traditional",
            "unicase",
        ],
    ),
    ("font-variant-alternates", &["historical-forms", "normal"]),
    (
        "font-variant-caps",
        &[
            "all-petite-caps",
            "all-small-caps",
            "normal",
            "petite-caps",
            "small-caps",
            "titling-caps",
            "unicase",
        ],
    ),
    (
        "font-variant-east-asian",
        &[
            "full-width",
            "jis04",
            "jis78",
            "jis83",
            "jis90",
            "normal",
            "proportional-width",
            "ruby",
            "simplified",
            "traditional",
        ],
    ),
    (
        "font-variant-emoji",
        &["emoji", "normal", "text", "unicode"],
    ),
    (
        "font-variant-ligatures",
        &[
            "common-ligatures",
            "contextual",
            "discretionary-ligatures",
            "historical-ligatures",
            "no-common-ligatures",
            "no-contextual",
            "no-discretionary-ligatures",
            "no-historical-ligatures",
            "none",
            "normal",
        ],
    ),
    (
        "font-variant-numeric",
        &[
            "diagonal-fractions",
            "lining-nums",
            "normal",
            "oldstyle-nums",
            "ordinal",
            "proportional-nums",
            "slashed-zero",
            "stacked-fractions",
            "tabular-nums",
        ],
    ),
    ("font-variant-position", &["normal", "sub", "super"]),
    ("font-variation-settings", &["normal"]),
    ("font-weight", &["bold", "bolder", "lighter", "normal"]),
    (
        "forced-color-adjust",
        &["auto", "none", "preserve-parent-color"],
    ),
    ("gap", &["normal"]),
    ("grid", &["none"]),
    ("grid-area", &["auto"]),
    ("grid-auto-columns", &["auto", "max-content", "min-content"]),
    ("grid-auto-flow", &["column", "dense", "row"]),
    ("grid-auto-rows", &["auto", "max-content", "min-content"]),
    ("grid-column", &["auto"]),
    ("grid-column-end", &["auto"]),
    ("grid-column-start", &["auto"]),
    ("grid-row", &["auto"]),
    ("grid-row-end", &["auto"]),
    ("grid-row-start", &["auto"]),
    ("grid-template", &["none"]),
    ("grid-template-areas", &["none"]),
    (
        "grid-template-columns",
        &["auto", "max-content", "min-content", "none", "subgrid"],
    ),
    (
        "grid-template-rows",
        &["auto", "max-content", "min-content", "none", "subgrid"],
    ),
    (
        "hanging-punctuation",
        &["allow-end", "first", "force-end", "last", "none"],
    ),
    (
        "height",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    ("hyphenate-character", &["auto"]),
    ("hyphenate-limit-chars", &["auto"]),
    ("hyphens", &["auto", "manual", "none"]),
    ("image-orientation", &["flip", "from-image"]),
    (
        "image-rendering",
        &["auto", "crisp-edges", "pixelated", "smooth"],
    ),
    ("initial-letter", &["normal"]),
    (
        "inline-size",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    ("inset", &["auto"]),
    ("inset-block", &["auto"]),
    ("inset-block-end", &["auto"]),
    ("inset-block-start", &["auto"]),
    ("inset-inline", &["auto"]),
    ("inset-inline-end", &["auto"]),
    ("inset-inline-start", &["auto"]),
    ("interactivity", &["auto", "inert"]),
    ("interest-delay", &["normal"]),
    ("interest-delay-end", &["normal"]),
    ("interest-delay-start", &["normal"]),
    ("isolation", &["auto", "isolate"]),
    (
        "justify-content",
        &[
            "center",
            "end",
            "flex-end",
            "flex-start",
            "left",
            "normal",
            "right",
            "space-around",
            "space-between",
            "space-evenly",
            "start",
            "stretch",
        ],
    ),
    (
        "justify-items",
        &[
            "anchor-center",
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "left",
            "legacy",
            "normal",
            "right",
            "self-end",
            "self-start",
            "start",
            "stretch",
        ],
    ),
    (
        "justify-self",
        &[
            "anchor-center",
            "auto",
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "left",
            "normal",
            "right",
            "self-end",
            "self-start",
            "start",
            "stretch",
        ],
    ),
    ("left", &["auto"]),
    ("letter-spacing", &["normal"]),
    (
        "line-break",
        &["anywhere", "auto", "loose", "normal", "strict"],
    ),
    ("line-clamp", &["none"]),
    ("line-height", &["normal"]),
    ("list-style", &["inside", "none", "outside"]),
    ("list-style-image", &["none"]),
    ("list-style-position", &["inside", "outside"]),
    ("list-style-type", &["none"]),
    ("margin", &["auto"]),
    ("margin-block", &["auto"]),
    ("margin-block-end", &["auto"]),
    ("margin-block-start", &["auto"]),
    ("margin-bottom", &["auto"]),
    ("margin-inline", &["auto"]),
    ("margin-inline-end", &["auto"]),
    ("margin-inline-start", &["auto"]),
    ("margin-left", &["auto"]),
    ("margin-right", &["auto"]),
    ("margin-top", &["auto"]),
    ("marker", &["none"]),
    ("marker-end", &["none"]),
    ("marker-mid", &["none"]),
    ("marker-start", &["none"]),
    (
        "mask",
        &[
            "add",
            "alpha",
            "border-box",
            "bottom",
            "center",
            "content-box",
            "exclude",
            "fill-box",
            "intersect",
            "left",
            "luminance",
            "margin-box",
            "match-source",
            "no-clip",
            "no-repeat",
            "none",
            "padding-box",
            "repeat",
            "repeat-x",
            "repeat-y",
            "right",
            "round",
            "space",
            "stroke-box",
            "subtract",
            "top",
            "view-box",
        ],
    ),
    (
        "mask-border",
        &[
            "alpha",
            "luminance",
            "none",
            "repeat",
            "round",
            "space",
            "stretch",
        ],
    ),
    ("mask-border-mode", &["alpha", "luminance"]),
    (
        "mask-border-repeat",
        &["repeat", "round", "space", "stretch"],
    ),
    ("mask-border-source", &["none"]),
    ("mask-border-width", &["auto"]),
    (
        "mask-clip",
        &[
            "border-box",
            "content-box",
            "fill-box",
            "no-clip",
            "padding-box",
            "stroke-box",
            "view-box",
        ],
    ),
    (
        "mask-composite",
        &["add", "exclude", "intersect", "subtract"],
    ),
    ("mask-image", &["none"]),
    ("mask-mode", &["alpha", "luminance", "match-source"]),
    (
        "mask-origin",
        &[
            "border-box",
            "content-box",
            "fill-box",
            "padding-box",
            "stroke-box",
            "view-box",
        ],
    ),
    (
        "mask-position",
        &["bottom", "center", "left", "right", "top"],
    ),
    (
        "mask-repeat",
        &[
            "no-repeat",
            "repeat",
            "repeat-x",
            "repeat-y",
            "round",
            "space",
        ],
    ),
    ("mask-size", &["auto", "contain", "cover"]),
    ("mask-type", &["alpha", "luminance"]),
    ("math-depth", &["auto-add"]),
    ("math-style", &["compact", "normal"]),
    (
        "max-block-size",
        &["fit-content", "max-content", "min-content", "none"],
    ),
    (
        "max-height",
        &["fit-content", "max-content", "min-content", "none"],
    ),
    (
        "max-inline-size",
        &["fit-content", "max-content", "min-content", "none"],
    ),
    (
        "max-width",
        &["fit-content", "max-content", "min-content", "none"],
    ),
    (
        "min-block-size",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    (
        "min-height",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    (
        "min-inline-size",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    (
        "min-width",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    (
        "mix-blend-mode",
        &[
            "color",
            "color-burn",
            "color-dodge",
            "darken",
            "difference",
            "exclusion",
            "hard-light",
            "hue",
            "lighten",
            "luminosity",
            "multiply",
            "normal",
            "overlay",
            "plus-darker",
            "plus-lighter",
            "saturation",
            "screen",
            "soft-light",
        ],
    ),
    (
        "object-fit",
        &["contain", "cover", "fill", "none", "scale-down"],
    ),
    (
        "object-position",
        &["bottom", "center", "left", "right", "top"],
    ),
    (
        "offset",
        &[
            "auto",
            "border-box",
            "bottom",
            "center",
            "content-box",
            "fill-box",
            "left",
            "none",
            "normal",
            "padding-box",
            "right",
            "stroke-box",
            "top",
            "view-box",
        ],
    ),
    (
        "offset-anchor",
        &["auto", "bottom", "center", "left", "right", "top"],
    ),
    (
        "offset-path",
        &[
            "border-box",
            "content-box",
            "fill-box",
            "none",
            "padding-box",
            "stroke-box",
            "view-box",
        ],
    ),
    (
        "offset-position",
        &["auto", "bottom", "center", "left", "normal", "right", "top"],
    ),
    ("offset-rotate", &["auto", "reverse"]),
    (
        "outline",
        &[
            "auto", "dashed", "dotted", "double", "groove", "inset", "medium", "none", "outset",
            "ridge", "solid", "thick", "thin",
        ],
    ),
    ("outline-color", &["auto"]),
    (
        "outline-style",
        &[
            "auto", "dashed", "dotted", "double", "groove", "inset", "none", "outset", "ridge",
            "solid",
        ],
    ),
    ("outline-width", &["medium", "thick", "thin"]),
    ("overflow", &["auto", "clip", "hidden", "scroll", "visible"]),
    ("overflow-anchor", &["auto", "none"]),
    (
        "overflow-block",
        &["auto", "clip", "hidden", "scroll", "visible"],
    ),
    (
        "overflow-clip-margin",
        &["border-box", "content-box", "padding-box"],
    ),
    (
        "overflow-inline",
        &["auto", "clip", "hidden", "scroll", "visible"],
    ),
    ("overflow-wrap", &["anywhere", "break-word", "normal"]),
    (
        "overflow-x",
        &["auto", "clip", "hidden", "scroll", "visible"],
    ),
    (
        "overflow-y",
        &["auto", "clip", "hidden", "scroll", "visible"],
    ),
    ("overscroll-behavior", &["auto", "contain", "none"]),
    ("overscroll-behavior-block", &["auto", "contain", "none"]),
    ("overscroll-behavior-inline", &["auto", "contain", "none"]),
    ("overscroll-behavior-x", &["auto", "contain", "none"]),
    ("overscroll-behavior-y", &["auto", "contain", "none"]),
    ("page", &["auto"]),
    ("paint-order", &["fill", "markers", "normal", "stroke"]),
    ("perspective", &["none"]),
    (
        "perspective-origin",
        &["bottom", "center", "left", "right", "top"],
    ),
    (
        "place-content",
        &[
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "normal",
            "space-around",
            "space-between",
            "space-evenly",
            "start",
            "stretch",
        ],
    ),
    (
        "place-items",
        &[
            "anchor-center",
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "normal",
            "self-end",
            "self-start",
            "start",
            "stretch",
        ],
    ),
    (
        "place-self",
        &[
            "anchor-center",
            "auto",
            "baseline",
            "center",
            "end",
            "flex-end",
            "flex-start",
            "normal",
            "self-end",
            "self-start",
            "start",
            "stretch",
        ],
    ),
    (
        "pointer-events",
        &[
            "all",
            "auto",
            "fill",
            "inherit",
            "none",
            "painted",
            "stroke",
            "visible",
            "visiblefill",
            "visiblepainted",
            "visiblestroke",
        ],
    ),
    (
        "position",
        &["absolute", "fixed", "relative", "static", "sticky"],
    ),
    ("print-color-adjust", &["economy", "exact"]),
    ("quotes", &["auto", "none"]),
    (
        "reading-flow",
        &[
            "flex-flow",
            "flex-visual",
            "grid-columns",
            "grid-order",
            "grid-rows",
            "normal",
            "source-order",
        ],
    ),
    (
        "resize",
        &["block", "both", "horizontal", "inline", "none", "vertical"],
    ),
    ("right", &["auto"]),
    ("rotate", &["none"]),
    ("row-gap", &["normal"]),
    (
        "ruby-align",
        &["center", "space-around", "space-between", "start"],
    ),
    ("ruby-overhang", &["auto", "none"]),
    (
        "ruby-position",
        &["alternate", "inter-character", "over", "under"],
    ),
    ("scale", &["none"]),
    ("scroll-behavior", &["auto", "smooth"]),
    ("scroll-marker-group", &["after", "before", "none"]),
    ("scroll-padding", &["auto"]),
    ("scroll-padding-block", &["auto"]),
    ("scroll-padding-block-end", &["auto"]),
    ("scroll-padding-block-start", &["auto"]),
    ("scroll-padding-bottom", &["auto"]),
    ("scroll-padding-inline", &["auto"]),
    ("scroll-padding-inline-end", &["auto"]),
    ("scroll-padding-inline-start", &["auto"]),
    ("scroll-padding-left", &["auto"]),
    ("scroll-padding-right", &["auto"]),
    ("scroll-padding-top", &["auto"]),
    ("scroll-snap-align", &["center", "end", "none", "start"]),
    ("scroll-snap-stop", &["always", "normal"]),
    (
        "scroll-snap-type",
        &["block", "both", "inline", "none", "x", "y"],
    ),
    ("scroll-target-group", &["auto", "none"]),
    ("scrollbar-color", &["auto"]),
    ("scrollbar-gutter", &["auto", "stable"]),
    ("scrollbar-width", &["auto", "none", "thin"]),
    (
        "shape-outside",
        &[
            "border-box",
            "content-box",
            "margin-box",
            "none",
            "padding-box",
        ],
    ),
    (
        "shape-rendering",
        &["auto", "crispedges", "geometricprecision", "optimizespeed"],
    ),
    ("stroke", &["context-fill", "context-stroke", "none"]),
    ("stroke-dasharray", &["none"]),
    ("stroke-linecap", &["butt", "round", "square"]),
    (
        "stroke-linejoin",
        &["arcs", "bevel", "miter", "miter-clip", "round"],
    ),
    ("table-layout", &["auto", "fixed"]),
    (
        "text-align",
        &[
            "center",
            "end",
            "justify",
            "left",
            "match-parent",
            "right",
            "start",
        ],
    ),
    (
        "text-align-last",
        &["auto", "center", "end", "justify", "left", "right", "start"],
    ),
    ("text-anchor", &["end", "middle", "start"]),
    ("text-autospace", &["auto", "normal"]),
    (
        "text-box",
        &[
            "auto",
            "cap",
            "ex",
            "ideographic",
            "ideographic-ink",
            "none",
            "normal",
            "text",
            "trim-both",
            "trim-end",
            "trim-start",
        ],
    ),
    (
        "text-box-edge",
        &[
            "auto",
            "cap",
            "ex",
            "ideographic",
            "ideographic-ink",
            "text",
        ],
    ),
    (
        "text-box-trim",
        &["none", "trim-both", "trim-end", "trim-start"],
    ),
    ("text-combine-upright", &["all", "digits", "none"]),
    (
        "text-decoration",
        &[
            "auto",
            "blink",
            "dashed",
            "dotted",
            "double",
            "from-font",
            "grammar-error",
            "line-through",
            "none",
            "overline",
            "solid",
            "spelling-error",
            "underline",
            "wavy",
        ],
    ),
    ("text-decoration-inset", &["auto"]),
    (
        "text-decoration-line",
        &[
            "blink",
            "grammar-error",
            "line-through",
            "none",
            "overline",
            "spelling-error",
            "underline",
        ],
    ),
    ("text-decoration-skip-ink", &["all", "auto", "none"]),
    (
        "text-decoration-style",
        &["dashed", "dotted", "double", "solid", "wavy"],
    ),
    ("text-decoration-thickness", &["auto", "from-font"]),
    (
        "text-emphasis",
        &[
            "circle",
            "dot",
            "double-circle",
            "filled",
            "none",
            "open",
            "sesame",
            "triangle",
        ],
    ),
    ("text-emphasis-position", &["auto", "over", "under"]),
    (
        "text-emphasis-style",
        &[
            "circle",
            "dot",
            "double-circle",
            "filled",
            "none",
            "open",
            "sesame",
            "triangle",
        ],
    ),
    (
        "text-justify",
        &["auto", "inter-character", "inter-word", "none"],
    ),
    ("text-orientation", &["mixed", "sideways", "upright"]),
    ("text-overflow", &["clip", "ellipsis"]),
    (
        "text-rendering",
        &[
            "auto",
            "geometricprecision",
            "optimizelegibility",
            "optimizespeed",
        ],
    ),
    ("text-shadow", &["none"]),
    (
        "text-transform",
        &[
            "capitalize",
            "full-size-kana",
            "full-width",
            "lowercase",
            "math-auto",
            "none",
            "uppercase",
        ],
    ),
    ("text-underline-offset", &["auto"]),
    (
        "text-underline-position",
        &["auto", "from-font", "left", "right", "under"],
    ),
    (
        "text-wrap",
        &["auto", "balance", "nowrap", "pretty", "stable", "wrap"],
    ),
    ("text-wrap-mode", &["nowrap", "wrap"]),
    ("text-wrap-style", &["auto", "balance", "pretty", "stable"]),
    ("timeline-trigger", &["none"]),
    (
        "timeline-trigger-exit-range",
        &[
            "auto",
            "contain",
            "cover",
            "entry",
            "entry-crossing",
            "exit",
            "exit-crossing",
            "normal",
        ],
    ),
    (
        "timeline-trigger-exit-range-end",
        &[
            "auto",
            "contain",
            "cover",
            "entry",
            "entry-crossing",
            "exit",
            "exit-crossing",
            "normal",
        ],
    ),
    (
        "timeline-trigger-exit-range-start",
        &[
            "auto",
            "contain",
            "cover",
            "entry",
            "entry-crossing",
            "exit",
            "exit-crossing",
            "normal",
        ],
    ),
    ("timeline-trigger-name", &["none"]),
    (
        "timeline-trigger-range",
        &[
            "contain",
            "cover",
            "entry",
            "entry-crossing",
            "exit",
            "exit-crossing",
            "normal",
        ],
    ),
    (
        "timeline-trigger-range-end",
        &[
            "contain",
            "cover",
            "entry",
            "entry-crossing",
            "exit",
            "exit-crossing",
            "normal",
        ],
    ),
    (
        "timeline-trigger-range-start",
        &[
            "contain",
            "cover",
            "entry",
            "entry-crossing",
            "exit",
            "exit-crossing",
            "normal",
        ],
    ),
    ("timeline-trigger-source", &["auto", "none"]),
    ("top", &["auto"]),
    (
        "touch-action",
        &[
            "auto",
            "manipulation",
            "none",
            "pan-down",
            "pan-left",
            "pan-right",
            "pan-up",
            "pan-x",
            "pan-y",
            "pinch-zoom",
        ],
    ),
    ("transform", &["none"]),
    (
        "transform-box",
        &[
            "border-box",
            "content-box",
            "fill-box",
            "stroke-box",
            "view-box",
        ],
    ),
    (
        "transform-origin",
        &["bottom", "center", "left", "right", "top"],
    ),
    ("transform-style", &["flat", "preserve-3d"]),
    (
        "transition",
        &[
            "all",
            "allow-discrete",
            "ease",
            "ease-in",
            "ease-in-out",
            "ease-out",
            "linear",
            "none",
            "normal",
            "step-end",
            "step-start",
        ],
    ),
    ("transition-behavior", &["allow-discrete", "normal"]),
    ("transition-property", &["all", "none"]),
    (
        "transition-timing-function",
        &[
            "ease",
            "ease-in",
            "ease-in-out",
            "ease-out",
            "linear",
            "step-end",
            "step-start",
        ],
    ),
    ("translate", &["none"]),
    ("trigger-scope", &["all", "none"]),
    (
        "unicode-bidi",
        &[
            "bidi-override",
            "embed",
            "isolate",
            "isolate-override",
            "normal",
            "plaintext",
        ],
    ),
    ("user-select", &["all", "auto", "none", "text"]),
    (
        "vector-effect",
        &[
            "fixed-position",
            "non-rotation",
            "non-scaling-size",
            "non-scaling-stroke",
            "none",
        ],
    ),
    (
        "vertical-align",
        &[
            "baseline",
            "bottom",
            "middle",
            "sub",
            "super",
            "text-bottom",
            "text-top",
            "top",
        ],
    ),
    ("view-transition-class", &["none"]),
    ("view-transition-name", &["match-element", "none"]),
    ("visibility", &["collapse", "hidden", "visible"]),
    (
        "white-space",
        &[
            "break-spaces",
            "collapse",
            "normal",
            "nowrap",
            "pre",
            "pre-line",
            "pre-wrap",
            "preserve",
            "preserve-breaks",
            "preserve-spaces",
            "wrap",
        ],
    ),
    (
        "white-space-collapse",
        &[
            "break-spaces",
            "collapse",
            "preserve",
            "preserve-breaks",
            "preserve-spaces",
        ],
    ),
    (
        "width",
        &["auto", "fit-content", "max-content", "min-content"],
    ),
    ("will-change", &["auto", "contents", "scroll-position"]),
    (
        "word-break",
        &[
            "auto-phrase",
            "break-all",
            "break-word",
            "keep-all",
            "normal",
        ],
    ),
    ("word-spacing", &["normal"]),
    ("word-wrap", &["break-word", "normal"]),
    (
        "writing-mode",
        &[
            "horizontal-tb",
            "sideways-lr",
            "sideways-rl",
            "vertical-lr",
            "vertical-rl",
        ],
    ),
    ("z-index", &["auto"]),
    ("zoom", &["normal", "reset"]),
];

/// 全局具名颜色关键字（小写、升序）。
///
/// 属性侧的语法分析把 `<color>` 当作终点，所以 `red` / `transparent` /
/// `currentcolor` 不在任何属性的关键字表里。接受 `<color>` 的属性
/// （`property_caps` 里带 `COLOR` 位）额外拿这张表放行。
///
/// 与 `keywords_gen.rs` 的 `ColorKeyword` 同源，但这里统一小写：那边
/// 要按规范原样输出 `currentColor` / `Canvas`，这边只用来查表。
pub static COLOR_KEYWORDS: &[&str] = &[
    "accentcolor",
    "accentcolortext",
    "activeborder",
    "activecaption",
    "activetext",
    "aliceblue",
    "antiquewhite",
    "appworkspace",
    "aqua",
    "aquamarine",
    "azure",
    "background",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "buttonborder",
    "buttonface",
    "buttonhighlight",
    "buttonshadow",
    "buttontext",
    "cadetblue",
    "canvas",
    "canvastext",
    "captiontext",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "currentcolor",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "field",
    "fieldtext",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "graytext",
    "green",
    "greenyellow",
    "grey",
    "highlight",
    "highlighttext",
    "honeydew",
    "hotpink",
    "inactiveborder",
    "inactivecaption",
    "inactivecaptiontext",
    "indianred",
    "indigo",
    "infobackground",
    "infotext",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "linktext",
    "magenta",
    "mark",
    "marktext",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "menu",
    "menutext",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "scrollbar",
    "seagreen",
    "seashell",
    "selecteditem",
    "selecteditemtext",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "threeddarkshadow",
    "threedface",
    "threedhighlight",
    "threedlightshadow",
    "threedshadow",
    "tomato",
    "transparent",
    "turquoise",
    "violet",
    "visitedtext",
    "wheat",
    "white",
    "whitesmoke",
    "window",
    "windowframe",
    "windowtext",
    "yellow",
    "yellowgreen",
];

/// 对**所有**属性都合法的 CSS 全局取值，不必逐属性登记（升序）。
pub static UNIVERSAL_KEYWORDS: &[&str] = &["inherit", "initial", "revert", "revert-layer", "unset"];
