use phf::phf_map;
use proc_macro2::Span;
use syn::Result;

/// 属性解析结果
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PropertyResolveResult {
    /// 匹配到强类型的标准属性/短别名 (如 Padding, BorderRadius)
    Builtin(&'static str),
    /// 自定义 CSS 变量 (--*)，统一映射为 props::Any
    CustomVar,
}

/// 短别名映射表 (如 p => Padding, bg => BackgroundColor)
pub static SHORT_ALIAS_MAP: phf::Map<&'static str, &'static str> = phf_map! {
    "any" => "Any",
    "p" => "Padding",
    "px" => "PaddingInline",
    "py" => "PaddingBlock",
    "pt" => "PaddingTop",
    "pr" => "PaddingRight",
    "pb" => "PaddingBottom",
    "pl" => "PaddingLeft",
    "m" => "Margin",
    "mx" => "MarginInline",
    "my" => "MarginBlock",
    "mt" => "MarginTop",
    "mr" => "MarginRight",
    "mb" => "MarginBottom",
    "ml" => "MarginLeft",
    "w" => "Width",
    "h" => "Height",
    "bg" => "BackgroundColor",
    "text" => "Color",
    "border" => "BorderColor",
    "rounded" => "BorderRadius",
};

macro_rules! phf_pascal_map {
    ($($name:literal),* $(,)?) => {
        phf_map! {
            $($name => $name),*
        }
    };
}

/// silex_css 注册的全量标准属性 PascalCase PHF 哈希表
pub static STANDARD_PASCAL_MAP: phf::Map<&'static str, &'static str> = phf_pascal_map! {
    "WebkitLineClamp",
    "WebkitTextFillColor",
    "WebkitTextStroke",
    "WebkitTextStrokeColor",
    "WebkitTextStrokeWidth",
    "AccentColor",
    "AlignContent",
    "AlignItems",
    "AlignSelf",
    "AlignmentBaseline",
    "All",
    "Animation",
    "AnimationComposition",
    "AnimationDelay",
    "AnimationDirection",
    "AnimationDuration",
    "AnimationFillMode",
    "AnimationIterationCount",
    "AnimationName",
    "AnimationPlayState",
    "AnimationTimingFunction",
    "AnimationTrigger",
    "Appearance",
    "AspectRatio",
    "BackdropFilter",
    "BackfaceVisibility",
    "Background",
    "BackgroundAttachment",
    "BackgroundBlendMode",
    "BackgroundClip",
    "BackgroundColor",
    "BackgroundImage",
    "BackgroundOrigin",
    "BackgroundPosition",
    "BackgroundPositionX",
    "BackgroundPositionY",
    "BackgroundRepeat",
    "BackgroundSize",
    "BaselineShift",
    "BaselineSource",
    "BlockSize",
    "Border",
    "BorderBlock",
    "BorderBlockColor",
    "BorderBlockEnd",
    "BorderBlockEndColor",
    "BorderBlockEndStyle",
    "BorderBlockEndWidth",
    "BorderBlockStart",
    "BorderBlockStartColor",
    "BorderBlockStartStyle",
    "BorderBlockStartWidth",
    "BorderBlockStyle",
    "BorderBlockWidth",
    "BorderBottom",
    "BorderBottomColor",
    "BorderBottomLeftRadius",
    "BorderBottomRightRadius",
    "BorderBottomStyle",
    "BorderBottomWidth",
    "BorderCollapse",
    "BorderColor",
    "BorderEndEndRadius",
    "BorderEndStartRadius",
    "BorderImage",
    "BorderImageOutset",
    "BorderImageRepeat",
    "BorderImageSlice",
    "BorderImageSource",
    "BorderImageWidth",
    "BorderInline",
    "BorderInlineColor",
    "BorderInlineEnd",
    "BorderInlineEndColor",
    "BorderInlineEndStyle",
    "BorderInlineEndWidth",
    "BorderInlineStart",
    "BorderInlineStartColor",
    "BorderInlineStartStyle",
    "BorderInlineStartWidth",
    "BorderInlineStyle",
    "BorderInlineWidth",
    "BorderLeft",
    "BorderLeftColor",
    "BorderLeftStyle",
    "BorderLeftWidth",
    "BorderRadius",
    "BorderRight",
    "BorderRightColor",
    "BorderRightStyle",
    "BorderRightWidth",
    "BorderSpacing",
    "BorderStartEndRadius",
    "BorderStartStartRadius",
    "BorderStyle",
    "BorderTop",
    "BorderTopColor",
    "BorderTopLeftRadius",
    "BorderTopRightRadius",
    "BorderTopStyle",
    "BorderTopWidth",
    "BorderWidth",
    "Bottom",
    "BoxDecorationBreak",
    "BoxShadow",
    "BoxSizing",
    "BreakAfter",
    "BreakBefore",
    "BreakInside",
    "CaptionSide",
    "Caret",
    "CaretAnimation",
    "CaretColor",
    "CaretShape",
    "Clear",
    "ClipPath",
    "ClipRule",
    "Color",
    "ColorInterpolationFilters",
    "ColorScheme",
    "ColumnCount",
    "ColumnFill",
    "ColumnGap",
    "ColumnHeight",
    "ColumnRule",
    "ColumnRuleColor",
    "ColumnRuleStyle",
    "ColumnRuleWidth",
    "ColumnSpan",
    "ColumnWidth",
    "ColumnWrap",
    "Columns",
    "Contain",
    "ContainIntrinsicBlockSize",
    "ContainIntrinsicHeight",
    "ContainIntrinsicInlineSize",
    "ContainIntrinsicSize",
    "ContainIntrinsicWidth",
    "Container",
    "ContainerName",
    "ContainerType",
    "Content",
    "ContentVisibility",
    "CornerBlockEndShape",
    "CornerBlockStartShape",
    "CornerBottomLeftShape",
    "CornerBottomRightShape",
    "CornerBottomShape",
    "CornerEndEndShape",
    "CornerEndStartShape",
    "CornerInlineEndShape",
    "CornerInlineStartShape",
    "CornerLeftShape",
    "CornerRightShape",
    "CornerShape",
    "CornerStartEndShape",
    "CornerStartStartShape",
    "CornerTopLeftShape",
    "CornerTopRightShape",
    "CornerTopShape",
    "CounterIncrement",
    "CounterReset",
    "CounterSet",
    "Cursor",
    "Cx",
    "Cy",
    "D",
    "Direction",
    "Display",
    "DominantBaseline",
    "DynamicRangeLimit",
    "EmptyCells",
    "Fill",
    "FillOpacity",
    "FillRule",
    "Filter",
    "Flex",
    "FlexBasis",
    "FlexDirection",
    "FlexFlow",
    "FlexGrow",
    "FlexShrink",
    "FlexWrap",
    "Float",
    "FloodColor",
    "FloodOpacity",
    "Font",
    "FontFamily",
    "FontFeatureSettings",
    "FontKerning",
    "FontLanguageOverride",
    "FontOpticalSizing",
    "FontPalette",
    "FontSize",
    "FontSizeAdjust",
    "FontStyle",
    "FontSynthesis",
    "FontSynthesisSmallCaps",
    "FontSynthesisStyle",
    "FontSynthesisWeight",
    "FontVariant",
    "FontVariantAlternates",
    "FontVariantCaps",
    "FontVariantEastAsian",
    "FontVariantEmoji",
    "FontVariantLigatures",
    "FontVariantNumeric",
    "FontVariantPosition",
    "FontVariationSettings",
    "FontWeight",
    "ForcedColorAdjust",
    "Gap",
    "Grid",
    "GridArea",
    "GridAutoColumns",
    "GridAutoFlow",
    "GridAutoRows",
    "GridColumn",
    "GridColumnEnd",
    "GridColumnStart",
    "GridRow",
    "GridRowEnd",
    "GridRowStart",
    "GridTemplate",
    "GridTemplateAreas",
    "GridTemplateColumns",
    "GridTemplateRows",
    "HangingPunctuation",
    "Height",
    "HyphenateCharacter",
    "HyphenateLimitChars",
    "Hyphens",
    "ImageOrientation",
    "ImageRendering",
    "InitialLetter",
    "InlineSize",
    "Inset",
    "InsetBlock",
    "InsetBlockEnd",
    "InsetBlockStart",
    "InsetInline",
    "InsetInlineEnd",
    "InsetInlineStart",
    "Interactivity",
    "InterestDelay",
    "InterestDelayEnd",
    "InterestDelayStart",
    "Isolation",
    "JustifyContent",
    "JustifyItems",
    "JustifySelf",
    "Left",
    "LetterSpacing",
    "LightingColor",
    "LineBreak",
    "LineClamp",
    "LineHeight",
    "ListStyle",
    "ListStyleImage",
    "ListStylePosition",
    "ListStyleType",
    "Margin",
    "MarginBlock",
    "MarginBlockEnd",
    "MarginBlockStart",
    "MarginBottom",
    "MarginInline",
    "MarginInlineEnd",
    "MarginInlineStart",
    "MarginLeft",
    "MarginRight",
    "MarginTop",
    "Marker",
    "MarkerEnd",
    "MarkerMid",
    "MarkerStart",
    "Mask",
    "MaskBorder",
    "MaskBorderMode",
    "MaskBorderOutset",
    "MaskBorderRepeat",
    "MaskBorderSlice",
    "MaskBorderSource",
    "MaskBorderWidth",
    "MaskClip",
    "MaskComposite",
    "MaskImage",
    "MaskMode",
    "MaskOrigin",
    "MaskPosition",
    "MaskRepeat",
    "MaskSize",
    "MaskType",
    "MathDepth",
    "MathStyle",
    "MaxBlockSize",
    "MaxHeight",
    "MaxInlineSize",
    "MaxWidth",
    "MinBlockSize",
    "MinHeight",
    "MinInlineSize",
    "MinWidth",
    "MixBlendMode",
    "ObjectFit",
    "ObjectPosition",
    "Offset",
    "OffsetAnchor",
    "OffsetDistance",
    "OffsetPath",
    "OffsetPosition",
    "OffsetRotate",
    "Opacity",
    "Order",
    "Orphans",
    "Outline",
    "OutlineColor",
    "OutlineOffset",
    "OutlineStyle",
    "OutlineWidth",
    "Overflow",
    "OverflowAnchor",
    "OverflowBlock",
    "OverflowClipMargin",
    "OverflowInline",
    "OverflowWrap",
    "OverflowX",
    "OverflowY",
    "OverscrollBehavior",
    "OverscrollBehaviorBlock",
    "OverscrollBehaviorInline",
    "OverscrollBehaviorX",
    "OverscrollBehaviorY",
    "Padding",
    "PaddingBlock",
    "PaddingBlockEnd",
    "PaddingBlockStart",
    "PaddingBottom",
    "PaddingInline",
    "PaddingInlineEnd",
    "PaddingInlineStart",
    "PaddingLeft",
    "PaddingRight",
    "PaddingTop",
    "Page",
    "PaintOrder",
    "Perspective",
    "PerspectiveOrigin",
    "PlaceContent",
    "PlaceItems",
    "PlaceSelf",
    "PointerEvents",
    "Position",
    "PrintColorAdjust",
    "Quotes",
    "R",
    "ReadingFlow",
    "ReadingOrder",
    "Resize",
    "Right",
    "Rotate",
    "RowGap",
    "RubyAlign",
    "RubyOverhang",
    "RubyPosition",
    "Rx",
    "Ry",
    "Scale",
    "ScrollBehavior",
    "ScrollMargin",
    "ScrollMarginBlock",
    "ScrollMarginBlockEnd",
    "ScrollMarginBlockStart",
    "ScrollMarginBottom",
    "ScrollMarginInline",
    "ScrollMarginInlineEnd",
    "ScrollMarginInlineStart",
    "ScrollMarginLeft",
    "ScrollMarginRight",
    "ScrollMarginTop",
    "ScrollMarkerGroup",
    "ScrollPadding",
    "ScrollPaddingBlock",
    "ScrollPaddingBlockEnd",
    "ScrollPaddingBlockStart",
    "ScrollPaddingBottom",
    "ScrollPaddingInline",
    "ScrollPaddingInlineEnd",
    "ScrollPaddingInlineStart",
    "ScrollPaddingLeft",
    "ScrollPaddingRight",
    "ScrollPaddingTop",
    "ScrollSnapAlign",
    "ScrollSnapStop",
    "ScrollSnapType",
    "ScrollTargetGroup",
    "ScrollbarColor",
    "ScrollbarGutter",
    "ScrollbarWidth",
    "ShapeImageThreshold",
    "ShapeMargin",
    "ShapeOutside",
    "ShapeRendering",
    "StopColor",
    "StopOpacity",
    "Stroke",
    "StrokeDasharray",
    "StrokeDashoffset",
    "StrokeLinecap",
    "StrokeLinejoin",
    "StrokeMiterlimit",
    "StrokeOpacity",
    "StrokeWidth",
    "TabSize",
    "TableLayout",
    "TextAlign",
    "TextAlignLast",
    "TextAnchor",
    "TextAutospace",
    "TextBox",
    "TextBoxEdge",
    "TextBoxTrim",
    "TextCombineUpright",
    "TextDecoration",
    "TextDecorationColor",
    "TextDecorationInset",
    "TextDecorationLine",
    "TextDecorationSkipInk",
    "TextDecorationStyle",
    "TextDecorationThickness",
    "TextEmphasis",
    "TextEmphasisColor",
    "TextEmphasisPosition",
    "TextEmphasisStyle",
    "TextIndent",
    "TextJustify",
    "TextOrientation",
    "TextOverflow",
    "TextRendering",
    "TextShadow",
    "TextTransform",
    "TextUnderlineOffset",
    "TextUnderlinePosition",
    "TextWrap",
    "TextWrapMode",
    "TextWrapStyle",
    "TimelineTrigger",
    "TimelineTriggerExitRange",
    "TimelineTriggerExitRangeEnd",
    "TimelineTriggerExitRangeStart",
    "TimelineTriggerName",
    "TimelineTriggerRange",
    "TimelineTriggerRangeEnd",
    "TimelineTriggerRangeStart",
    "TimelineTriggerSource",
    "Top",
    "TouchAction",
    "Transform",
    "TransformBox",
    "TransformOrigin",
    "TransformStyle",
    "Transition",
    "TransitionBehavior",
    "TransitionDelay",
    "TransitionDuration",
    "TransitionProperty",
    "TransitionTimingFunction",
    "Translate",
    "TriggerScope",
    "UnicodeBidi",
    "UserSelect",
    "VectorEffect",
    "VerticalAlign",
    "ViewTransitionClass",
    "ViewTransitionName",
    "Visibility",
    "WhiteSpace",
    "WhiteSpaceCollapse",
    "Widows",
    "Width",
    "WillChange",
    "WordBreak",
    "WordSpacing",
    "WordWrap",
    "WritingMode",
    "X",
    "Y",
    "ZIndex",
    "Zoom",
};

/// 解析 CSS 属性名，返回与之匹配的强类型 Struct 名称或错误
pub fn resolve_property_type(prop: &str, span: Span) -> Result<PropertyResolveResult> {
    // 1. 自定义 CSS 变量 (--*) 统一映射为 props::Any
    if prop.starts_with("--") {
        return Ok(PropertyResolveResult::CustomVar);
    }

    // 2. 短别名优先 PHF 查表
    if let Some(&type_name) = SHORT_ALIAS_MAP.get(prop) {
        return Ok(PropertyResolveResult::Builtin(type_name));
    }

    // 3. 将 kebab-case 转换为 PascalCase 并查询标准 PHF 属性哈希表
    let mut pascal = String::with_capacity(prop.len());
    for part in prop.split('-') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            pascal.extend(first.to_uppercase());
            pascal.push_str(chars.as_str());
        }
    }

    if let Some(&type_name) = STANDARD_PASCAL_MAP.get(pascal.as_str()) {
        return Ok(PropertyResolveResult::Builtin(type_name));
    }

    // 4. 既不是 CSS 变量，也不是合法标准 CSS 属性，直接返回明确的过程宏编译报错
    Err(syn::Error::new(
        span,
        format!(
            "未知的 CSS 属性 '{}'。如果是自定义 CSS 变量，请使用 '--{}' 格式；请检查拼写。",
            prop, prop
        ),
    ))
}
