[package]
name = "silex_macros_test"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
silex_core.workspace = true
silex_css = { workspace = true, features = ["tw"] }
silex_dom.workspace = true
silex_view.workspace = true
silex_html.workspace = true
silex_macros = { workspace = true, default-features = false, features = ["component", "css", "tw", "store"] }
silex_persist.workspace = true
silex_rx.workspace = true
web-sys.workspace = true

[dev-dependencies]
trybuild = "1.0"
wasm-bindgen-test.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
