// 自动生成的 Utility 前缀与单位元数据表（供 silex_macros 使用）
// 由 silex_codegen 自动生成，切勿手写修改！

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnitKind {
    RemScale,
    Pixel,
    Percentage,
    Degree,
    Milliseconds,
    Unitless,
    GridRepeat,
    GridSpan,
}

pub struct PrefixMeta {
    pub prefix: &'static str,
    pub target_props: &'static [&'static str],
    pub unit_kind: UnitKind,
}

#[rustfmt::skip]
pub static PREFIX_METADATA: &[PrefixMeta] = &[
    PrefixMeta { prefix: "auto-cols", target_props: &["grid-auto-columns"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "auto-rows", target_props: &["grid-auto-rows"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "backdrop-blur", target_props: &["backdrop-filter"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "blur", target_props: &["filter"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border", target_props: &["border-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border-b", target_props: &["border-bottom-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border-l", target_props: &["border-left-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border-r", target_props: &["border-right-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border-t", target_props: &["border-top-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border-x", target_props: &["border-left-width", "border-right-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "border-y", target_props: &["border-top-width", "border-bottom-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "bottom", target_props: &["bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "col-end", target_props: &["grid-column-end"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "col-span", target_props: &["grid-column"], unit_kind: UnitKind::GridSpan },
    PrefixMeta { prefix: "col-start", target_props: &["grid-column-start"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "columns", target_props: &["column-count"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "delay", target_props: &["transition-delay"], unit_kind: UnitKind::Milliseconds },
    PrefixMeta { prefix: "duration", target_props: &["transition-duration"], unit_kind: UnitKind::Milliseconds },
    PrefixMeta { prefix: "fade-in", target_props: &["--tw-enter-opacity"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "fade-out", target_props: &["--tw-exit-opacity"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "gap", target_props: &["gap"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "gap-x", target_props: &["column-gap"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "gap-y", target_props: &["row-gap"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "grid-cols", target_props: &["grid-template-columns"], unit_kind: UnitKind::GridRepeat },
    PrefixMeta { prefix: "grid-rows", target_props: &["grid-template-rows"], unit_kind: UnitKind::GridRepeat },
    PrefixMeta { prefix: "h", target_props: &["height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "height", target_props: &["height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "inset", target_props: &["top", "right", "bottom", "left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "inset-x", target_props: &["left", "right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "inset-y", target_props: &["top", "bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "left", target_props: &["left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "line-clamp", target_props: &["-webkit-line-clamp"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "m", target_props: &["margin"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "margin", target_props: &["margin"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "max-h", target_props: &["max-height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "max-w", target_props: &["max-width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "mb", target_props: &["margin-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "min-h", target_props: &["min-height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "min-w", target_props: &["min-width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "ml", target_props: &["margin-left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "mr", target_props: &["margin-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "mt", target_props: &["margin-top"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "mx", target_props: &["margin-left", "margin-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "my", target_props: &["margin-top", "margin-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "opacity", target_props: &["opacity"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "outline", target_props: &["outline-width"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "p", target_props: &["padding"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "padding", target_props: &["padding"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "pb", target_props: &["padding-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "pl", target_props: &["padding-left"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "pr", target_props: &["padding-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "pt", target_props: &["padding-top"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "px", target_props: &["padding-left", "padding-right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "py", target_props: &["padding-top", "padding-bottom"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "right", target_props: &["right"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "rotate", target_props: &["transform"], unit_kind: UnitKind::Degree },
    PrefixMeta { prefix: "row-end", target_props: &["grid-row-end"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "row-span", target_props: &["grid-row"], unit_kind: UnitKind::GridSpan },
    PrefixMeta { prefix: "row-start", target_props: &["grid-row-start"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "scale", target_props: &["transform"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "scale-x", target_props: &["transform"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "scale-y", target_props: &["transform"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "size", target_props: &["width", "height"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "skew-x", target_props: &["transform"], unit_kind: UnitKind::Degree },
    PrefixMeta { prefix: "skew-y", target_props: &["transform"], unit_kind: UnitKind::Degree },
    PrefixMeta { prefix: "slide-in-from-bottom", target_props: &["--tw-enter-translate-y"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "slide-in-from-left", target_props: &["--tw-enter-translate-x"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "slide-in-from-right", target_props: &["--tw-enter-translate-x"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "slide-in-from-top", target_props: &["--tw-enter-translate-y"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "top", target_props: &["top"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "translate-x", target_props: &["transform"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "translate-y", target_props: &["transform"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "underline-offset", target_props: &["text-underline-offset"], unit_kind: UnitKind::Pixel },
    PrefixMeta { prefix: "w", target_props: &["width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "width", target_props: &["width"], unit_kind: UnitKind::RemScale },
    PrefixMeta { prefix: "z", target_props: &["z-index"], unit_kind: UnitKind::Unitless },
    PrefixMeta { prefix: "zoom-in", target_props: &["--tw-enter-scale"], unit_kind: UnitKind::Percentage },
    PrefixMeta { prefix: "zoom-out", target_props: &["--tw-exit-scale"], unit_kind: UnitKind::Percentage },
];

/// 根据 Utility 前缀二分查找对应的元数据配置
pub fn lookup_prefix_meta(prefix: &str) -> Option<&'static PrefixMeta> {
    let idx = PREFIX_METADATA.binary_search_by_key(&prefix, |m| m.prefix).ok()?;
    Some(&PREFIX_METADATA[idx])
}
