name: Deploy Zola site to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - '.github/workflows/zola.yml'

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.23.3

      - name: Check Zola site
        run: zola --root docs check

      - name: Build Zola site
        run: zola --root docs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
